/*
Wilson Maintenance Portal - SQL Server migration v0.9
Generated by sql/generate_migration_v09.py -- do not hand-edit.
Edit sql/_migration_v09_ddl.sql (structure) or assets/plan-config.js (seed data)
and re-run the generator.

Purpose
-------
Implements MERGE_GUIDE.md section 7: the schema additions required before the
real merge. sql/maintenance_schema.sql is at v0.3 (2026-08-21) and predates the
v0.5-v0.9 field workflow entirely -- it has no tables for technician
inspections, checkpoints, readings, photos, areas, or lifecycle/brand tier, and
its health-report tables still reflect the report builder that v0.7 retired.

Covers:
  7.1  Property areas                     MaintenanceAreas, MaintenanceAssets.AreaId
  7.2  Household billing method / AR      MaintenanceHouseholds billing columns
  7.3  Raw technician inspection data     MaintenanceFieldInspections (+Checks, +Photos)
  7.4  Report delivery tracking           MaintenanceReportDeliveries
  7.5  Technician assignment / user id    MaintenanceVisits technician columns
  7.6  Lifecycle configuration            MaintenanceLifecycleTiers, MaintenanceBrandTiers,
                                          MaintenanceExpectedLifeRules, MaintenanceLifecycleStages
  7.7  Protocol configuration             MaintenanceProtocolTemplates, MaintenanceProtocolCheckpoints,
                                          MaintenanceProtocolAssignments
  7.8  Filter service pricing (added)     MaintenanceFilterPrices, plus per-asset
                                          filter opt-in/quantity columns and the
  7.9  Age provenance + photo evidence   MaintenanceAgeSources, MaintenanceAssets
                                         install/age-source columns, field-inspection
                                         age source, photo upload reconciliation
                                          subscription filter-service amount

Status codes use the centralized vocabularies from MERGE_GUIDE section 34 and
are enforced with CHECK constraints, so a UI phrase can never be persisted as
state.

Applying this script
--------------------
Run sql/maintenance_schema.sql first. This script is strictly additive and
idempotent: every object is guarded, every column addition is guarded by
COL_LENGTH, and every seed is a MERGE. Re-running it is safe and is the
intended way to pick up protocol changes.

It deliberately does NOT redefine any existing object. sql/maintenance_schema.sql
ends with three CREATE OR ALTER VIEW statements; if this migration altered one of
them, a later re-run of the base script would silently revert it. New behaviour
is therefore delivered as new views instead.

Not covered here
----------------
- Retiring the office-built report tables (MaintenanceHealthReport* still carry
  the pre-v0.7 model). They are left intact because live prototype data may
  reference them; plan their retirement with the API contract rewrite.
- Photo binary storage. Only the storage key is modelled -- see MERGE_GUIDE
  section 20.
- HVAC field protocols. No HVAC field workflow exists yet (context section 34
  item 3), so no HVAC protocol templates are seeded.

Security
--------
No cardholder data. Technician identity is stored as the authoritative internal
user id plus a display-name snapshot for historical reporting.
*/

SET NOCOUNT ON;
SET XACT_ABORT ON;
GO

/* -------------------------------------------------------------------------
   Preflight: the base schema must already be present
   ------------------------------------------------------------------------- */
IF OBJECT_ID('dbo.MaintenanceHouseholds', 'U') IS NULL
    OR OBJECT_ID('dbo.MaintenanceAssets', 'U') IS NULL
    OR OBJECT_ID('dbo.MaintenanceVisits', 'U') IS NULL
    OR OBJECT_ID('dbo.MaintenanceHealthReports', 'U') IS NULL
BEGIN
    RAISERROR (
        'Base maintenance schema not found. Run sql/maintenance_schema.sql before this migration.',
        20, 1
    ) WITH LOG;
END;
GO

/* -------------------------------------------------------------------------
   7.1  Property areas
   ------------------------------------------------------------------------- */
IF OBJECT_ID('dbo.MaintenanceAreas', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.MaintenanceAreas (
        AreaId INT IDENTITY(1,1) NOT NULL
            CONSTRAINT PK_MaintenanceAreas PRIMARY KEY,
        HouseholdId INT NOT NULL,
        AreaName NVARCHAR(150) NOT NULL,
        AreaKind NVARCHAR(30) NULL,
        SortOrder INT NULL,
        AreaStatus NVARCHAR(30) NOT NULL
            CONSTRAINT DF_MaintenanceAreas_Status DEFAULT ('Active'),
        CreatedAt DATETIME2 NOT NULL
            CONSTRAINT DF_MaintenanceAreas_CreatedAt DEFAULT SYSUTCDATETIME(),
        UpdatedAt DATETIME2 NOT NULL
            CONSTRAINT DF_MaintenanceAreas_UpdatedAt DEFAULT SYSUTCDATETIME(),
        VersionStamp ROWVERSION,
        CONSTRAINT FK_MaintenanceAreas_Households
            FOREIGN KEY (HouseholdId) REFERENCES dbo.MaintenanceHouseholds(HouseholdId)
    );

    CREATE UNIQUE INDEX UX_MaintenanceAreas_HouseholdName
        ON dbo.MaintenanceAreas(HouseholdId, AreaName);

    CREATE INDEX IX_MaintenanceAreas_Household
        ON dbo.MaintenanceAreas(HouseholdId, AreaStatus, SortOrder);
END;
GO

/* AreaId on assets. LocationName is kept as the text snapshot the customer and
   invoice import actually entered -- see MERGE_GUIDE 7.1. */
IF COL_LENGTH('dbo.MaintenanceAssets', 'AreaId') IS NULL
    ALTER TABLE dbo.MaintenanceAssets ADD AreaId INT NULL;
GO
IF OBJECT_ID('dbo.FK_MaintenanceAssets_Areas', 'F') IS NULL
    ALTER TABLE dbo.MaintenanceAssets ADD CONSTRAINT FK_MaintenanceAssets_Areas
        FOREIGN KEY (AreaId) REFERENCES dbo.MaintenanceAreas(AreaId);
GO
IF NOT EXISTS (
    SELECT 1 FROM sys.indexes
    WHERE name = 'IX_MaintenanceAssets_Area'
      AND object_id = OBJECT_ID('dbo.MaintenanceAssets')
)
    CREATE INDEX IX_MaintenanceAssets_Area
        ON dbo.MaintenanceAssets(AreaId, SortOrder);
GO

/* -------------------------------------------------------------------------
   7.2  Household billing method / AR

   Added as columns on MaintenanceHouseholds rather than a separate 1:1 billing
   profile table (MERGE_GUIDE 7.2 permits either). Command Center payment
   readiness is a per-household question on nearly every queue query, and a 1:1
   table would add a join to all of them for four columns with no history
   requirement. MaintenancePaymentProfiles already holds the card-side rows.
   ------------------------------------------------------------------------- */
IF COL_LENGTH('dbo.MaintenanceHouseholds', 'BillingMethodCode') IS NULL
    ALTER TABLE dbo.MaintenanceHouseholds ADD BillingMethodCode NVARCHAR(30) NOT NULL
        CONSTRAINT DF_MaintenanceHouseholds_BillingMethod DEFAULT ('CARD_ON_FILE');
GO
IF COL_LENGTH('dbo.MaintenanceHouseholds', 'AccountTerms') IS NULL
    ALTER TABLE dbo.MaintenanceHouseholds ADD AccountTerms NVARCHAR(50) NULL;
GO
IF COL_LENGTH('dbo.MaintenanceHouseholds', 'ExternalARCustomerId') IS NULL
    ALTER TABLE dbo.MaintenanceHouseholds ADD ExternalARCustomerId NVARCHAR(100) NULL;
GO
IF COL_LENGTH('dbo.MaintenanceHouseholds', 'ARStatus') IS NULL
    ALTER TABLE dbo.MaintenanceHouseholds ADD ARStatus NVARCHAR(30) NULL;
GO
IF OBJECT_ID('dbo.CK_MaintenanceHouseholds_BillingMethod', 'C') IS NULL
    ALTER TABLE dbo.MaintenanceHouseholds
        ADD CONSTRAINT CK_MaintenanceHouseholds_BillingMethod
        CHECK (BillingMethodCode IN ('CARD_ON_FILE', 'AR_ACCOUNT'));
GO
IF OBJECT_ID('dbo.CK_MaintenanceHouseholds_ARStatus', 'C') IS NULL
    ALTER TABLE dbo.MaintenanceHouseholds
        ADD CONSTRAINT CK_MaintenanceHouseholds_ARStatus
        CHECK (ARStatus IS NULL OR ARStatus IN ('Active', 'Hold', 'Review'));
GO

/* -------------------------------------------------------------------------
   7.6 / 7.7  Configuration tables

   Table definitions only; seed data is generated at the end of this script.
   ------------------------------------------------------------------------- */
IF OBJECT_ID('dbo.MaintenanceLifecycleTiers', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.MaintenanceLifecycleTiers (
        LifecycleTierId INT IDENTITY(1,1) NOT NULL
            CONSTRAINT PK_MaintenanceLifecycleTiers PRIMARY KEY,
        TierCode NVARCHAR(20) NOT NULL
            CONSTRAINT UQ_MaintenanceLifecycleTiers_Code UNIQUE,
        TierLabel NVARCHAR(50) NOT NULL,
        DefaultExpectedYears DECIMAL(5,1) NULL,
        ExampleBrands NVARCHAR(500) NULL,
        IsActive BIT NOT NULL
            CONSTRAINT DF_MaintenanceLifecycleTiers_Active DEFAULT (1),
        CreatedAt DATETIME2 NOT NULL
            CONSTRAINT DF_MaintenanceLifecycleTiers_CreatedAt DEFAULT SYSUTCDATETIME(),
        UpdatedAt DATETIME2 NOT NULL
            CONSTRAINT DF_MaintenanceLifecycleTiers_UpdatedAt DEFAULT SYSUTCDATETIME()
    );
END;
GO

IF OBJECT_ID('dbo.MaintenanceBrandTiers', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.MaintenanceBrandTiers (
        BrandTierId INT IDENTITY(1,1) NOT NULL
            CONSTRAINT PK_MaintenanceBrandTiers PRIMARY KEY,
        BrandMatchText NVARCHAR(100) NOT NULL
            CONSTRAINT UQ_MaintenanceBrandTiers_Match UNIQUE,
        MatchType NVARCHAR(20) NOT NULL
            CONSTRAINT DF_MaintenanceBrandTiers_MatchType DEFAULT ('CONTAINS'),
        TierCode NVARCHAR(20) NOT NULL,
        SortOrder INT NULL,
        IsActive BIT NOT NULL
            CONSTRAINT DF_MaintenanceBrandTiers_Active DEFAULT (1),
        CreatedAt DATETIME2 NOT NULL
            CONSTRAINT DF_MaintenanceBrandTiers_CreatedAt DEFAULT SYSUTCDATETIME(),
        UpdatedAt DATETIME2 NOT NULL
            CONSTRAINT DF_MaintenanceBrandTiers_UpdatedAt DEFAULT SYSUTCDATETIME(),
        CONSTRAINT CK_MaintenanceBrandTiers_MatchType
            CHECK (MatchType IN ('EXACT', 'CONTAINS'))
    );

    CREATE INDEX IX_MaintenanceBrandTiers_Lookup
        ON dbo.MaintenanceBrandTiers(IsActive, SortOrder);
END;
GO

IF OBJECT_ID('dbo.MaintenanceProtocolTemplates', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.MaintenanceProtocolTemplates (
        ProtocolTemplateId INT IDENTITY(1,1) NOT NULL
            CONSTRAINT PK_MaintenanceProtocolTemplates PRIMARY KEY,
        TemplateCode NVARCHAR(50) NOT NULL,
        TemplateName NVARCHAR(150) NOT NULL,
        TemplateVersion INT NOT NULL
            CONSTRAINT DF_MaintenanceProtocolTemplates_Version DEFAULT (1),
        TemplateNote NVARCHAR(500) NULL,
        SourceConfigVersion NVARCHAR(50) NULL,
        IsActive BIT NOT NULL
            CONSTRAINT DF_MaintenanceProtocolTemplates_Active DEFAULT (1),
        CreatedAt DATETIME2 NOT NULL
            CONSTRAINT DF_MaintenanceProtocolTemplates_CreatedAt DEFAULT SYSUTCDATETIME(),
        UpdatedAt DATETIME2 NOT NULL
            CONSTRAINT DF_MaintenanceProtocolTemplates_UpdatedAt DEFAULT SYSUTCDATETIME(),
        CONSTRAINT UQ_MaintenanceProtocolTemplates_CodeVersion
            UNIQUE (TemplateCode, TemplateVersion)
    );
END;
GO

IF OBJECT_ID('dbo.MaintenanceProtocolCheckpoints', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.MaintenanceProtocolCheckpoints (
        ProtocolCheckpointId INT IDENTITY(1,1) NOT NULL
            CONSTRAINT PK_MaintenanceProtocolCheckpoints PRIMARY KEY,
        ProtocolTemplateId INT NOT NULL,
        CheckpointCode NVARCHAR(50) NOT NULL,
        CheckpointName NVARCHAR(300) NOT NULL,
        PromptText NVARCHAR(MAX) NULL,
        GuidanceText NVARCHAR(MAX) NULL,
        ReadingLabel NVARCHAR(150) NULL,
        ReadingFieldsJson NVARCHAR(MAX) NULL,
        DerivedReadingCode NVARCHAR(50) NULL,
        ReadingUnit NVARCHAR(30) NULL,
        PhotoPromptText NVARCHAR(300) NULL,
        RatingRequired BIT NOT NULL
            CONSTRAINT DF_MaintenanceProtocolCheckpoints_RatingRequired DEFAULT (1),
        SortOrder INT NULL,
        IsActive BIT NOT NULL
            CONSTRAINT DF_MaintenanceProtocolCheckpoints_Active DEFAULT (1),
        CreatedAt DATETIME2 NOT NULL
            CONSTRAINT DF_MaintenanceProtocolCheckpoints_CreatedAt DEFAULT SYSUTCDATETIME(),
        UpdatedAt DATETIME2 NOT NULL
            CONSTRAINT DF_MaintenanceProtocolCheckpoints_UpdatedAt DEFAULT SYSUTCDATETIME(),
        CONSTRAINT FK_MaintenanceProtocolCheckpoints_Templates
            FOREIGN KEY (ProtocolTemplateId)
            REFERENCES dbo.MaintenanceProtocolTemplates(ProtocolTemplateId),
        CONSTRAINT UQ_MaintenanceProtocolCheckpoints_Code
            UNIQUE (ProtocolTemplateId, CheckpointCode)
    );

    CREATE INDEX IX_MaintenanceProtocolCheckpoints_Template
        ON dbo.MaintenanceProtocolCheckpoints(ProtocolTemplateId, SortOrder);
END;
GO

/* -------------------------------------------------------------------------
   v0.9.17: WHAT KIND OF ANSWER A CHECKPOINT TAKES, IN THE DATABASE.

   Until now every checkpoint carried a rating and every rating averaged into
   the health score. That is how "Maintenance clean cycle -- performed" -- work
   Wilson was paid to do -- ended up raising the customer's number, and how a
   technician's judgement of an evaporator frost pattern carried the same weight
   as a measured compartment temperature.

   The browser now resolves this through WILSON_ANSWERS.scorable() in
   plan-config.js. These columns carry the same rule into SQL Server, because
   the dashboard will eventually compute the score here, and a rule that lives
   in only one of the two places is a rule that will disagree with itself.

       ResultKind    scored | maintenance | observed | trend
       ScoresHealth  1 only where ResultKind = 'scored', enforced below
       AnswerControl which tap-only control the field tool renders
       OptionSetCode the observation or pass/fail set the options come from

   CK_..._ScoresOnlyScored is the guardrail, not documentation: it makes
   "work performed raises the health score" unrepresentable rather than merely
   discouraged. Any future seed that tries it fails the insert.
   ------------------------------------------------------------------------- */
IF COL_LENGTH('dbo.MaintenanceProtocolCheckpoints', 'ResultKind') IS NULL
    ALTER TABLE dbo.MaintenanceProtocolCheckpoints ADD ResultKind NVARCHAR(20) NOT NULL
        CONSTRAINT DF_MaintenanceProtocolCheckpoints_ResultKind DEFAULT ('scored');
GO

IF COL_LENGTH('dbo.MaintenanceProtocolCheckpoints', 'ScoresHealth') IS NULL
    ALTER TABLE dbo.MaintenanceProtocolCheckpoints ADD ScoresHealth BIT NOT NULL
        CONSTRAINT DF_MaintenanceProtocolCheckpoints_ScoresHealth DEFAULT (1);
GO

IF COL_LENGTH('dbo.MaintenanceProtocolCheckpoints', 'AnswerControl') IS NULL
    ALTER TABLE dbo.MaintenanceProtocolCheckpoints ADD AnswerControl NVARCHAR(20) NULL;
GO

IF COL_LENGTH('dbo.MaintenanceProtocolCheckpoints', 'OptionSetCode') IS NULL
    ALTER TABLE dbo.MaintenanceProtocolCheckpoints ADD OptionSetCode NVARCHAR(40) NULL;
GO

IF OBJECT_ID('dbo.CK_MaintenanceProtocolCheckpoints_ResultKind', 'C') IS NULL
    ALTER TABLE dbo.MaintenanceProtocolCheckpoints
        ADD CONSTRAINT CK_MaintenanceProtocolCheckpoints_ResultKind
        CHECK (ResultKind IN ('scored', 'maintenance', 'observed', 'trend'));
GO
IF OBJECT_ID('dbo.CK_MaintenanceProtocolCheckpoints_ScoresOnlyScored', 'C') IS NULL
    ALTER TABLE dbo.MaintenanceProtocolCheckpoints
        ADD CONSTRAINT CK_MaintenanceProtocolCheckpoints_ScoresOnlyScored
        CHECK (ScoresHealth = 0 OR ResultKind = 'scored');
GO

/* -------------------------------------------------------------------------
   v0.9.19: THE ANSWERS A CHECKPOINT ACCEPTS, AND WHAT EACH ONE IS WORTH.

   Conditions score now. The reason that is defensible rather than reckless is
   that the value of every answer is written down in advance, shown to the
   technician on the button, and identical on every visit and every appliance --
   so "cloudy or incomplete cubes" is worth the same 3 whoever taps it.

   Those values lived only in plan-config.js, which is fine while the browser
   computes the score and useless the moment the dashboard has to. This table is
   where they live in SQL Server, seeded from the same config, with the parity
   asserted by _qa/verify-sql-migration.py.

       ScoreValue     1-5, or NULL for "could not get to it", which scores
                      nothing and is never a failure
       RaisesFinding  independent of the score: heavy build-up beyond reach is
                      worth a 3 AND needs saying out loud, and a full-marks
                      answer never raises one
       RequiresDetail the answer owes a follow-up ('code' so far) and the check
                      is not complete without it

   CK_..._ScoreRange is the guardrail: a score outside 1-5 cannot be stored, so
   a bad seed fails the insert instead of quietly deflating somebody's report.
   ------------------------------------------------------------------------- */
IF OBJECT_ID('dbo.MaintenanceCheckpointOptions', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.MaintenanceCheckpointOptions (
        CheckpointOptionId INT IDENTITY(1,1) NOT NULL
            CONSTRAINT PK_MaintenanceCheckpointOptions PRIMARY KEY,
        ProtocolCheckpointId INT NOT NULL,
        OptionSetCode NVARCHAR(40) NULL,
        OptionCode NVARCHAR(40) NOT NULL,
        OptionLabel NVARCHAR(200) NOT NULL,
        ResultText NVARCHAR(100) NOT NULL,
        ScoreValue TINYINT NULL,
        RaisesFinding BIT NOT NULL
            CONSTRAINT DF_MaintenanceCheckpointOptions_RaisesFinding DEFAULT (0),
        RequiresDetail NVARCHAR(20) NULL,
        SortOrder INT NULL,
        IsActive BIT NOT NULL
            CONSTRAINT DF_MaintenanceCheckpointOptions_Active DEFAULT (1),
        CreatedAt DATETIME2 NOT NULL
            CONSTRAINT DF_MaintenanceCheckpointOptions_CreatedAt DEFAULT SYSUTCDATETIME(),
        UpdatedAt DATETIME2 NOT NULL
            CONSTRAINT DF_MaintenanceCheckpointOptions_UpdatedAt DEFAULT SYSUTCDATETIME(),
        CONSTRAINT FK_MaintenanceCheckpointOptions_Checkpoints
            FOREIGN KEY (ProtocolCheckpointId)
            REFERENCES dbo.MaintenanceProtocolCheckpoints(ProtocolCheckpointId),
        CONSTRAINT UQ_MaintenanceCheckpointOptions_Code
            UNIQUE (ProtocolCheckpointId, OptionCode),
        CONSTRAINT CK_MaintenanceCheckpointOptions_ScoreRange
            CHECK (ScoreValue IS NULL OR ScoreValue BETWEEN 1 AND 5)
    );

    CREATE INDEX IX_MaintenanceCheckpointOptions_Checkpoint
        ON dbo.MaintenanceCheckpointOptions(ProtocolCheckpointId, SortOrder);
END;
GO

/* -------------------------------------------------------------------------
   The scoring gate, as a view.

   Anything computing a health score reads THIS, not the checkpoints table, so
   the exclusion cannot be forgotten in a WHERE clause. Every other checkpoint
   is still recorded, still printed for the customer, and still photographed --
   it simply does not move the number.
   ------------------------------------------------------------------------- */
IF OBJECT_ID('dbo.vw_MaintenanceScoringCheckpoints', 'V') IS NOT NULL
    DROP VIEW dbo.vw_MaintenanceScoringCheckpoints;
GO

CREATE VIEW dbo.vw_MaintenanceScoringCheckpoints
AS
SELECT
    c.ProtocolCheckpointId,
    c.ProtocolTemplateId,
    t.TemplateCode,
    t.TemplateVersion,
    c.CheckpointCode,
    c.CheckpointName,
    c.ResultKind,
    c.AnswerControl,
    c.OptionSetCode,
    c.ReadingLabel,
    c.ReadingUnit,
    c.SortOrder
FROM dbo.MaintenanceProtocolCheckpoints c
INNER JOIN dbo.MaintenanceProtocolTemplates t
    ON t.ProtocolTemplateId = c.ProtocolTemplateId
WHERE c.IsActive = 1
  AND c.ScoresHealth = 1
  AND c.ResultKind = 'scored';
GO

/*
   Protocol assignment: which template applies to a given appliance.

   This is the SQL form of WILSON_PROTOCOL.resolveCheckpointSet() in
   plan-config.js. Resolution walks assignments in Precedence order and takes
   the first active match:

       Precedence 10  APPLIANCE_TYPE      matched on MaintenanceAssets.AssetTypeCode
       Precedence 20  CUSTOMER_CATEGORY   matched on MaintenanceAssets.CustomerCategoryCode

   MaintenanceAssets.CheckpointSetCode remains as the value captured at
   enrollment, but it is a snapshot, NOT the resolution input -- exactly as in
   the JS resolver. Assets created before v0.9.1 hold four known-wrong values
   (Ventilation as generic, Microwave as cooking, Washer and Dryer as laundry);
   resolving through these assignments corrects them with no data migration.
   IMUC group membership still wins over both scopes and is applied in code.
*/
IF OBJECT_ID('dbo.MaintenanceProtocolAssignments', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.MaintenanceProtocolAssignments (
        ProtocolAssignmentId INT IDENTITY(1,1) NOT NULL
            CONSTRAINT PK_MaintenanceProtocolAssignments PRIMARY KEY,
        AssignmentScope NVARCHAR(30) NOT NULL,
        ScopeCode NVARCHAR(50) NOT NULL,
        ScopeLabel NVARCHAR(150) NULL,
        TemplateCode NVARCHAR(50) NOT NULL,
        Precedence INT NOT NULL
            CONSTRAINT DF_MaintenanceProtocolAssignments_Precedence DEFAULT (20),
        IsActive BIT NOT NULL
            CONSTRAINT DF_MaintenanceProtocolAssignments_Active DEFAULT (1),
        CreatedAt DATETIME2 NOT NULL
            CONSTRAINT DF_MaintenanceProtocolAssignments_CreatedAt DEFAULT SYSUTCDATETIME(),
        UpdatedAt DATETIME2 NOT NULL
            CONSTRAINT DF_MaintenanceProtocolAssignments_UpdatedAt DEFAULT SYSUTCDATETIME(),
        CONSTRAINT UQ_MaintenanceProtocolAssignments_Scope
            UNIQUE (AssignmentScope, ScopeCode),
        CONSTRAINT CK_MaintenanceProtocolAssignments_Scope
            CHECK (AssignmentScope IN ('APPLIANCE_TYPE', 'CUSTOMER_CATEGORY'))
    );

    CREATE INDEX IX_MaintenanceProtocolAssignments_Resolve
        ON dbo.MaintenanceProtocolAssignments(IsActive, Precedence, ScopeCode);
END;
GO

IF OBJECT_ID('dbo.MaintenanceExpectedLifeRules', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.MaintenanceExpectedLifeRules (
        ExpectedLifeRuleId INT IDENTITY(1,1) NOT NULL
            CONSTRAINT PK_MaintenanceExpectedLifeRules PRIMARY KEY,
        TemplateCode NVARCHAR(50) NOT NULL,
        TierCode NVARCHAR(20) NOT NULL,
        ExpectedYears DECIMAL(5,1) NOT NULL,
        IsActive BIT NOT NULL
            CONSTRAINT DF_MaintenanceExpectedLifeRules_Active DEFAULT (1),
        CreatedAt DATETIME2 NOT NULL
            CONSTRAINT DF_MaintenanceExpectedLifeRules_CreatedAt DEFAULT SYSUTCDATETIME(),
        UpdatedAt DATETIME2 NOT NULL
            CONSTRAINT DF_MaintenanceExpectedLifeRules_UpdatedAt DEFAULT SYSUTCDATETIME(),
        CONSTRAINT UQ_MaintenanceExpectedLifeRules_Key
            UNIQUE (TemplateCode, TierCode)
    );
END;
GO

IF OBJECT_ID('dbo.MaintenanceLifecycleStages', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.MaintenanceLifecycleStages (
        LifecycleStageId INT IDENTITY(1,1) NOT NULL
            CONSTRAINT PK_MaintenanceLifecycleStages PRIMARY KEY,
        StageLabel NVARCHAR(50) NOT NULL
            CONSTRAINT UQ_MaintenanceLifecycleStages_Label UNIQUE,
        MaxAgeRatio DECIMAL(6,3) NOT NULL,
        SortOrder INT NULL,
        IsActive BIT NOT NULL
            CONSTRAINT DF_MaintenanceLifecycleStages_Active DEFAULT (1),
        CreatedAt DATETIME2 NOT NULL
            CONSTRAINT DF_MaintenanceLifecycleStages_CreatedAt DEFAULT SYSUTCDATETIME(),
        UpdatedAt DATETIME2 NOT NULL
            CONSTRAINT DF_MaintenanceLifecycleStages_UpdatedAt DEFAULT SYSUTCDATETIME()
    );
END;
GO

/* -------------------------------------------------------------------------
   7.3  Raw technician inspection data

   The field layer is the record of what the technician actually entered. It is
   append-and-correct, never overwritten by report generation: health reports
   are derived from it, so a report can be regenerated or revised without
   losing the underlying field facts (MERGE_GUIDE 7.3, 23).
   ------------------------------------------------------------------------- */
IF OBJECT_ID('dbo.MaintenanceFieldInspections', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.MaintenanceFieldInspections (
        FieldInspectionId INT IDENTITY(1,1) NOT NULL
            CONSTRAINT PK_MaintenanceFieldInspections PRIMARY KEY,
        VisitId INT NOT NULL,
        VisitAssetId INT NULL,
        HouseholdId INT NOT NULL,
        AssetId INT NOT NULL,

        /* Protocol version in force on the service date (MERGE_GUIDE 7.7). */
        ProtocolTemplateId INT NULL,
        ProtocolTemplateCodeSnapshot NVARCHAR(50) NULL,
        ProtocolTemplateVersionSnapshot INT NULL,

        /* Identity: the internal user id is authoritative, the name is a snapshot. */
        TechnicianUserId NVARCHAR(100) NULL,
        TechnicianDisplayNameSnapshot NVARCHAR(150) NULL,

        InspectionStatus NVARCHAR(40) NOT NULL
            CONSTRAINT DF_MaintenanceFieldInspections_Status DEFAULT ('NOT_STARTED'),
        StartedAt DATETIME2 NULL,
        CompletedAt DATETIME2 NULL,

        /* Lifecycle context captured in the field. */
        ApproxAgeYears DECIMAL(5,1) NULL,
        LifecycleTierCode NVARCHAR(20) NULL,
        ExpectedLifeYears DECIMAL(5,1) NULL,
        LifecycleStage NVARCHAR(50) NULL,

        /* Scoring. 75% condition / 25% lifecycle -- see reportScoring in plan-config.js. */
        ConditionScore DECIMAL(6,2) NULL,
        LifecycleScore DECIMAL(6,2) NULL,
        FinalHealthScore DECIMAL(6,2) NULL,
        GradeLabel NVARCHAR(10) NULL,

        SerialTagPhotoStorageKey NVARCHAR(500) NULL,
        TechnicianSummary NVARCHAR(MAX) NULL,
        FollowUpRequired BIT NOT NULL
            CONSTRAINT DF_MaintenanceFieldInspections_FollowUp DEFAULT (0),

        CreatedAt DATETIME2 NOT NULL
            CONSTRAINT DF_MaintenanceFieldInspections_CreatedAt DEFAULT SYSUTCDATETIME(),
        UpdatedAt DATETIME2 NOT NULL
            CONSTRAINT DF_MaintenanceFieldInspections_UpdatedAt DEFAULT SYSUTCDATETIME(),
        VersionStamp ROWVERSION,

        CONSTRAINT FK_MaintenanceFieldInspections_Visits
            FOREIGN KEY (VisitId) REFERENCES dbo.MaintenanceVisits(VisitId),
        CONSTRAINT FK_MaintenanceFieldInspections_VisitAssets
            FOREIGN KEY (VisitAssetId) REFERENCES dbo.MaintenanceVisitAssets(VisitAssetId),
        CONSTRAINT FK_MaintenanceFieldInspections_Households
            FOREIGN KEY (HouseholdId) REFERENCES dbo.MaintenanceHouseholds(HouseholdId),
        CONSTRAINT FK_MaintenanceFieldInspections_Assets
            FOREIGN KEY (AssetId) REFERENCES dbo.MaintenanceAssets(AssetId),
        CONSTRAINT FK_MaintenanceFieldInspections_Templates
            FOREIGN KEY (ProtocolTemplateId)
            REFERENCES dbo.MaintenanceProtocolTemplates(ProtocolTemplateId),

        /* MERGE_GUIDE 7.3 status vocabulary. */
        CONSTRAINT CK_MaintenanceFieldInspections_Status
            CHECK (InspectionStatus IN (
                'NOT_STARTED', 'IN_PROGRESS', 'FIELD_COMPLETE', 'REPORT_GENERATED'
            )),
        CONSTRAINT CK_MaintenanceFieldInspections_Score
            CHECK (FinalHealthScore IS NULL OR FinalHealthScore BETWEEN 0 AND 100),

        /* One live inspection per asset per visit. */
        CONSTRAINT UQ_MaintenanceFieldInspections_VisitAsset
            UNIQUE (VisitId, AssetId)
    );

    CREATE INDEX IX_MaintenanceFieldInspections_Visit
        ON dbo.MaintenanceFieldInspections(VisitId, InspectionStatus);

    CREATE INDEX IX_MaintenanceFieldInspections_Asset
        ON dbo.MaintenanceFieldInspections(AssetId, CompletedAt DESC);

    CREATE INDEX IX_MaintenanceFieldInspections_Technician
        ON dbo.MaintenanceFieldInspections(TechnicianUserId, CompletedAt DESC);
END;
GO

IF OBJECT_ID('dbo.MaintenanceFieldInspectionChecks', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.MaintenanceFieldInspectionChecks (
        FieldInspectionCheckId INT IDENTITY(1,1) NOT NULL
            CONSTRAINT PK_MaintenanceFieldInspectionChecks PRIMARY KEY,
        FieldInspectionId INT NOT NULL,
        CheckpointCode NVARCHAR(50) NOT NULL,

        /* Wording as shown to the technician on the service date. Never a live
           join to MaintenanceProtocolCheckpoints -- protocol text changes. */
        CheckpointLabelSnapshot NVARCHAR(300) NULL,

        Performed BIT NOT NULL
            CONSTRAINT DF_MaintenanceFieldInspectionChecks_Performed DEFAULT (0),
        Rating TINYINT NULL,
        StatusLabel NVARCHAR(20) NULL,
        ObservedValue NVARCHAR(150) NULL,
        ObservedUnit NVARCHAR(30) NULL,
        TargetText NVARCHAR(300) NULL,
        ReadingJson NVARCHAR(MAX) NULL,
        TechnicianNote NVARCHAR(MAX) NULL,
        PhotoCount INT NOT NULL
            CONSTRAINT DF_MaintenanceFieldInspectionChecks_PhotoCount DEFAULT (0),
        SortOrder INT NULL,
        CompletedAt DATETIME2 NULL,
        CreatedAt DATETIME2 NOT NULL
            CONSTRAINT DF_MaintenanceFieldInspectionChecks_CreatedAt DEFAULT SYSUTCDATETIME(),
        UpdatedAt DATETIME2 NOT NULL
            CONSTRAINT DF_MaintenanceFieldInspectionChecks_UpdatedAt DEFAULT SYSUTCDATETIME(),

        CONSTRAINT FK_MaintenanceFieldInspectionChecks_Inspections
            FOREIGN KEY (FieldInspectionId)
            REFERENCES dbo.MaintenanceFieldInspections(FieldInspectionId),

        /* Five tap buttons in the field tool, not a slider. */
        CONSTRAINT CK_MaintenanceFieldInspectionChecks_Rating
            CHECK (Rating IS NULL OR Rating BETWEEN 1 AND 5),
        CONSTRAINT CK_MaintenanceFieldInspectionChecks_Status
            CHECK (StatusLabel IS NULL OR StatusLabel IN ('PASS', 'MONITOR', 'ACTION')),
        CONSTRAINT UQ_MaintenanceFieldInspectionChecks_Code
            UNIQUE (FieldInspectionId, CheckpointCode)
    );

    CREATE INDEX IX_MaintenanceFieldInspectionChecks_Inspection
        ON dbo.MaintenanceFieldInspectionChecks(FieldInspectionId, SortOrder);
END;
GO

IF OBJECT_ID('dbo.MaintenanceFieldInspectionPhotos', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.MaintenanceFieldInspectionPhotos (
        FieldInspectionPhotoId INT IDENTITY(1,1) NOT NULL
            CONSTRAINT PK_MaintenanceFieldInspectionPhotos PRIMARY KEY,
        FieldInspectionId INT NOT NULL,
        FieldInspectionCheckId INT NULL,
        PhotoKind NVARCHAR(30) NOT NULL
            CONSTRAINT DF_MaintenanceFieldInspectionPhotos_Kind DEFAULT ('CHECKPOINT'),
        StorageKey NVARCHAR(500) NOT NULL,
        ContentType NVARCHAR(100) NULL,
        ByteSize BIGINT NULL,
        Caption NVARCHAR(300) NULL,
        CapturedAt DATETIME2 NULL,
        IncludeInReport BIT NOT NULL
            CONSTRAINT DF_MaintenanceFieldInspectionPhotos_Include DEFAULT (1),
        SortOrder INT NULL,
        CreatedAt DATETIME2 NOT NULL
            CONSTRAINT DF_MaintenanceFieldInspectionPhotos_CreatedAt DEFAULT SYSUTCDATETIME(),

        CONSTRAINT FK_MaintenanceFieldInspectionPhotos_Inspections
            FOREIGN KEY (FieldInspectionId)
            REFERENCES dbo.MaintenanceFieldInspections(FieldInspectionId),
        CONSTRAINT FK_MaintenanceFieldInspectionPhotos_Checks
            FOREIGN KEY (FieldInspectionCheckId)
            REFERENCES dbo.MaintenanceFieldInspectionChecks(FieldInspectionCheckId),
        CONSTRAINT CK_MaintenanceFieldInspectionPhotos_Kind
            CHECK (PhotoKind IN ('SERIAL_TAG', 'CHECKPOINT', 'BEFORE', 'AFTER', 'OTHER'))
    );

    CREATE INDEX IX_MaintenanceFieldInspectionPhotos_Inspection
        ON dbo.MaintenanceFieldInspectionPhotos(FieldInspectionId, SortOrder);
END;
GO

/* Link a generated report back to the field inspection it came from. Nullable:
   pre-v0.7 reports were built in the office and have no field inspection. */
IF COL_LENGTH('dbo.MaintenanceHealthReports', 'FieldInspectionId') IS NULL
    ALTER TABLE dbo.MaintenanceHealthReports ADD FieldInspectionId INT NULL;
GO
IF OBJECT_ID('dbo.FK_MaintenanceHealthReports_FieldInspections', 'F') IS NULL
    ALTER TABLE dbo.MaintenanceHealthReports
        ADD CONSTRAINT FK_MaintenanceHealthReports_FieldInspections
        FOREIGN KEY (FieldInspectionId)
        REFERENCES dbo.MaintenanceFieldInspections(FieldInspectionId);
GO

/* -------------------------------------------------------------------------
   7.4  Report delivery tracking

   Append-only per send attempt, so resend history survives (MERGE_GUIDE 7.4).
   ------------------------------------------------------------------------- */
IF OBJECT_ID('dbo.MaintenanceReportDeliveries', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.MaintenanceReportDeliveries (
        ReportDeliveryId INT IDENTITY(1,1) NOT NULL
            CONSTRAINT PK_MaintenanceReportDeliveries PRIMARY KEY,
        HealthReportId INT NOT NULL,
        HouseholdId INT NOT NULL,
        RecipientEmail NVARCHAR(255) NOT NULL,
        RecipientName NVARCHAR(150) NULL,
        DeliveryStatus NVARCHAR(30) NOT NULL
            CONSTRAINT DF_MaintenanceReportDeliveries_Status DEFAULT ('READY'),
        ProviderName NVARCHAR(50) NULL,
        ProviderMessageId NVARCHAR(200) NULL,
        QueuedAt DATETIME2 NULL,
        SentAt DATETIME2 NULL,
        FailedAt DATETIME2 NULL,
        FailureReason NVARCHAR(1000) NULL,
        AttemptCount INT NOT NULL
            CONSTRAINT DF_MaintenanceReportDeliveries_Attempts DEFAULT (0),
        ReportRevisionNumber INT NULL,
        CreatedByUserId NVARCHAR(100) NULL,
        CreatedAt DATETIME2 NOT NULL
            CONSTRAINT DF_MaintenanceReportDeliveries_CreatedAt DEFAULT SYSUTCDATETIME(),
        UpdatedAt DATETIME2 NOT NULL
            CONSTRAINT DF_MaintenanceReportDeliveries_UpdatedAt DEFAULT SYSUTCDATETIME(),
        VersionStamp ROWVERSION,

        CONSTRAINT FK_MaintenanceReportDeliveries_Reports
            FOREIGN KEY (HealthReportId)
            REFERENCES dbo.MaintenanceHealthReports(HealthReportId),
        CONSTRAINT FK_MaintenanceReportDeliveries_Households
            FOREIGN KEY (HouseholdId) REFERENCES dbo.MaintenanceHouseholds(HouseholdId),
        CONSTRAINT CK_MaintenanceReportDeliveries_Status
            CHECK (DeliveryStatus IN ('READY', 'QUEUED', 'SENT', 'FAILED'))
    );

    CREATE INDEX IX_MaintenanceReportDeliveries_Report
        ON dbo.MaintenanceReportDeliveries(HealthReportId, CreatedAt DESC);

    CREATE INDEX IX_MaintenanceReportDeliveries_Queue
        ON dbo.MaintenanceReportDeliveries(DeliveryStatus, QueuedAt);
END;
GO

/* -------------------------------------------------------------------------
   7.5  Technician assignment / authenticated user

   Display names are snapshots for historical reporting; the internal user id is
   the authoritative identity (MERGE_GUIDE 7.5, 12).
   ------------------------------------------------------------------------- */
IF COL_LENGTH('dbo.MaintenanceVisits', 'AssignedTechnicianUserId') IS NULL
    ALTER TABLE dbo.MaintenanceVisits ADD AssignedTechnicianUserId NVARCHAR(100) NULL;
GO
IF COL_LENGTH('dbo.MaintenanceVisits', 'AssignedTechnicianNameSnapshot') IS NULL
    ALTER TABLE dbo.MaintenanceVisits ADD AssignedTechnicianNameSnapshot NVARCHAR(150) NULL;
GO
IF COL_LENGTH('dbo.MaintenanceVisits', 'StartedByUserId') IS NULL
    ALTER TABLE dbo.MaintenanceVisits ADD StartedByUserId NVARCHAR(100) NULL;
GO
IF COL_LENGTH('dbo.MaintenanceVisits', 'CompletedByUserId') IS NULL
    ALTER TABLE dbo.MaintenanceVisits ADD CompletedByUserId NVARCHAR(100) NULL;
GO
IF COL_LENGTH('dbo.MaintenanceVisits', 'FieldStartedAt') IS NULL
    ALTER TABLE dbo.MaintenanceVisits ADD FieldStartedAt DATETIME2 NULL;
GO
IF NOT EXISTS (
    SELECT 1 FROM sys.indexes
    WHERE name = 'IX_MaintenanceVisits_Technician'
      AND object_id = OBJECT_ID('dbo.MaintenanceVisits')
)
    CREATE INDEX IX_MaintenanceVisits_Technician
        ON dbo.MaintenanceVisits(AssignedTechnicianUserId, DueDate);
GO

/* -------------------------------------------------------------------------
   7.8  Filter service pricing  (beyond MERGE_GUIDE section 7)

   Filter service is now a PRICED selection rather than a flag: choosing it on
   an individual refrigeration or icemaker asset raises the annual plan price by
   Wilson's sales price for that asset's filters. Estate Concierge includes
   filters outright, so the same selection costs nothing there.

   Water and air / food-preservation filters are separate customer choices --
   air is common on Sub-Zero and similar premium refrigeration and is never
   selected by default.

   PLACEHOLDER PRICING. The seeded unit prices mirror the $70 placeholder in
   assets/plan-config.js and are NOT approved numbers. When Wilson's filter
   sales-price list is loaded, add rows keyed by PartNumber (leaving the
   kind-level rows as the fallback) and set PriceIsPlaceholder = 0. Pricing
   should be resolved server-side from this table rather than from browser JS
   (context section 34 item 11).
   ------------------------------------------------------------------------- */
IF OBJECT_ID('dbo.MaintenanceFilterPrices', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.MaintenanceFilterPrices (
        FilterPriceId INT IDENTITY(1,1) NOT NULL
            CONSTRAINT PK_MaintenanceFilterPrices PRIMARY KEY,
        FilterKindCode NVARCHAR(20) NOT NULL,
        /* NULL PartNumber = the kind-level fallback price. */
        PartNumber NVARCHAR(100) NULL,
        FilterDescription NVARCHAR(300) NULL,
        UnitSalesPrice DECIMAL(12,2) NOT NULL,
        DefaultQuantity INT NOT NULL
            CONSTRAINT DF_MaintenanceFilterPrices_Quantity DEFAULT (1),
        PriceIsPlaceholder BIT NOT NULL
            CONSTRAINT DF_MaintenanceFilterPrices_Placeholder DEFAULT (1),
        EffectiveFrom DATE NULL,
        EffectiveTo DATE NULL,
        IsActive BIT NOT NULL
            CONSTRAINT DF_MaintenanceFilterPrices_Active DEFAULT (1),
        CreatedAt DATETIME2 NOT NULL
            CONSTRAINT DF_MaintenanceFilterPrices_CreatedAt DEFAULT SYSUTCDATETIME(),
        UpdatedAt DATETIME2 NOT NULL
            CONSTRAINT DF_MaintenanceFilterPrices_UpdatedAt DEFAULT SYSUTCDATETIME(),
        CONSTRAINT CK_MaintenanceFilterPrices_Kind
            CHECK (FilterKindCode IN ('water', 'air')),
        CONSTRAINT CK_MaintenanceFilterPrices_Price
            CHECK (UnitSalesPrice >= 0)
    );

    /* One fallback row per kind; part-number rows are added alongside. */
    CREATE UNIQUE INDEX UX_MaintenanceFilterPrices_KindFallback
        ON dbo.MaintenanceFilterPrices(FilterKindCode)
        WHERE PartNumber IS NULL;

    CREATE UNIQUE INDEX UX_MaintenanceFilterPrices_Part
        ON dbo.MaintenanceFilterPrices(FilterKindCode, PartNumber)
        WHERE PartNumber IS NOT NULL;
END;
GO

/* Per-asset filter selections. Water and air are independent opt-ins, each with
   its own quantity, so the annual price can be recomputed server-side. */
IF COL_LENGTH('dbo.MaintenanceAssets', 'WaterFilterServiceOptIn') IS NULL
    ALTER TABLE dbo.MaintenanceAssets ADD WaterFilterServiceOptIn BIT NOT NULL
        CONSTRAINT DF_MaintenanceAssets_WaterFilterOptIn DEFAULT (0);
GO
IF COL_LENGTH('dbo.MaintenanceAssets', 'AirFilterServiceOptIn') IS NULL
    ALTER TABLE dbo.MaintenanceAssets ADD AirFilterServiceOptIn BIT NOT NULL
        CONSTRAINT DF_MaintenanceAssets_AirFilterOptIn DEFAULT (0);
GO
IF COL_LENGTH('dbo.MaintenanceAssets', 'WaterFilterQuantity') IS NULL
    ALTER TABLE dbo.MaintenanceAssets ADD WaterFilterQuantity INT NULL;
GO
IF COL_LENGTH('dbo.MaintenanceAssets', 'AirFilterQuantity') IS NULL
    ALTER TABLE dbo.MaintenanceAssets ADD AirFilterQuantity INT NULL;
GO

/* Annual filter-service amount priced into the subscription, kept alongside the
   plan amount so the breakdown survives a price-list change. */
IF COL_LENGTH('dbo.MaintenanceSubscriptions', 'FilterServiceAnnualAmount') IS NULL
    ALTER TABLE dbo.MaintenanceSubscriptions ADD FilterServiceAnnualAmount DECIMAL(12,2) NOT NULL
        CONSTRAINT DF_MaintenanceSubscriptions_FilterAmount DEFAULT (0);
GO
IF COL_LENGTH('dbo.MaintenanceSubscriptions', 'FilterServiceDetailJson') IS NULL
    ALTER TABLE dbo.MaintenanceSubscriptions ADD FilterServiceDetailJson NVARCHAR(MAX) NULL;
GO

-- {{SEEDS}}
-- {{FILTER_PRICE_SEED}}

/* -------------------------------------------------------------------------
   New operational views

   Additive only. The base script's three views are left untouched so that
   re-running sql/maintenance_schema.sql cannot revert anything defined here.
   ------------------------------------------------------------------------- */

/*
   Payment readiness. MERGE_GUIDE 7.2: an AR household is payment-ready even
   with no Stripe payment method, so readiness must never be inferred from a
   missing card.
*/
CREATE OR ALTER VIEW dbo.vw_MaintenanceHouseholdPaymentReadiness
AS
SELECT
    h.HouseholdId,
    h.HouseholdReference,
    h.DisplayName AS HouseholdName,
    h.BillingMethodCode,
    h.AccountTerms,
    h.ARStatus,
    h.ExternalARCustomerId,
    pp.PaymentProfileId,
    pp.PaymentProfileStatus,
    pp.CardBrand,
    pp.CardLast4,
    CAST(
        CASE
            WHEN h.BillingMethodCode = 'AR_ACCOUNT'
                 AND ISNULL(h.ARStatus, 'Review') = 'Active' THEN 1
            WHEN h.BillingMethodCode = 'CARD_ON_FILE'
                 AND pp.PaymentProfileId IS NOT NULL
                 AND pp.PaymentProfileStatus = 'Active' THEN 1
            ELSE 0
        END AS BIT
    ) AS PaymentReady,
    CASE
        WHEN h.BillingMethodCode = 'AR_ACCOUNT'
             AND ISNULL(h.ARStatus, 'Review') = 'Active' THEN 'AR_APPROVED'
        WHEN h.BillingMethodCode = 'AR_ACCOUNT' THEN 'ACTION_REQUIRED'
        WHEN pp.PaymentProfileId IS NULL THEN 'ACTION_REQUIRED'
        WHEN pp.PaymentProfileStatus <> 'Active' THEN 'ACTION_REQUIRED'
        ELSE 'READY_TO_CHARGE'
    END AS PaymentReadinessCode
FROM dbo.MaintenanceHouseholds h
OUTER APPLY (
    SELECT TOP (1)
        p.PaymentProfileId, p.PaymentProfileStatus, p.CardBrand, p.CardLast4
    FROM dbo.MaintenancePaymentProfiles p
    WHERE p.HouseholdId = h.HouseholdId
    ORDER BY
        CASE WHEN p.PaymentProfileStatus = 'Active' THEN 0 ELSE 1 END,
        p.PaymentProfileId DESC
) pp;
GO

/*
   Field progress per visit. Drives the Command Center's view of what the
   technician has finished and whether the report package is ready
   (MERGE_GUIDE 23).
*/
CREATE OR ALTER VIEW dbo.vw_MaintenanceFieldProgress
AS
SELECT
    v.VisitId,
    v.HouseholdId,
    h.DisplayName AS HouseholdName,
    v.DueDate,
    v.VisitStatus,
    v.AssignedTechnicianUserId,
    v.AssignedTechnicianNameSnapshot,
    v.FieldStartedAt,
    v.CompletedAt,
    COUNT(va.VisitAssetId) AS ScopedAssetCount,
    SUM(CASE WHEN fi.InspectionStatus IN ('FIELD_COMPLETE', 'REPORT_GENERATED')
             THEN 1 ELSE 0 END) AS CompletedAssetCount,
    SUM(CASE WHEN fi.InspectionStatus = 'IN_PROGRESS' THEN 1 ELSE 0 END)
        AS InProgressAssetCount,
    SUM(CASE WHEN fi.FieldInspectionId IS NULL
                   OR fi.InspectionStatus = 'NOT_STARTED'
             THEN 1 ELSE 0 END) AS NotStartedAssetCount,
    SUM(CASE WHEN fi.FollowUpRequired = 1 THEN 1 ELSE 0 END) AS FollowUpCount,
    CAST(
        CASE WHEN COUNT(va.VisitAssetId) > 0
              AND COUNT(va.VisitAssetId) = SUM(
                    CASE WHEN fi.InspectionStatus IN ('FIELD_COMPLETE', 'REPORT_GENERATED')
                         THEN 1 ELSE 0 END)
             THEN 1 ELSE 0 END AS BIT
    ) AS AllAssetsFieldComplete,
    AVG(CAST(fi.FinalHealthScore AS DECIMAL(6,2))) AS AverageHealthScore
FROM dbo.MaintenanceVisits v
INNER JOIN dbo.MaintenanceHouseholds h
    ON h.HouseholdId = v.HouseholdId
LEFT JOIN dbo.MaintenanceVisitAssets va
    ON va.VisitId = v.VisitId
LEFT JOIN dbo.MaintenanceFieldInspections fi
    ON fi.VisitId = va.VisitId
   AND fi.AssetId = va.AssetId
GROUP BY
    v.VisitId, v.HouseholdId, h.DisplayName, v.DueDate, v.VisitStatus,
    v.AssignedTechnicianUserId, v.AssignedTechnicianNameSnapshot,
    v.FieldStartedAt, v.CompletedAt;
GO

/*
   Resolved protocol per asset. The SQL counterpart of
   WILSON_PROTOCOL.resolveCheckpointSet(), including the IMUC override.
   Compare against MaintenanceAssets.CheckpointSetCode to find assets still
   carrying a stale snapshot.
*/
CREATE OR ALTER VIEW dbo.vw_MaintenanceAssetProtocol
AS
SELECT
    resolution.AssetId,
    resolution.HouseholdId,
    resolution.AssetCategory,
    resolution.AssetTypeCode,
    resolution.AssetTypeName,
    resolution.CustomerCategoryCode,
    resolution.StoredCheckpointSetCode,
    resolution.ResolvedTemplateCode,
    CAST(CASE WHEN resolution.StoredCheckpointSetCode IS NOT NULL
                   AND resolution.StoredCheckpointSetCode <> resolution.ResolvedTemplateCode
              THEN 1 ELSE 0 END AS BIT) AS StoredValueIsStale
FROM (
    /* Non-IMUC: assignment by precedence, then the stored snapshot only if it
       names a real template, then generic. The snapshot ranks BELOW config and
       above generic -- identical to step 4 of resolveCheckpointSet(). */
    SELECT
        a.AssetId,
        a.HouseholdId,
        a.AssetCategory,
        a.AssetTypeCode,
        a.AssetTypeName,
        a.CustomerCategoryCode,
        a.CheckpointSetCode AS StoredCheckpointSetCode,
        COALESCE(resolved.TemplateCode, snapshot.TemplateCode, 'generic')
            AS ResolvedTemplateCode
    FROM dbo.MaintenanceAssets a
    OUTER APPLY (
        SELECT TOP (1) pa.TemplateCode
        FROM dbo.MaintenanceProtocolAssignments pa
        WHERE pa.IsActive = 1
          AND (
                (pa.AssignmentScope = 'APPLIANCE_TYPE' AND pa.ScopeCode = a.AssetTypeCode)
             OR (pa.AssignmentScope = 'CUSTOMER_CATEGORY' AND pa.ScopeCode = a.CustomerCategoryCode)
          )
        ORDER BY pa.Precedence, pa.ProtocolAssignmentId
    ) resolved
    OUTER APPLY (
        SELECT TOP (1) t.TemplateCode
        FROM dbo.MaintenanceProtocolTemplates t
        WHERE t.TemplateCode = a.CheckpointSetCode
          AND t.IsActive = 1
        ORDER BY t.TemplateVersion DESC
    ) snapshot
    WHERE a.AssetCategory NOT IN ('imuc', 'hvac')

    UNION ALL

    /* HVAC resolves by SYSTEM TYPE, never by an appliance-type assignment.
       This arm was missing, and its absence was invisible: with no HVAC assets
       in the demo data and no HVAC case in the parity test, the view happily
       resolved an HVAC asset to whatever appliance template its type code
       happened to match. The JS resolver (WILSON_PROTOCOL.resolveCheckpointSet)
       branches on group === 'hvac' first, in this order, and falls through to
       'generic' on purpose: an unrecognised system should be visible as a gap
       rather than quietly get three subjective ratings. */
    SELECT
        a.AssetId,
        a.HouseholdId,
        a.AssetCategory,
        a.AssetTypeCode,
        a.AssetTypeName,
        a.CustomerCategoryCode,
        a.CheckpointSetCode AS StoredCheckpointSetCode,
        CASE
            WHEN systype.SystemType LIKE '%heat pump%'
              OR systype.SystemType LIKE '%heatpump%'      THEN 'hvac_heatpump'
            WHEN systype.SystemType LIKE '%mini split%'
              OR systype.SystemType LIKE '%mini-split%'
              OR systype.SystemType LIKE '%minisplit%'
              OR systype.SystemType LIKE '%ductless%'      THEN 'hvac_minisplit'
            WHEN systype.SystemType LIKE '%furnace%'
              OR systype.SystemType LIKE '%gas heat%'      THEN 'hvac_furnace'
            WHEN systype.SystemType LIKE '%split%'
              OR systype.SystemType LIKE '%package%'
              OR systype.SystemType LIKE '%air handler%'
              OR systype.SystemType LIKE '%condenser%'     THEN 'hvac_cooling'
            ELSE 'generic'
        END AS ResolvedTemplateCode
    FROM dbo.MaintenanceAssets a
    CROSS APPLY (
        SELECT LOWER(COALESCE(NULLIF(a.AssetTypeCode, N''),
                              NULLIF(a.AssetTypeName, N''),
                              a.CustomerCategoryCode, N'')) AS SystemType
    ) systype
    WHERE a.AssetCategory = 'hvac'

    UNION ALL

    /* IMUC group membership always wins, before any assignment lookup. */
    SELECT
        a.AssetId,
        a.HouseholdId,
        a.AssetCategory,
        a.AssetTypeCode,
        a.AssetTypeName,
        a.CustomerCategoryCode,
        a.CheckpointSetCode AS StoredCheckpointSetCode,
        'icemaker' AS ResolvedTemplateCode
    FROM dbo.MaintenanceAssets a
    WHERE a.AssetCategory = 'imuc'
) resolution;
GO

/* -------------------------------------------------------------------------
   7.9  Age provenance and photographic evidence  (added v0.9.12)

   TWO GAPS THAT WERE THE SAME GAP: the prototype recorded a fact without
   recording whether the fact was evidence.

   AGE. Lifecycle age carries 25% of every health score
   (MaintenanceLifecycleWeights). Nothing populated an install date, so the
   technician typed a number from memory or from what the customer recalled,
   and the score treated that identically to a dated invoice. Wilson SOLD most
   of this equipment, so the date usually exists on an invoice -- these columns
   are where it lands, with the source that produced it. An asset with no
   install date must score on measured condition alone; the application drops
   the age term rather than substituting a default, and MaintenanceAssets
   .InstallYear stays NULL rather than 0.

   PHOTOS. MaintenanceFieldInspectionPhotos already existed with a StorageKey,
   but the field tool never produced one: it set a boolean, discarded the image,
   and the report printed a count with nothing behind it. Photographs are now
   captured to device storage with a local id, so the upload path needs to
   reconcile a device-side capture with the blob it eventually becomes --
   LocalCaptureId and UploadedAt are that reconciliation.
   ------------------------------------------------------------------------- */

/* The vocabulary, seeded from plan-config.js so the application and the
   database cannot disagree about what "documented" means. IsDocumented is the
   honesty flag: 0 means the figure is somebody's recollection. */
IF OBJECT_ID('dbo.MaintenanceAgeSources', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.MaintenanceAgeSources (
        /* Surrogate key plus a UNIQUE natural code, matching every other
           configuration table here: the code is what the application and the
           FK reference, the id is what survives a code being renamed. */
        AgeSourceId INT IDENTITY(1,1) NOT NULL
            CONSTRAINT PK_MaintenanceAgeSources PRIMARY KEY,
        AgeSourceCode NVARCHAR(30) NOT NULL
            CONSTRAINT UQ_MaintenanceAgeSources_Code UNIQUE,
        DisplayName NVARCHAR(100) NOT NULL,
        ShortName NVARCHAR(50) NULL,
        IsDocumented BIT NOT NULL
            CONSTRAINT DF_MaintenanceAgeSources_Documented DEFAULT (0),
        SortOrder INT NULL,
        CustomerNote NVARCHAR(400) NULL,
        IsActive BIT NOT NULL
            CONSTRAINT DF_MaintenanceAgeSources_Active DEFAULT (1)
    );
END;
GO

IF COL_LENGTH('dbo.MaintenanceAssets', 'InstallYear') IS NULL
    ALTER TABLE dbo.MaintenanceAssets ADD InstallYear SMALLINT NULL;
GO

/* The date as printed on the source document, kept alongside the year so a
   dispute can be settled against the paperwork rather than re-derived. */
IF COL_LENGTH('dbo.MaintenanceAssets', 'InstallDate') IS NULL
    ALTER TABLE dbo.MaintenanceAssets ADD InstallDate DATE NULL;
GO

IF COL_LENGTH('dbo.MaintenanceAssets', 'AgeSourceCode') IS NULL
    ALTER TABLE dbo.MaintenanceAssets ADD AgeSourceCode NVARCHAR(30) NULL;
GO

/* The invoice number, work order, or other document the date came off. */
IF COL_LENGTH('dbo.MaintenanceAssets', 'AgeSourceReference') IS NULL
    ALTER TABLE dbo.MaintenanceAssets ADD AgeSourceReference NVARCHAR(60) NULL;
GO

IF OBJECT_ID('dbo.FK_MaintenanceAssets_AgeSources', 'F') IS NULL
    ALTER TABLE dbo.MaintenanceAssets ADD CONSTRAINT FK_MaintenanceAssets_AgeSources
        FOREIGN KEY (AgeSourceCode) REFERENCES dbo.MaintenanceAgeSources(AgeSourceCode);
GO

/* What the technician claimed at the visit, which is not always what the asset
   record says: a tech who overrides an invoice-derived age owns that number,
   and the report has to be able to say so. */
IF COL_LENGTH('dbo.MaintenanceFieldInspections', 'AgeSourceCode') IS NULL
    ALTER TABLE dbo.MaintenanceFieldInspections ADD AgeSourceCode NVARCHAR(30) NULL;
GO

/* An explicit "cannot be established". Completion used to require a numeric
   age, so the gate itself demanded a guess on any undated appliance. */
IF COL_LENGTH('dbo.MaintenanceFieldInspections', 'AgeNotEstablished') IS NULL
    ALTER TABLE dbo.MaintenanceFieldInspections ADD AgeNotEstablished BIT NOT NULL
        CONSTRAINT DF_MaintenanceFieldInspections_AgeNotEstablished DEFAULT (0);
GO

/* The device-side id of the captured image, so an upload can be matched to the
   capture it came from and retried idempotently. */
IF COL_LENGTH('dbo.MaintenanceFieldInspectionPhotos', 'LocalCaptureId') IS NULL
    ALTER TABLE dbo.MaintenanceFieldInspectionPhotos ADD LocalCaptureId NVARCHAR(60) NULL;
GO

IF COL_LENGTH('dbo.MaintenanceFieldInspectionPhotos', 'UploadedAt') IS NULL
    ALTER TABLE dbo.MaintenanceFieldInspectionPhotos ADD UploadedAt DATETIME2 NULL;
GO

/* Pixel dimensions of what was stored, so a viewer can lay out without
   fetching the blob first. */
IF COL_LENGTH('dbo.MaintenanceFieldInspectionPhotos', 'PixelWidth') IS NULL
    ALTER TABLE dbo.MaintenanceFieldInspectionPhotos ADD PixelWidth INT NULL;
GO

IF COL_LENGTH('dbo.MaintenanceFieldInspectionPhotos', 'PixelHeight') IS NULL
    ALTER TABLE dbo.MaintenanceFieldInspectionPhotos ADD PixelHeight INT NULL;
GO

IF NOT EXISTS (
    SELECT 1 FROM sys.indexes
    WHERE name = 'UX_MaintenanceFieldInspectionPhotos_LocalCapture'
      AND object_id = OBJECT_ID('dbo.MaintenanceFieldInspectionPhotos')
)
    /* Filtered unique index: a retried upload of the same device capture must
       not create a second row, but rows predating this column have none. */
    CREATE UNIQUE INDEX UX_MaintenanceFieldInspectionPhotos_LocalCapture
        ON dbo.MaintenanceFieldInspectionPhotos(LocalCaptureId)
        WHERE LocalCaptureId IS NOT NULL;
GO

{{AGE_SOURCE_SEED}}

/* -------------------------------------------------------------------------
   7.10  Water hardness as a lifecycle modifier  (added v0.9.21)

   A property-level fact, not an appliance-level one. One hardness strip is run
   per residence per visit, and the reading changes how long the equipment that
   RUNS WATER is expected to last -- never what the technician measured today,
   and never anything on a dryer or a range.

   THE READING IS THE ONLY INPUT. A technician types the number off the strip;
   nobody selects a band and nobody selects a multiplier. The factor is computed
   from the number by piecewise-linear interpolation between the anchors in
   MaintenanceWaterLifeFactorAnchors, and vw_MaintenanceHouseholdWaterLatest
   below does that interpolation with the same anchors and the same clamps as
   WILSON_WATER.lifeFactorForGpg() in plan-config.js.

   There is no softener table. An earlier draft of this section had one, and it
   was double-counting: the strip is read at a tap, downstream of whatever
   equipment the house has, so a working softener already shows up as a soft
   reading. Recording it separately asked the same question twice and then
   needed a rule for what to do when the two answers disagreed.

   Four things this schema is deliberately built to prevent:

   1. AN ASSUMED READING. There is no default hardness and no lookup by ZIP.
      A household with no row here is untested, the application applies a factor
      of 1.00, and the customer report says the water has not been tested.
      Inferring hardness from an address would be inventing a measurement.

   2. A LOST HISTORY. Every test is a row. A jump from 3 gpg to 14 gpg between
      two visits is a softener that has failed since the last one -- which is a
      finding worth more to the customer than either reading alone, and is only
      visible if the earlier row survives.

   3. A STORED MULTIPLIER. The factor is nowhere in the data. It is derived, on
      read, from the reading and the current anchors -- so correcting the anchors
      corrects every house at once. A factor written onto the test row at save
      time would freeze today's inference into history and quietly outlive it.

   4. AN INFERENCE PASSING AS A STUDY. IsSourced on the settings row is 0 and
      is meant to stay 0 until somebody puts a real lifespan study behind these
      numbers. The anchors are Wilson's inference from a water-heater EFFICIENCY
      study, and the basis text says so wherever the figure is shown.
   ------------------------------------------------------------------------- */

/* The bands, seeded from plan-config.js. DESCRIPTION ONLY -- they name a
   reading for the customer and carry no arithmetic. MaxGrainsPerGallon NULL is
   the open-topped band. */
IF OBJECT_ID('dbo.MaintenanceWaterHardnessBands', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.MaintenanceWaterHardnessBands (
        WaterHardnessBandId INT IDENTITY(1,1) NOT NULL
            CONSTRAINT PK_MaintenanceWaterHardnessBands PRIMARY KEY,
        BandCode NVARCHAR(30) NOT NULL
            CONSTRAINT UQ_MaintenanceWaterHardnessBands_Code UNIQUE,
        DisplayName NVARCHAR(60) NOT NULL,
        MaxGrainsPerGallon DECIMAL(6,2) NULL,
        PlainLanguage NVARCHAR(200) NULL,
        SortOrder INT NOT NULL,
        IsActive BIT NOT NULL
            CONSTRAINT DF_MaintenanceWaterHardnessBands_Active DEFAULT (1)
    );
END;
GO

/* THE ALGORITHM, as data. The curve is piecewise linear through these points
   and flat outside them: at or below the first anchor the factor is 1.000, at
   or above the last it stops. The last anchor is 26 gpg because that is the
   hardness Battelle actually measured -- past the evidence the curve does not
   continue on confidence alone.

   The floor is fenced by a CHECK for the same reason it is fenced in the
   application: the source is an efficiency figure, not a lifespan study, and an
   anchor that halved an appliance's life would claim far more than it supports. */
IF OBJECT_ID('dbo.MaintenanceWaterLifeFactorAnchors', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.MaintenanceWaterLifeFactorAnchors (
        GrainsPerGallon DECIMAL(6,2) NOT NULL
            CONSTRAINT PK_MaintenanceWaterLifeFactorAnchors PRIMARY KEY,
        LifeFactor DECIMAL(4,3) NOT NULL
            CONSTRAINT CK_MaintenanceWaterLifeFactorAnchors_Factor
                CHECK (LifeFactor >= 0.7 AND LifeFactor <= 1.0),
        SortOrder INT NOT NULL,
        IsActive BIT NOT NULL
            CONSTRAINT DF_MaintenanceWaterLifeFactorAnchors_Active DEFAULT (1)
    );
END;
GO

/* Which protocols run water at all. A dryer does not care how hard the water
   is, and quietly shortening its expected life would be inventing a mechanism.
   Seeded from plan-config.js, so the dashboard cannot widen the blast radius
   without the application agreeing. */
IF OBJECT_ID('dbo.MaintenanceWaterBearingProtocols', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.MaintenanceWaterBearingProtocols (
        TemplateCode NVARCHAR(40) NOT NULL
            CONSTRAINT PK_MaintenanceWaterBearingProtocols PRIMARY KEY,
        IsActive BIT NOT NULL
            CONSTRAINT DF_MaintenanceWaterBearingProtocols_Active DEFAULT (1)
    );
END;
GO

/* One row. The scalars that govern the whole modifier, in the database so the
   dashboard reads the same numbers -- and the same disclaimer -- as the field
   tool. */
IF OBJECT_ID('dbo.MaintenanceWaterHardnessSettings', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.MaintenanceWaterHardnessSettings (
        SettingsId TINYINT NOT NULL
            CONSTRAINT PK_MaintenanceWaterHardnessSettings PRIMARY KEY
            CONSTRAINT CK_MaintenanceWaterHardnessSettings_Single CHECK (SettingsId = 1),
        /* What an untested house gets. 1.000, and it is a column rather than a
           literal so that anyone tempted to change it has to look at it. */
        UntestedLifeFactor DECIMAL(4,3) NOT NULL
            CONSTRAINT CK_MaintenanceWaterHardnessSettings_Untested
                CHECK (UntestedLifeFactor = 1.0),
        /* At or above this band the customer's report carries a hardness flag.
           Below it the water is worth stating but not worth flagging -- a flag
           on every address Wilson serves is a flag people learn to ignore. */
        CustomerFlagBandCode NVARCHAR(30) NOT NULL,
        /* Nothing potable reads this high; above it is a mis-key, refused
           rather than banded. */
        MaxPlausibleGpg DECIMAL(6,2) NOT NULL,
        /* Where the numbers come from, printed wherever the adjustment shows. */
        Basis NVARCHAR(2000) NOT NULL,
        /* 0 = Wilson's inference, not a published lifespan study. */
        IsSourced BIT NOT NULL
            CONSTRAINT DF_MaintenanceWaterHardnessSettings_Sourced DEFAULT (0),
        UpdatedAt DATETIME2 NOT NULL
            CONSTRAINT DF_MaintenanceWaterHardnessSettings_Updated DEFAULT (SYSUTCDATETIME()),
        CONSTRAINT FK_MaintenanceWaterHardnessSettings_Band
            FOREIGN KEY (CustomerFlagBandCode)
            REFERENCES dbo.MaintenanceWaterHardnessBands(BandCode)
    );
END;
GO

/* The readings themselves. Full history, one row per test. */
IF OBJECT_ID('dbo.MaintenanceHouseholdWaterTests', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.MaintenanceHouseholdWaterTests (
        WaterTestId INT IDENTITY(1,1) NOT NULL
            CONSTRAINT PK_MaintenanceHouseholdWaterTests PRIMARY KEY,
        HouseholdId INT NOT NULL,
        /* Which visit produced it, where there was one. Nullable because a
           reading can also arrive from an office follow-up call. */
        VisitId INT NULL,
        /* THE reading, and the only input. NOT NULL: a water test row without a
           number is not a water test, and there is no band to fall back on
           because bands no longer carry arithmetic. A house nobody tested has no
           row at all, which is a different and honest thing.

           No band and no factor are stored beside it. Both are derived on read
           from this number, so a corrected anchor corrects every house. */
        GrainsPerGallon DECIMAL(6,2) NOT NULL
            CONSTRAINT CK_MaintenanceHouseholdWaterTests_Gpg
                CHECK (GrainsPerGallon >= 0 AND GrainsPerGallon <= 100),
        TestedOn DATE NOT NULL,
        TestedByUserId NVARCHAR(60) NULL,
        TestedByName NVARCHAR(120) NULL,
        Notes NVARCHAR(600) NULL,
        CreatedAt DATETIME2 NOT NULL
            CONSTRAINT DF_MaintenanceHouseholdWaterTests_Created DEFAULT (SYSUTCDATETIME()),
        CONSTRAINT FK_MaintenanceHouseholdWaterTests_Household
            FOREIGN KEY (HouseholdId) REFERENCES dbo.MaintenanceHouseholds(HouseholdId)
    );
END;
GO

IF NOT EXISTS (
    SELECT 1 FROM sys.indexes
    WHERE name = 'IX_MaintenanceHouseholdWaterTests_Household'
      AND object_id = OBJECT_ID('dbo.MaintenanceHouseholdWaterTests')
)
    CREATE INDEX IX_MaintenanceHouseholdWaterTests_Household
        ON dbo.MaintenanceHouseholdWaterTests(HouseholdId, TestedOn DESC, WaterTestId DESC);
GO

/* -------------------------------------------------------------------------
   7.11  BRAND, PRODUCT LINE AND SERVICEABILITY   (v0.9.30)

   Three facts the dashboard has to agree with the field tool about:

     - which product line an appliance belongs to, which is a second axis the
       old brand -> tier -> years chain did not have;
     - how long a given brand's product on a given line is expected to last,
       with BOTH numbers behind it so the figure can be traced rather than
       merely displayed;
     - whether Wilson can put the appliance on a plan at all, and which of the
       two reasons applies if not.

   Additive and idempotent like every other section here.
   ------------------------------------------------------------------------- */
IF OBJECT_ID('dbo.MaintenanceApplianceLines', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.MaintenanceApplianceLines (
        ApplianceLineId INT IDENTITY(1,1) NOT NULL
            CONSTRAINT PK_MaintenanceApplianceLines PRIMARY KEY,
        LineCode NVARCHAR(40) NOT NULL
            CONSTRAINT UQ_MaintenanceApplianceLines_Code UNIQUE,
        DisplayName NVARCHAR(60) NOT NULL,
        /* The protocol templates, customer categories and appliance types that
           resolve to this line. JSON rather than three child tables because the
           dashboard reads it whole and never joins on it. */
        MatchSets NVARCHAR(MAX) NULL,
        MatchCategories NVARCHAR(MAX) NULL,
        MatchTypes NVARCHAR(MAX) NULL,
        IsActive BIT NOT NULL
            CONSTRAINT DF_MaintenanceApplianceLines_Active DEFAULT (1),
        UpdatedAt DATETIME2(0) NOT NULL
            CONSTRAINT DF_MaintenanceApplianceLines_Updated DEFAULT (SYSUTCDATETIME())
    );
END;
GO

IF OBJECT_ID('dbo.MaintenanceBrandLifespans', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.MaintenanceBrandLifespans (
        BrandLifespanId INT IDENTITY(1,1) NOT NULL
            CONSTRAINT PK_MaintenanceBrandLifespans PRIMARY KEY,
        BrandKey NVARCHAR(60) NOT NULL,
        /* '*' IS A BRAND-WIDE FIGURE -- "thermador 15y across all product". Such
           a row carries no ExpectedYears and no AnchoredYears, because the
           anchored half depends on which line it lands on: the same 15 resolves
           to 17 against the hood column and 18 against the range column. The
           consumer computes the midpoint at lookup, rounding halves UP. */
        LineCode NVARCHAR(40) NOT NULL,
        /* NULL for a brand's plain row. A series row is checked FIRST and
           matches on text found in the model number or description. */
        SeriesCode NVARCHAR(60) NULL,
        SeriesLabel NVARCHAR(80) NULL,
        SeriesMatchText NVARCHAR(MAX) NULL,
        TierCode NVARCHAR(30) NOT NULL,
        /* The shipped figure, and the two numbers it is the midpoint of.
           FieldYears is Wilson's service experience; AnchoredYears is
           MaintenanceExpectedLife for this line and tier. Both are kept so a
           number nobody agrees with can be argued with rather than only
           overwritten. */
        ExpectedYears DECIMAL(5,1) NULL,
        FieldYears DECIMAL(5,1) NOT NULL,
        AnchoredYears DECIMAL(5,1) NULL,
        /* Brand-wide rows only: the lines that brand actually sells, as a JSON
           array. A brand-wide row must answer on nothing outside it -- Asko has
           no outdoor grill and Bertazzoni no coffee system. An EMPTY or absent
           list must mean "no lines", never "all lines". CoversDrafted marks a
           list drafted from public catalogues rather than confirmed by Wilson. */
        CoversLines NVARCHAR(MAX) NULL,
        CoversDrafted BIT NOT NULL
            CONSTRAINT DF_MaintenanceBrandLifespans_Drafted DEFAULT (0),
        /* Whose judgement the row's tier was. Tier chooses the column
           AnchoredYears comes from, so it moves the number. */
        TierDrafted BIT NOT NULL
            CONSTRAINT DF_MaintenanceBrandLifespans_TierDrafted DEFAULT (0),
        /* Set when FieldYears stands ALONE because no published figure covers
           this equipment -- outdoor undercounter refrigeration and ice, where
           NAHB's rows are indoor machines, and built-in coffee, whose columns
           were drafted from the one row that would be averaged against them.
           AnchoredYears is NULL and ExpectedYears equals FieldYears. */
        NoAnchorReason NVARCHAR(400) NULL,
        /* A named line must ship its resolved figure; a brand-wide row must NOT,
           or one line's column would be silently applied to all of them. */
        CONSTRAINT CK_MaintenanceBrandLifespans_Resolved CHECK (
            (LineCode <> '*' AND ExpectedYears IS NOT NULL
             /* Unanchored means the field figure stands alone, and says why. */
             AND (AnchoredYears IS NOT NULL
                  OR (NoAnchorReason IS NOT NULL AND ExpectedYears = FieldYears)))
            OR (LineCode = '*' AND ExpectedYears IS NULL AND AnchoredYears IS NULL
                AND CoversLines IS NOT NULL)
        ),
        IsActive BIT NOT NULL
            CONSTRAINT DF_MaintenanceBrandLifespans_Active DEFAULT (1),
        UpdatedAt DATETIME2(0) NOT NULL
            CONSTRAINT DF_MaintenanceBrandLifespans_Updated DEFAULT (SYSUTCDATETIME()),
        CONSTRAINT UQ_MaintenanceBrandLifespans_Row
            UNIQUE (BrandKey, LineCode, SeriesCode)
    );
END;
GO

IF OBJECT_ID('dbo.MaintenanceBrandExclusions', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.MaintenanceBrandExclusions (
        BrandExclusionId INT IDENTITY(1,1) NOT NULL
            CONSTRAINT PK_MaintenanceBrandExclusions PRIMARY KEY,
        BrandKey NVARCHAR(60) NOT NULL
            CONSTRAINT UQ_MaintenanceBrandExclusions_Brand UNIQUE,
        DisplayName NVARCHAR(80) NOT NULL,
        /* NOT_SERVICED  -- Wilson neither sells nor services it.
           NOT_MAINTAINABLE -- Wilson sells it and would service it, but there is
           no maintenance to perform. These are different facts and the copy
           below is deliberately different for each. */
        ExclusionKind NVARCHAR(30) NOT NULL
            CONSTRAINT CK_MaintenanceBrandExclusions_Kind
            CHECK (ExclusionKind IN ('NOT_SERVICED', 'NOT_MAINTAINABLE')),
        Because NVARCHAR(60) NULL,
        IsActive BIT NOT NULL
            CONSTRAINT DF_MaintenanceBrandExclusions_Active DEFAULT (1),
        UpdatedAt DATETIME2(0) NOT NULL
            CONSTRAINT DF_MaintenanceBrandExclusions_Updated DEFAULT (SYSUTCDATETIME())
    );
END;
GO

IF OBJECT_ID('dbo.MaintenanceServiceabilityCopy', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.MaintenanceServiceabilityCopy (
        ServiceabilityCopyId INT IDENTITY(1,1) NOT NULL
            CONSTRAINT PK_MaintenanceServiceabilityCopy PRIMARY KEY,
        StateCode NVARCHAR(30) NOT NULL
            CONSTRAINT UQ_MaintenanceServiceabilityCopy_State UNIQUE,
        /* One sentence per audience, so the customer report, the office queue
           card and the technician's appliance card cannot drift into three
           explanations that merely agree. CustomerText is deliberately EMPTY for
           an unrecognised brand -- that is an internal question, and printing it
           would leak uncertainty onto somebody's report. */
        CustomerText NVARCHAR(400) NULL,
        OfficeText NVARCHAR(400) NULL,
        TechText NVARCHAR(400) NULL,
        UpdatedAt DATETIME2(0) NOT NULL
            CONSTRAINT DF_MaintenanceServiceabilityCopy_Updated DEFAULT (SYSUTCDATETIME())
    );
END;
GO

-- {{BRAND_SEED}}

-- {{WATER_SEED}}

/* -------------------------------------------------------------------------
   The current water for each household, resolved.

   THE FACTOR IS COMPUTED HERE, FROM THE READING. This view carries the same
   algorithm as WILSON_WATER.lifeFactorForGpg() in plan-config.js and the two
   must not drift:

     - at or below the first anchor  -> 1.000
     - at or above the last anchor   -> that anchor's factor, FLAT
     - between two anchors           -> linear, rounded to 3 decimals

   The rounding is part of the contract, not an implementation detail. Without
   it the two sides agree to fourteen decimal places and disagree in the
   fifteenth, which is enough to print a different number of years.

   A household with no test does not appear here. Absence means untested, which
   means no adjustment -- callers must LEFT JOIN and treat a miss as a factor of
   1.00 rather than filtering the household out of a report.
   ------------------------------------------------------------------------- */
IF OBJECT_ID('dbo.vw_MaintenanceHouseholdWaterLatest', 'V') IS NOT NULL
    DROP VIEW dbo.vw_MaintenanceHouseholdWaterLatest;
GO

CREATE VIEW dbo.vw_MaintenanceHouseholdWaterLatest
AS
WITH latest AS (
    SELECT t.*,
           ROW_NUMBER() OVER (PARTITION BY t.HouseholdId
                              ORDER BY t.TestedOn DESC, t.WaterTestId DESC) AS rn
    FROM dbo.MaintenanceHouseholdWaterTests t
),
bounds AS (
    SELECT MIN(GrainsPerGallon) AS FirstGpg, MAX(GrainsPerGallon) AS LastGpg
    FROM dbo.MaintenanceWaterLifeFactorAnchors WHERE IsActive = 1
),
interpolated AS (
    SELECT
        l.HouseholdId, l.WaterTestId, l.VisitId, l.GrainsPerGallon,
        l.TestedOn, l.TestedByName,
        CAST(CASE
            /* Flat below the first anchor and above the last. */
            WHEN l.GrainsPerGallon <= bd.FirstGpg THEN
                (SELECT LifeFactor FROM dbo.MaintenanceWaterLifeFactorAnchors
                 WHERE GrainsPerGallon = bd.FirstGpg)
            WHEN l.GrainsPerGallon >= bd.LastGpg THEN
                (SELECT LifeFactor FROM dbo.MaintenanceWaterLifeFactorAnchors
                 WHERE GrainsPerGallon = bd.LastGpg)
            /* Linear between the two anchors that bracket the reading. */
            ELSE ROUND(
                lo.LifeFactor
                + ((l.GrainsPerGallon - lo.GrainsPerGallon)
                   / NULLIF(hi.GrainsPerGallon - lo.GrainsPerGallon, 0))
                  * (hi.LifeFactor - lo.LifeFactor), 3)
        END AS DECIMAL(4,3)) AS LifeFactor
    FROM latest l
    CROSS JOIN bounds bd
    /* `an`, not `a`: throughout this migration `a.` is MaintenanceAssets, and
       reusing it here for the anchor table read as an asset column to anything
       scanning the file -- including this package's own schema checker, which
       is what caught it. */
    OUTER APPLY (
        SELECT TOP (1) an.GrainsPerGallon, an.LifeFactor
        FROM dbo.MaintenanceWaterLifeFactorAnchors an
        WHERE an.IsActive = 1 AND an.GrainsPerGallon <= l.GrainsPerGallon
        ORDER BY an.GrainsPerGallon DESC
    ) lo
    OUTER APPLY (
        SELECT TOP (1) an.GrainsPerGallon, an.LifeFactor
        FROM dbo.MaintenanceWaterLifeFactorAnchors an
        WHERE an.IsActive = 1 AND an.GrainsPerGallon > l.GrainsPerGallon
        ORDER BY an.GrainsPerGallon ASC
    ) hi
    WHERE l.rn = 1
)
SELECT
    i.HouseholdId,
    i.WaterTestId,
    i.VisitId,
    i.GrainsPerGallon,
    i.TestedOn,
    i.TestedByName,
    /* The band names the reading for the customer. It carries no arithmetic --
       the factor above came from the number, not from this. */
    b.BandCode,
    b.DisplayName AS BandName,
    b.PlainLanguage,
    /* The flag the customer's report shows. */
    CASE WHEN b.SortOrder >= fb.SortOrder THEN CAST(1 AS BIT) ELSE CAST(0 AS BIT) END
        AS IsFlaggedToCustomer,
    i.LifeFactor,
    cfg.Basis,
    cfg.IsSourced
FROM interpolated i
CROSS JOIN dbo.MaintenanceWaterHardnessSettings cfg
INNER JOIN dbo.MaintenanceWaterHardnessBands fb
    ON fb.BandCode = cfg.CustomerFlagBandCode
OUTER APPLY (
    SELECT TOP (1) bb.BandCode, bb.DisplayName, bb.PlainLanguage, bb.SortOrder
    FROM dbo.MaintenanceWaterHardnessBands bb
    WHERE bb.IsActive = 1
      AND (bb.MaxGrainsPerGallon IS NULL OR i.GrainsPerGallon <= bb.MaxGrainsPerGallon)
    ORDER BY bb.SortOrder ASC
) b;
GO

/* -------------------------------------------------------------------------
   Expected service life per asset, after water.

   The join that makes the modifier real: base expected life by template and
   tier, multiplied by the household's factor, but ONLY for protocols that run
   water. Everything else passes through untouched, and an untested household
   passes through untouched as well.

   WHERE THE TIER COMES FROM, and why not from the asset. MaintenanceAssets has
   no tier column -- tier is resolved from the brand through
   MaintenanceBrandTiers, and re-implementing that match here would be a second
   copy of a rule that already exists in two places. So this view takes the tier
   that was ACTUALLY USED, off the most recent field inspection, which is both
   already recorded and the figure the customer was shown. An asset nobody has
   inspected yet has no tier here and therefore no expected life: it reports
   NULL rather than a guess, and UsesWater and WaterLifeFactor are still
   populated so the dashboard can show the water finding regardless.
   ------------------------------------------------------------------------- */
IF OBJECT_ID('dbo.vw_MaintenanceAssetExpectedLife', 'V') IS NOT NULL
    DROP VIEW dbo.vw_MaintenanceAssetExpectedLife;
GO

CREATE VIEW dbo.vw_MaintenanceAssetExpectedLife
AS
WITH last_inspection AS (
    SELECT fi.AssetId, fi.LifecycleTierCode,
           ROW_NUMBER() OVER (PARTITION BY fi.AssetId
                              ORDER BY COALESCE(fi.CompletedAt, fi.StartedAt, fi.CreatedAt) DESC,
                                       fi.FieldInspectionId DESC) AS rn
    FROM dbo.MaintenanceFieldInspections fi
    WHERE fi.LifecycleTierCode IS NOT NULL
)
SELECT
    a.AssetId,
    a.HouseholdId,
    a.AssetTypeName,
    a.CheckpointSetCode AS TemplateCode,
    li.LifecycleTierCode AS TierCode,
    r.ExpectedYears AS BaseExpectedYears,
    CASE WHEN wb.TemplateCode IS NULL THEN CAST(0 AS BIT) ELSE CAST(1 AS BIT) END
        AS UsesWater,
    /* No test, or an appliance that never touches water, means no adjustment.
       COALESCE, not a default row: absence is the honest answer. */
    CASE WHEN wb.TemplateCode IS NULL THEN CAST(1.000 AS DECIMAL(4,3))
         ELSE COALESCE(w.LifeFactor, CAST(1.000 AS DECIMAL(4,3))) END AS WaterLifeFactor,
    CAST(ROUND(r.ExpectedYears *
        CASE WHEN wb.TemplateCode IS NULL THEN 1.000
             ELSE COALESCE(w.LifeFactor, 1.000) END, 1) AS DECIMAL(5,1))
        AS AdjustedExpectedYears,
    w.BandCode,
    w.GrainsPerGallon,
    w.IsFlaggedToCustomer
FROM dbo.MaintenanceAssets a
LEFT JOIN last_inspection li
    ON li.AssetId = a.AssetId AND li.rn = 1
LEFT JOIN dbo.MaintenanceExpectedLifeRules r
    ON r.TemplateCode = a.CheckpointSetCode
   AND r.TierCode = li.LifecycleTierCode
   AND r.IsActive = 1
LEFT JOIN dbo.MaintenanceWaterBearingProtocols wb
    ON wb.TemplateCode = a.CheckpointSetCode AND wb.IsActive = 1
LEFT JOIN dbo.vw_MaintenanceHouseholdWaterLatest w
    ON w.HouseholdId = a.HouseholdId;
GO

/* -------------------------------------------------------------------------
   Which appliances have a documented age, and which do not.

   The operational list behind the cold-start problem: every row here with
   IsDocumented = 0 is an appliance whose health score rests partly on a guess,
   and most of them have an invoice somebody can pull.
   ------------------------------------------------------------------------- */
IF OBJECT_ID('dbo.vw_MaintenanceAssetAgeProvenance', 'V') IS NOT NULL
    DROP VIEW dbo.vw_MaintenanceAssetAgeProvenance;
GO

CREATE VIEW dbo.vw_MaintenanceAssetAgeProvenance
AS
SELECT
    a.AssetId,
    a.HouseholdId,
    a.AssetTypeName,
    a.Brand,
    a.Model,
    a.InstallYear,
    a.InstallDate,
    COALESCE(a.AgeSourceCode, 'unknown') AS AgeSourceCode,
    COALESCE(s.DisplayName, 'Not established') AS AgeSourceName,
    COALESCE(s.IsDocumented, 0) AS IsDocumented,
    a.AgeSourceReference,
    /* NULL, not zero: an appliance with no install year has no age, and an age
       of 0 would read as brand new. */
    CASE WHEN a.InstallYear IS NULL THEN NULL
         ELSE YEAR(SYSUTCDATETIME()) - a.InstallYear END AS AgeYears,
    CASE WHEN a.InstallYear IS NULL THEN CAST(1 AS BIT) ELSE CAST(0 AS BIT) END AS ScoredOnConditionOnly
FROM dbo.MaintenanceAssets a
LEFT JOIN dbo.MaintenanceAgeSources s
    ON s.AgeSourceCode = a.AgeSourceCode;
GO

/* -------------------------------------------------------------------------
   Schema version
   ------------------------------------------------------------------------- */
IF NOT EXISTS (
    SELECT 1 FROM dbo.MaintenanceSchemaVersions WHERE VersionNumber = '0.9'
)
BEGIN
    INSERT INTO dbo.MaintenanceSchemaVersions (VersionNumber, Notes)
    VALUES ('0.9', 'Property areas, AR billing, technician field inspection layer, report delivery tracking, technician user linkage, and versioned lifecycle/protocol configuration. Age provenance and photographic evidence. Protocol and age-source seeds generated from plan-config.js v{{CONFIG_VERSION}}.');
END;
GO
