"""proto_dmg.js — today's delivery board, from the real sales export: the deliveries behind the damage rows the
service request queue receives.

⟨9/19 late⟩ The installers' form itself lives in Agility and is not rebuilt here (Cayden). What the board needs
is the delivery each queue row refers to — real invoice codes, models and serials — so a row on the incoming
panel is a real customer's real unit. Customer data, so this file is gitignored like reference/data.
"""
import sqlite3, json

c = sqlite3.connect('/tmp/hist.db'); c.row_factory = sqlite3.Row
q = """
SELECT s.invoice_code inv, s.created_date date, cu.display_name cust, a.line1 addr, a.city, a.zip,
       COUNT(DISTINCT ss.sale_serial_id) n
FROM sale s JOIN customer cu ON cu.customer_id=s.customer_id
LEFT JOIN address a ON a.customer_id=cu.customer_id
JOIN sale_serial ss ON ss.invoice_code=s.invoice_code
WHERE s.created_date>='2026-08-15' AND s.inv_type IN ('S','R')
  AND cu.display_name NOT LIKE '%WARRANTY%' AND cu.display_name NOT LIKE '%WHIRLPOOL%'
  AND cu.display_name NOT LIKE '%SUBZERO%' AND cu.display_name NOT LIKE '*%'
  AND a.line1 IS NOT NULL AND a.zip IS NOT NULL AND length(a.line1)>6
GROUP BY s.invoice_code HAVING n BETWEEN 1 AND 3
ORDER BY (n>1) DESC, s.created_date DESC LIMIT 12"""
stops = []
for r in c.execute(q):
    units = [dict(u) for u in c.execute("""
        SELECT ss.model_code model, ss.serial, COALESCE(MAX(sl.model_desc),'') dsc, COALESCE(MAX(sl.brand_code),'') brand
        FROM sale_serial ss LEFT JOIN sale_line sl ON sl.invoice_code=ss.invoice_code AND sl.model_code=ss.model_code
        WHERE ss.invoice_code=? GROUP BY ss.serial ORDER BY ss.sale_serial_id LIMIT 3""", (r['inv'],))]
    units = [u for u in units if u['serial'] and u['model']]
    if not units:
        continue
    stops.append({'inv': r['inv'], 'cust': r['cust'], 'addr': r['addr'], 'city': r['city'],
                  'zip': r['zip'], 'date': r['date'], 'units': units})

trucks = [('D02', 2), ('D03', 5), ('D06', 5)]
out, i = [], 0
for tid, n in trucks:
    out.append({'id': tid, 'stops': stops[i:i + n]})
    i += n
body = ("/* generated by builddmg.py from the ePASS sales export — today's delivery board behind the cosmetic\n"
        "   request queue's damage rows. Real invoice codes, models and serials; no phone numbers. Gitignored. */\n"
        "const DMG_TRUCKS=" + json.dumps(out, separators=(',', ':')) + ";\n")
open('proto_dmg.js', 'w', encoding='utf-8').write(body)
print(f"{sum(len(t['stops']) for t in out)} stops over {len(out)} trucks · {len(body):,} bytes")
for t in out:
    print(' ', t['id'], len(t['stops']), 'stops ·', ', '.join(s['inv'] for s in t['stops']))
