/*
Wilson Maintenance Portal - SQL Server migration v0.9
Generated by sql/generate_migration_v09.py -- do not hand-edit.
Edit sql/_migration_v09_ddl.sql (structure) or assets/plan-config.js (seed data)
and re-run the generator.

Purpose
-------
Implements MERGE_GUIDE.md section 7: the schema additions required before the
real merge. sql/maintenance_schema.sql is at v0.3 (2026-08-21) and predates the
v0.5-v0.9 field workflow entirely -- it has no tables for technician
inspections, checkpoints, readings, photos, areas, or lifecycle/brand tier, and
its health-report tables still reflect the report builder that v0.7 retired.

Covers:
  7.1  Property areas                     MaintenanceAreas, MaintenanceAssets.AreaId
  7.2  Household billing method / AR      MaintenanceHouseholds billing columns
  7.3  Raw technician inspection data     MaintenanceFieldInspections (+Checks, +Photos)
  7.4  Report delivery tracking           MaintenanceReportDeliveries
  7.5  Technician assignment / user id    MaintenanceVisits technician columns
  7.6  Lifecycle configuration            MaintenanceLifecycleTiers, MaintenanceBrandTiers,
                                          MaintenanceExpectedLifeRules, MaintenanceLifecycleStages
  7.7  Protocol configuration             MaintenanceProtocolTemplates, MaintenanceProtocolCheckpoints,
                                          MaintenanceProtocolAssignments

Status codes use the centralized vocabularies from MERGE_GUIDE section 34 and
are enforced with CHECK constraints, so a UI phrase can never be persisted as
state.

Applying this script
--------------------
Run sql/maintenance_schema.sql first. This script is strictly additive and
idempotent: every object is guarded, every column addition is guarded by
COL_LENGTH, and every seed is a MERGE. Re-running it is safe and is the
intended way to pick up protocol changes.

It deliberately does NOT redefine any existing object. sql/maintenance_schema.sql
ends with three CREATE OR ALTER VIEW statements; if this migration altered one of
them, a later re-run of the base script would silently revert it. New behaviour
is therefore delivered as new views instead.

Not covered here
----------------
- Retiring the office-built report tables (MaintenanceHealthReport* still carry
  the pre-v0.7 model). They are left intact because live prototype data may
  reference them; plan their retirement with the API contract rewrite.
- Photo binary storage. Only the storage key is modelled -- see MERGE_GUIDE
  section 20.
- HVAC field protocols. No HVAC field workflow exists yet (context section 34
  item 3), so no HVAC protocol templates are seeded.

Security
--------
No cardholder data. Technician identity is stored as the authoritative internal
user id plus a display-name snapshot for historical reporting.
*/

SET NOCOUNT ON;
SET XACT_ABORT ON;
GO

/* -------------------------------------------------------------------------
   Preflight: the base schema must already be present
   ------------------------------------------------------------------------- */
IF OBJECT_ID('dbo.MaintenanceHouseholds', 'U') IS NULL
    OR OBJECT_ID('dbo.MaintenanceAssets', 'U') IS NULL
    OR OBJECT_ID('dbo.MaintenanceVisits', 'U') IS NULL
    OR OBJECT_ID('dbo.MaintenanceHealthReports', 'U') IS NULL
BEGIN
    RAISERROR (
        'Base maintenance schema not found. Run sql/maintenance_schema.sql before this migration.',
        20, 1
    ) WITH LOG;
END;
GO

/* -------------------------------------------------------------------------
   7.1  Property areas
   ------------------------------------------------------------------------- */
IF OBJECT_ID('dbo.MaintenanceAreas', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.MaintenanceAreas (
        AreaId INT IDENTITY(1,1) NOT NULL
            CONSTRAINT PK_MaintenanceAreas PRIMARY KEY,
        HouseholdId INT NOT NULL,
        AreaName NVARCHAR(150) NOT NULL,
        AreaKind NVARCHAR(30) NULL,
        SortOrder INT NULL,
        AreaStatus NVARCHAR(30) NOT NULL
            CONSTRAINT DF_MaintenanceAreas_Status DEFAULT ('Active'),
        CreatedAt DATETIME2 NOT NULL
            CONSTRAINT DF_MaintenanceAreas_CreatedAt DEFAULT SYSUTCDATETIME(),
        UpdatedAt DATETIME2 NOT NULL
            CONSTRAINT DF_MaintenanceAreas_UpdatedAt DEFAULT SYSUTCDATETIME(),
        VersionStamp ROWVERSION,
        CONSTRAINT FK_MaintenanceAreas_Households
            FOREIGN KEY (HouseholdId) REFERENCES dbo.MaintenanceHouseholds(HouseholdId)
    );

    CREATE UNIQUE INDEX UX_MaintenanceAreas_HouseholdName
        ON dbo.MaintenanceAreas(HouseholdId, AreaName);

    CREATE INDEX IX_MaintenanceAreas_Household
        ON dbo.MaintenanceAreas(HouseholdId, AreaStatus, SortOrder);
END;
GO

/* AreaId on assets. LocationName is kept as the text snapshot the customer and
   invoice import actually entered -- see MERGE_GUIDE 7.1. */
IF COL_LENGTH('dbo.MaintenanceAssets', 'AreaId') IS NULL
    ALTER TABLE dbo.MaintenanceAssets ADD AreaId INT NULL;
GO
IF OBJECT_ID('dbo.FK_MaintenanceAssets_Areas', 'F') IS NULL
    ALTER TABLE dbo.MaintenanceAssets ADD CONSTRAINT FK_MaintenanceAssets_Areas
        FOREIGN KEY (AreaId) REFERENCES dbo.MaintenanceAreas(AreaId);
GO
IF NOT EXISTS (
    SELECT 1 FROM sys.indexes
    WHERE name = 'IX_MaintenanceAssets_Area'
      AND object_id = OBJECT_ID('dbo.MaintenanceAssets')
)
    CREATE INDEX IX_MaintenanceAssets_Area
        ON dbo.MaintenanceAssets(AreaId, SortOrder);
GO

/* -------------------------------------------------------------------------
   7.2  Household billing method / AR

   Added as columns on MaintenanceHouseholds rather than a separate 1:1 billing
   profile table (MERGE_GUIDE 7.2 permits either). Command Center payment
   readiness is a per-household question on nearly every queue query, and a 1:1
   table would add a join to all of them for four columns with no history
   requirement. MaintenancePaymentProfiles already holds the card-side rows.
   ------------------------------------------------------------------------- */
IF COL_LENGTH('dbo.MaintenanceHouseholds', 'BillingMethodCode') IS NULL
    ALTER TABLE dbo.MaintenanceHouseholds ADD BillingMethodCode NVARCHAR(30) NOT NULL
        CONSTRAINT DF_MaintenanceHouseholds_BillingMethod DEFAULT ('CARD_ON_FILE');
GO
IF COL_LENGTH('dbo.MaintenanceHouseholds', 'AccountTerms') IS NULL
    ALTER TABLE dbo.MaintenanceHouseholds ADD AccountTerms NVARCHAR(50) NULL;
GO
IF COL_LENGTH('dbo.MaintenanceHouseholds', 'ExternalARCustomerId') IS NULL
    ALTER TABLE dbo.MaintenanceHouseholds ADD ExternalARCustomerId NVARCHAR(100) NULL;
GO
IF COL_LENGTH('dbo.MaintenanceHouseholds', 'ARStatus') IS NULL
    ALTER TABLE dbo.MaintenanceHouseholds ADD ARStatus NVARCHAR(30) NULL;
GO
IF OBJECT_ID('dbo.CK_MaintenanceHouseholds_BillingMethod', 'C') IS NULL
    ALTER TABLE dbo.MaintenanceHouseholds
        ADD CONSTRAINT CK_MaintenanceHouseholds_BillingMethod
        CHECK (BillingMethodCode IN ('CARD_ON_FILE', 'AR_ACCOUNT'));
GO
IF OBJECT_ID('dbo.CK_MaintenanceHouseholds_ARStatus', 'C') IS NULL
    ALTER TABLE dbo.MaintenanceHouseholds
        ADD CONSTRAINT CK_MaintenanceHouseholds_ARStatus
        CHECK (ARStatus IS NULL OR ARStatus IN ('Active', 'Hold', 'Review'));
GO

/* -------------------------------------------------------------------------
   7.6 / 7.7  Configuration tables

   Table definitions only; seed data is generated at the end of this script.
   ------------------------------------------------------------------------- */
IF OBJECT_ID('dbo.MaintenanceLifecycleTiers', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.MaintenanceLifecycleTiers (
        LifecycleTierId INT IDENTITY(1,1) NOT NULL
            CONSTRAINT PK_MaintenanceLifecycleTiers PRIMARY KEY,
        TierCode NVARCHAR(20) NOT NULL
            CONSTRAINT UQ_MaintenanceLifecycleTiers_Code UNIQUE,
        TierLabel NVARCHAR(50) NOT NULL,
        DefaultExpectedYears DECIMAL(5,1) NULL,
        ExampleBrands NVARCHAR(500) NULL,
        IsActive BIT NOT NULL
            CONSTRAINT DF_MaintenanceLifecycleTiers_Active DEFAULT (1),
        CreatedAt DATETIME2 NOT NULL
            CONSTRAINT DF_MaintenanceLifecycleTiers_CreatedAt DEFAULT SYSUTCDATETIME(),
        UpdatedAt DATETIME2 NOT NULL
            CONSTRAINT DF_MaintenanceLifecycleTiers_UpdatedAt DEFAULT SYSUTCDATETIME()
    );
END;
GO

IF OBJECT_ID('dbo.MaintenanceBrandTiers', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.MaintenanceBrandTiers (
        BrandTierId INT IDENTITY(1,1) NOT NULL
            CONSTRAINT PK_MaintenanceBrandTiers PRIMARY KEY,
        BrandMatchText NVARCHAR(100) NOT NULL
            CONSTRAINT UQ_MaintenanceBrandTiers_Match UNIQUE,
        MatchType NVARCHAR(20) NOT NULL
            CONSTRAINT DF_MaintenanceBrandTiers_MatchType DEFAULT ('CONTAINS'),
        TierCode NVARCHAR(20) NOT NULL,
        SortOrder INT NULL,
        IsActive BIT NOT NULL
            CONSTRAINT DF_MaintenanceBrandTiers_Active DEFAULT (1),
        CreatedAt DATETIME2 NOT NULL
            CONSTRAINT DF_MaintenanceBrandTiers_CreatedAt DEFAULT SYSUTCDATETIME(),
        UpdatedAt DATETIME2 NOT NULL
            CONSTRAINT DF_MaintenanceBrandTiers_UpdatedAt DEFAULT SYSUTCDATETIME(),
        CONSTRAINT CK_MaintenanceBrandTiers_MatchType
            CHECK (MatchType IN ('EXACT', 'CONTAINS'))
    );

    CREATE INDEX IX_MaintenanceBrandTiers_Lookup
        ON dbo.MaintenanceBrandTiers(IsActive, SortOrder);
END;
GO

IF OBJECT_ID('dbo.MaintenanceProtocolTemplates', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.MaintenanceProtocolTemplates (
        ProtocolTemplateId INT IDENTITY(1,1) NOT NULL
            CONSTRAINT PK_MaintenanceProtocolTemplates PRIMARY KEY,
        TemplateCode NVARCHAR(50) NOT NULL,
        TemplateName NVARCHAR(150) NOT NULL,
        TemplateVersion INT NOT NULL
            CONSTRAINT DF_MaintenanceProtocolTemplates_Version DEFAULT (1),
        TemplateNote NVARCHAR(500) NULL,
        SourceConfigVersion NVARCHAR(50) NULL,
        IsActive BIT NOT NULL
            CONSTRAINT DF_MaintenanceProtocolTemplates_Active DEFAULT (1),
        CreatedAt DATETIME2 NOT NULL
            CONSTRAINT DF_MaintenanceProtocolTemplates_CreatedAt DEFAULT SYSUTCDATETIME(),
        UpdatedAt DATETIME2 NOT NULL
            CONSTRAINT DF_MaintenanceProtocolTemplates_UpdatedAt DEFAULT SYSUTCDATETIME(),
        CONSTRAINT UQ_MaintenanceProtocolTemplates_CodeVersion
            UNIQUE (TemplateCode, TemplateVersion)
    );
END;
GO

IF OBJECT_ID('dbo.MaintenanceProtocolCheckpoints', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.MaintenanceProtocolCheckpoints (
        ProtocolCheckpointId INT IDENTITY(1,1) NOT NULL
            CONSTRAINT PK_MaintenanceProtocolCheckpoints PRIMARY KEY,
        ProtocolTemplateId INT NOT NULL,
        CheckpointCode NVARCHAR(50) NOT NULL,
        CheckpointName NVARCHAR(300) NOT NULL,
        PromptText NVARCHAR(MAX) NULL,
        GuidanceText NVARCHAR(MAX) NULL,
        ReadingLabel NVARCHAR(150) NULL,
        ReadingFieldsJson NVARCHAR(MAX) NULL,
        DerivedReadingCode NVARCHAR(50) NULL,
        ReadingUnit NVARCHAR(30) NULL,
        PhotoPromptText NVARCHAR(300) NULL,
        RatingRequired BIT NOT NULL
            CONSTRAINT DF_MaintenanceProtocolCheckpoints_RatingRequired DEFAULT (1),
        SortOrder INT NULL,
        IsActive BIT NOT NULL
            CONSTRAINT DF_MaintenanceProtocolCheckpoints_Active DEFAULT (1),
        CreatedAt DATETIME2 NOT NULL
            CONSTRAINT DF_MaintenanceProtocolCheckpoints_CreatedAt DEFAULT SYSUTCDATETIME(),
        UpdatedAt DATETIME2 NOT NULL
            CONSTRAINT DF_MaintenanceProtocolCheckpoints_UpdatedAt DEFAULT SYSUTCDATETIME(),
        CONSTRAINT FK_MaintenanceProtocolCheckpoints_Templates
            FOREIGN KEY (ProtocolTemplateId)
            REFERENCES dbo.MaintenanceProtocolTemplates(ProtocolTemplateId),
        CONSTRAINT UQ_MaintenanceProtocolCheckpoints_Code
            UNIQUE (ProtocolTemplateId, CheckpointCode)
    );

    CREATE INDEX IX_MaintenanceProtocolCheckpoints_Template
        ON dbo.MaintenanceProtocolCheckpoints(ProtocolTemplateId, SortOrder);
END;
GO

/*
   Protocol assignment: which template applies to a given appliance.

   This is the SQL form of WILSON_PROTOCOL.resolveCheckpointSet() in
   plan-config.js. Resolution walks assignments in Precedence order and takes
   the first active match:

       Precedence 10  APPLIANCE_TYPE      matched on MaintenanceAssets.AssetTypeCode
       Precedence 20  CUSTOMER_CATEGORY   matched on MaintenanceAssets.CustomerCategoryCode

   MaintenanceAssets.CheckpointSetCode remains as the value captured at
   enrollment, but it is a snapshot, NOT the resolution input -- exactly as in
   the JS resolver. Assets created before v0.9.1 hold four known-wrong values
   (Ventilation as generic, Microwave as cooking, Washer and Dryer as laundry);
   resolving through these assignments corrects them with no data migration.
   IMUC group membership still wins over both scopes and is applied in code.
*/
IF OBJECT_ID('dbo.MaintenanceProtocolAssignments', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.MaintenanceProtocolAssignments (
        ProtocolAssignmentId INT IDENTITY(1,1) NOT NULL
            CONSTRAINT PK_MaintenanceProtocolAssignments PRIMARY KEY,
        AssignmentScope NVARCHAR(30) NOT NULL,
        ScopeCode NVARCHAR(50) NOT NULL,
        ScopeLabel NVARCHAR(150) NULL,
        TemplateCode NVARCHAR(50) NOT NULL,
        Precedence INT NOT NULL
            CONSTRAINT DF_MaintenanceProtocolAssignments_Precedence DEFAULT (20),
        IsActive BIT NOT NULL
            CONSTRAINT DF_MaintenanceProtocolAssignments_Active DEFAULT (1),
        CreatedAt DATETIME2 NOT NULL
            CONSTRAINT DF_MaintenanceProtocolAssignments_CreatedAt DEFAULT SYSUTCDATETIME(),
        UpdatedAt DATETIME2 NOT NULL
            CONSTRAINT DF_MaintenanceProtocolAssignments_UpdatedAt DEFAULT SYSUTCDATETIME(),
        CONSTRAINT UQ_MaintenanceProtocolAssignments_Scope
            UNIQUE (AssignmentScope, ScopeCode),
        CONSTRAINT CK_MaintenanceProtocolAssignments_Scope
            CHECK (AssignmentScope IN ('APPLIANCE_TYPE', 'CUSTOMER_CATEGORY'))
    );

    CREATE INDEX IX_MaintenanceProtocolAssignments_Resolve
        ON dbo.MaintenanceProtocolAssignments(IsActive, Precedence, ScopeCode);
END;
GO

IF OBJECT_ID('dbo.MaintenanceExpectedLifeRules', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.MaintenanceExpectedLifeRules (
        ExpectedLifeRuleId INT IDENTITY(1,1) NOT NULL
            CONSTRAINT PK_MaintenanceExpectedLifeRules PRIMARY KEY,
        TemplateCode NVARCHAR(50) NOT NULL,
        TierCode NVARCHAR(20) NOT NULL,
        ExpectedYears DECIMAL(5,1) NOT NULL,
        IsActive BIT NOT NULL
            CONSTRAINT DF_MaintenanceExpectedLifeRules_Active DEFAULT (1),
        CreatedAt DATETIME2 NOT NULL
            CONSTRAINT DF_MaintenanceExpectedLifeRules_CreatedAt DEFAULT SYSUTCDATETIME(),
        UpdatedAt DATETIME2 NOT NULL
            CONSTRAINT DF_MaintenanceExpectedLifeRules_UpdatedAt DEFAULT SYSUTCDATETIME(),
        CONSTRAINT UQ_MaintenanceExpectedLifeRules_Key
            UNIQUE (TemplateCode, TierCode)
    );
END;
GO

IF OBJECT_ID('dbo.MaintenanceLifecycleStages', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.MaintenanceLifecycleStages (
        LifecycleStageId INT IDENTITY(1,1) NOT NULL
            CONSTRAINT PK_MaintenanceLifecycleStages PRIMARY KEY,
        StageLabel NVARCHAR(50) NOT NULL
            CONSTRAINT UQ_MaintenanceLifecycleStages_Label UNIQUE,
        MaxAgeRatio DECIMAL(6,3) NOT NULL,
        SortOrder INT NULL,
        IsActive BIT NOT NULL
            CONSTRAINT DF_MaintenanceLifecycleStages_Active DEFAULT (1),
        CreatedAt DATETIME2 NOT NULL
            CONSTRAINT DF_MaintenanceLifecycleStages_CreatedAt DEFAULT SYSUTCDATETIME(),
        UpdatedAt DATETIME2 NOT NULL
            CONSTRAINT DF_MaintenanceLifecycleStages_UpdatedAt DEFAULT SYSUTCDATETIME()
    );
END;
GO

/* -------------------------------------------------------------------------
   7.3  Raw technician inspection data

   The field layer is the record of what the technician actually entered. It is
   append-and-correct, never overwritten by report generation: health reports
   are derived from it, so a report can be regenerated or revised without
   losing the underlying field facts (MERGE_GUIDE 7.3, 23).
   ------------------------------------------------------------------------- */
IF OBJECT_ID('dbo.MaintenanceFieldInspections', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.MaintenanceFieldInspections (
        FieldInspectionId INT IDENTITY(1,1) NOT NULL
            CONSTRAINT PK_MaintenanceFieldInspections PRIMARY KEY,
        VisitId INT NOT NULL,
        VisitAssetId INT NULL,
        HouseholdId INT NOT NULL,
        AssetId INT NOT NULL,

        /* Protocol version in force on the service date (MERGE_GUIDE 7.7). */
        ProtocolTemplateId INT NULL,
        ProtocolTemplateCodeSnapshot NVARCHAR(50) NULL,
        ProtocolTemplateVersionSnapshot INT NULL,

        /* Identity: the internal user id is authoritative, the name is a snapshot. */
        TechnicianUserId NVARCHAR(100) NULL,
        TechnicianDisplayNameSnapshot NVARCHAR(150) NULL,

        InspectionStatus NVARCHAR(40) NOT NULL
            CONSTRAINT DF_MaintenanceFieldInspections_Status DEFAULT ('NOT_STARTED'),
        StartedAt DATETIME2 NULL,
        CompletedAt DATETIME2 NULL,

        /* Lifecycle context captured in the field. */
        ApproxAgeYears DECIMAL(5,1) NULL,
        LifecycleTierCode NVARCHAR(20) NULL,
        ExpectedLifeYears DECIMAL(5,1) NULL,
        LifecycleStage NVARCHAR(50) NULL,

        /* Scoring. 75% condition / 25% lifecycle -- see reportScoring in plan-config.js. */
        ConditionScore DECIMAL(6,2) NULL,
        LifecycleScore DECIMAL(6,2) NULL,
        FinalHealthScore DECIMAL(6,2) NULL,
        GradeLabel NVARCHAR(10) NULL,

        SerialTagPhotoStorageKey NVARCHAR(500) NULL,
        TechnicianSummary NVARCHAR(MAX) NULL,
        FollowUpRequired BIT NOT NULL
            CONSTRAINT DF_MaintenanceFieldInspections_FollowUp DEFAULT (0),

        CreatedAt DATETIME2 NOT NULL
            CONSTRAINT DF_MaintenanceFieldInspections_CreatedAt DEFAULT SYSUTCDATETIME(),
        UpdatedAt DATETIME2 NOT NULL
            CONSTRAINT DF_MaintenanceFieldInspections_UpdatedAt DEFAULT SYSUTCDATETIME(),
        VersionStamp ROWVERSION,

        CONSTRAINT FK_MaintenanceFieldInspections_Visits
            FOREIGN KEY (VisitId) REFERENCES dbo.MaintenanceVisits(VisitId),
        CONSTRAINT FK_MaintenanceFieldInspections_VisitAssets
            FOREIGN KEY (VisitAssetId) REFERENCES dbo.MaintenanceVisitAssets(VisitAssetId),
        CONSTRAINT FK_MaintenanceFieldInspections_Households
            FOREIGN KEY (HouseholdId) REFERENCES dbo.MaintenanceHouseholds(HouseholdId),
        CONSTRAINT FK_MaintenanceFieldInspections_Assets
            FOREIGN KEY (AssetId) REFERENCES dbo.MaintenanceAssets(AssetId),
        CONSTRAINT FK_MaintenanceFieldInspections_Templates
            FOREIGN KEY (ProtocolTemplateId)
            REFERENCES dbo.MaintenanceProtocolTemplates(ProtocolTemplateId),

        /* MERGE_GUIDE 7.3 status vocabulary. */
        CONSTRAINT CK_MaintenanceFieldInspections_Status
            CHECK (InspectionStatus IN (
                'NOT_STARTED', 'IN_PROGRESS', 'FIELD_COMPLETE', 'REPORT_GENERATED'
            )),
        CONSTRAINT CK_MaintenanceFieldInspections_Score
            CHECK (FinalHealthScore IS NULL OR FinalHealthScore BETWEEN 0 AND 100),

        /* One live inspection per asset per visit. */
        CONSTRAINT UQ_MaintenanceFieldInspections_VisitAsset
            UNIQUE (VisitId, AssetId)
    );

    CREATE INDEX IX_MaintenanceFieldInspections_Visit
        ON dbo.MaintenanceFieldInspections(VisitId, InspectionStatus);

    CREATE INDEX IX_MaintenanceFieldInspections_Asset
        ON dbo.MaintenanceFieldInspections(AssetId, CompletedAt DESC);

    CREATE INDEX IX_MaintenanceFieldInspections_Technician
        ON dbo.MaintenanceFieldInspections(TechnicianUserId, CompletedAt DESC);
END;
GO

IF OBJECT_ID('dbo.MaintenanceFieldInspectionChecks', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.MaintenanceFieldInspectionChecks (
        FieldInspectionCheckId INT IDENTITY(1,1) NOT NULL
            CONSTRAINT PK_MaintenanceFieldInspectionChecks PRIMARY KEY,
        FieldInspectionId INT NOT NULL,
        CheckpointCode NVARCHAR(50) NOT NULL,

        /* Wording as shown to the technician on the service date. Never a live
           join to MaintenanceProtocolCheckpoints -- protocol text changes. */
        CheckpointLabelSnapshot NVARCHAR(300) NULL,

        Performed BIT NOT NULL
            CONSTRAINT DF_MaintenanceFieldInspectionChecks_Performed DEFAULT (0),
        Rating TINYINT NULL,
        StatusLabel NVARCHAR(20) NULL,
        ObservedValue NVARCHAR(150) NULL,
        ObservedUnit NVARCHAR(30) NULL,
        TargetText NVARCHAR(300) NULL,
        ReadingJson NVARCHAR(MAX) NULL,
        TechnicianNote NVARCHAR(MAX) NULL,
        PhotoCount INT NOT NULL
            CONSTRAINT DF_MaintenanceFieldInspectionChecks_PhotoCount DEFAULT (0),
        SortOrder INT NULL,
        CompletedAt DATETIME2 NULL,
        CreatedAt DATETIME2 NOT NULL
            CONSTRAINT DF_MaintenanceFieldInspectionChecks_CreatedAt DEFAULT SYSUTCDATETIME(),
        UpdatedAt DATETIME2 NOT NULL
            CONSTRAINT DF_MaintenanceFieldInspectionChecks_UpdatedAt DEFAULT SYSUTCDATETIME(),

        CONSTRAINT FK_MaintenanceFieldInspectionChecks_Inspections
            FOREIGN KEY (FieldInspectionId)
            REFERENCES dbo.MaintenanceFieldInspections(FieldInspectionId),

        /* Five tap buttons in the field tool, not a slider. */
        CONSTRAINT CK_MaintenanceFieldInspectionChecks_Rating
            CHECK (Rating IS NULL OR Rating BETWEEN 1 AND 5),
        CONSTRAINT CK_MaintenanceFieldInspectionChecks_Status
            CHECK (StatusLabel IS NULL OR StatusLabel IN ('PASS', 'MONITOR', 'ACTION')),
        CONSTRAINT UQ_MaintenanceFieldInspectionChecks_Code
            UNIQUE (FieldInspectionId, CheckpointCode)
    );

    CREATE INDEX IX_MaintenanceFieldInspectionChecks_Inspection
        ON dbo.MaintenanceFieldInspectionChecks(FieldInspectionId, SortOrder);
END;
GO

IF OBJECT_ID('dbo.MaintenanceFieldInspectionPhotos', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.MaintenanceFieldInspectionPhotos (
        FieldInspectionPhotoId INT IDENTITY(1,1) NOT NULL
            CONSTRAINT PK_MaintenanceFieldInspectionPhotos PRIMARY KEY,
        FieldInspectionId INT NOT NULL,
        FieldInspectionCheckId INT NULL,
        PhotoKind NVARCHAR(30) NOT NULL
            CONSTRAINT DF_MaintenanceFieldInspectionPhotos_Kind DEFAULT ('CHECKPOINT'),
        StorageKey NVARCHAR(500) NOT NULL,
        ContentType NVARCHAR(100) NULL,
        ByteSize BIGINT NULL,
        Caption NVARCHAR(300) NULL,
        CapturedAt DATETIME2 NULL,
        IncludeInReport BIT NOT NULL
            CONSTRAINT DF_MaintenanceFieldInspectionPhotos_Include DEFAULT (1),
        SortOrder INT NULL,
        CreatedAt DATETIME2 NOT NULL
            CONSTRAINT DF_MaintenanceFieldInspectionPhotos_CreatedAt DEFAULT SYSUTCDATETIME(),

        CONSTRAINT FK_MaintenanceFieldInspectionPhotos_Inspections
            FOREIGN KEY (FieldInspectionId)
            REFERENCES dbo.MaintenanceFieldInspections(FieldInspectionId),
        CONSTRAINT FK_MaintenanceFieldInspectionPhotos_Checks
            FOREIGN KEY (FieldInspectionCheckId)
            REFERENCES dbo.MaintenanceFieldInspectionChecks(FieldInspectionCheckId),
        CONSTRAINT CK_MaintenanceFieldInspectionPhotos_Kind
            CHECK (PhotoKind IN ('SERIAL_TAG', 'CHECKPOINT', 'BEFORE', 'AFTER', 'OTHER'))
    );

    CREATE INDEX IX_MaintenanceFieldInspectionPhotos_Inspection
        ON dbo.MaintenanceFieldInspectionPhotos(FieldInspectionId, SortOrder);
END;
GO

/* Link a generated report back to the field inspection it came from. Nullable:
   pre-v0.7 reports were built in the office and have no field inspection. */
IF COL_LENGTH('dbo.MaintenanceHealthReports', 'FieldInspectionId') IS NULL
    ALTER TABLE dbo.MaintenanceHealthReports ADD FieldInspectionId INT NULL;
GO
IF OBJECT_ID('dbo.FK_MaintenanceHealthReports_FieldInspections', 'F') IS NULL
    ALTER TABLE dbo.MaintenanceHealthReports
        ADD CONSTRAINT FK_MaintenanceHealthReports_FieldInspections
        FOREIGN KEY (FieldInspectionId)
        REFERENCES dbo.MaintenanceFieldInspections(FieldInspectionId);
GO

/* -------------------------------------------------------------------------
   7.4  Report delivery tracking

   Append-only per send attempt, so resend history survives (MERGE_GUIDE 7.4).
   ------------------------------------------------------------------------- */
IF OBJECT_ID('dbo.MaintenanceReportDeliveries', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.MaintenanceReportDeliveries (
        ReportDeliveryId INT IDENTITY(1,1) NOT NULL
            CONSTRAINT PK_MaintenanceReportDeliveries PRIMARY KEY,
        HealthReportId INT NOT NULL,
        HouseholdId INT NOT NULL,
        RecipientEmail NVARCHAR(255) NOT NULL,
        RecipientName NVARCHAR(150) NULL,
        DeliveryStatus NVARCHAR(30) NOT NULL
            CONSTRAINT DF_MaintenanceReportDeliveries_Status DEFAULT ('READY'),
        ProviderName NVARCHAR(50) NULL,
        ProviderMessageId NVARCHAR(200) NULL,
        QueuedAt DATETIME2 NULL,
        SentAt DATETIME2 NULL,
        FailedAt DATETIME2 NULL,
        FailureReason NVARCHAR(1000) NULL,
        AttemptCount INT NOT NULL
            CONSTRAINT DF_MaintenanceReportDeliveries_Attempts DEFAULT (0),
        ReportRevisionNumber INT NULL,
        CreatedByUserId NVARCHAR(100) NULL,
        CreatedAt DATETIME2 NOT NULL
            CONSTRAINT DF_MaintenanceReportDeliveries_CreatedAt DEFAULT SYSUTCDATETIME(),
        UpdatedAt DATETIME2 NOT NULL
            CONSTRAINT DF_MaintenanceReportDeliveries_UpdatedAt DEFAULT SYSUTCDATETIME(),
        VersionStamp ROWVERSION,

        CONSTRAINT FK_MaintenanceReportDeliveries_Reports
            FOREIGN KEY (HealthReportId)
            REFERENCES dbo.MaintenanceHealthReports(HealthReportId),
        CONSTRAINT FK_MaintenanceReportDeliveries_Households
            FOREIGN KEY (HouseholdId) REFERENCES dbo.MaintenanceHouseholds(HouseholdId),
        CONSTRAINT CK_MaintenanceReportDeliveries_Status
            CHECK (DeliveryStatus IN ('READY', 'QUEUED', 'SENT', 'FAILED'))
    );

    CREATE INDEX IX_MaintenanceReportDeliveries_Report
        ON dbo.MaintenanceReportDeliveries(HealthReportId, CreatedAt DESC);

    CREATE INDEX IX_MaintenanceReportDeliveries_Queue
        ON dbo.MaintenanceReportDeliveries(DeliveryStatus, QueuedAt);
END;
GO

/* -------------------------------------------------------------------------
   7.5  Technician assignment / authenticated user

   Display names are snapshots for historical reporting; the internal user id is
   the authoritative identity (MERGE_GUIDE 7.5, 12).
   ------------------------------------------------------------------------- */
IF COL_LENGTH('dbo.MaintenanceVisits', 'AssignedTechnicianUserId') IS NULL
    ALTER TABLE dbo.MaintenanceVisits ADD AssignedTechnicianUserId NVARCHAR(100) NULL;
GO
IF COL_LENGTH('dbo.MaintenanceVisits', 'AssignedTechnicianNameSnapshot') IS NULL
    ALTER TABLE dbo.MaintenanceVisits ADD AssignedTechnicianNameSnapshot NVARCHAR(150) NULL;
GO
IF COL_LENGTH('dbo.MaintenanceVisits', 'StartedByUserId') IS NULL
    ALTER TABLE dbo.MaintenanceVisits ADD StartedByUserId NVARCHAR(100) NULL;
GO
IF COL_LENGTH('dbo.MaintenanceVisits', 'CompletedByUserId') IS NULL
    ALTER TABLE dbo.MaintenanceVisits ADD CompletedByUserId NVARCHAR(100) NULL;
GO
IF COL_LENGTH('dbo.MaintenanceVisits', 'FieldStartedAt') IS NULL
    ALTER TABLE dbo.MaintenanceVisits ADD FieldStartedAt DATETIME2 NULL;
GO
IF NOT EXISTS (
    SELECT 1 FROM sys.indexes
    WHERE name = 'IX_MaintenanceVisits_Technician'
      AND object_id = OBJECT_ID('dbo.MaintenanceVisits')
)
    CREATE INDEX IX_MaintenanceVisits_Technician
        ON dbo.MaintenanceVisits(AssignedTechnicianUserId, DueDate);
GO

/* -------------------------------------------------------------------------
   7.7  Protocol templates (seeded from plan-config.js)
   ------------------------------------------------------------------------- */
MERGE dbo.MaintenanceProtocolTemplates AS target
USING (VALUES
    (N'generic', N'Generic protocol', 1, N'3 checkpoints. Seeded from plan-config.js v0.6.', N'0.6', 1),
    (N'refrigerator', N'Refrigerator protocol', 1, N'5 checkpoints. Seeded from plan-config.js v0.6.', N'0.6', 1),
    (N'dishwasher', N'Dishwasher protocol', 1, N'5 checkpoints. Seeded from plan-config.js v0.6.', N'0.6', 1),
    (N'cooking', N'Cooking protocol', 1, N'4 checkpoints. Seeded from plan-config.js v0.6.', N'0.6', 1),
    (N'icemaker', N'Icemaker protocol', 1, N'5 checkpoints. Seeded from plan-config.js v0.6.', N'0.6', 1),
    (N'washer', N'Washer protocol', 1, N'5 checkpoints. Seeded from plan-config.js v0.6.', N'0.6', 1),
    (N'laundry', N'Laundry protocol', 1, N'5 checkpoints. Seeded from plan-config.js v0.6.', N'0.6', 1),
    (N'dryer', N'Dryer protocol', 1, N'5 checkpoints. Seeded from plan-config.js v0.6.', N'0.6', 1),
    (N'ventilation', N'Ventilation protocol', 1, N'5 checkpoints. Seeded from plan-config.js v0.6.', N'0.6', 1),
    (N'microwave', N'Microwave protocol', 1, N'5 checkpoints. Seeded from plan-config.js v0.6.', N'0.6', 1)
) AS source (TemplateCode, TemplateName, TemplateVersion, TemplateNote, SourceConfigVersion, IsActive)
ON target.TemplateCode = source.TemplateCode AND target.TemplateVersion = source.TemplateVersion
WHEN MATCHED THEN UPDATE SET
    TemplateName = source.TemplateName,
    TemplateNote = source.TemplateNote,
    SourceConfigVersion = source.SourceConfigVersion,
    IsActive = source.IsActive,
    UpdatedAt = SYSUTCDATETIME()
WHEN NOT MATCHED THEN INSERT (
    TemplateCode, TemplateName, TemplateVersion, TemplateNote, SourceConfigVersion, IsActive
) VALUES (
    source.TemplateCode, source.TemplateName, source.TemplateVersion, source.TemplateNote, source.SourceConfigVersion, source.IsActive
);
GO

MERGE dbo.MaintenanceProtocolCheckpoints AS target
USING (
    SELECT
        t.ProtocolTemplateId,
        source.CheckpointCode,
        source.CheckpointName,
        source.PromptText,
        source.GuidanceText,
        source.ReadingLabel,
        source.ReadingFieldsJson,
        source.DerivedReadingCode,
        source.ReadingUnit,
        source.PhotoPromptText,
        source.RatingRequired,
        source.SortOrder,
        source.IsActive
    FROM (VALUES
        (N'generic', 1, N'condition', N'Overall condition & operation', N'Run the unit and confirm normal operation, controls, and visible condition.', NULL, N'Reading / result', NULL, NULL, NULL, N'Serial tag or condition photo', 1, 10, 1),
        (N'generic', 1, N'connections', N'Connections & safety', N'Inspect visible utility connections and note any safety concern.', NULL, N'Observation', NULL, NULL, NULL, N'Photo if any issue is found', 1, 20, 1),
        (N'generic', 1, N'cleanliness', N'Maintenance condition', N'Check accessible filters, screens, vents, and serviceable buildup.', NULL, N'Condition', NULL, NULL, NULL, N'Before / after photo when cleaned', 1, 30, 1),
        (N'refrigerator', 1, N'temp', N'Compartment temperature performance', N'Measure each active refrigerated compartment and compare the actual temperature with its set point. Confirm normal ice production when the appliance makes ice.', N'Typical targets: fresh-food compartments about 35–38°F; freezer compartments close to 0°F. Specialty refrigeration should be compared with its actual set point and intended use.', NULL, N'[{"key":"primaryActual","label":"Primary compartment actual","unit":"°F","required":true,"placeholder":"Actual temp"},{"key":"primarySetpoint","label":"Primary set point","unit":"°F","required":true,"placeholder":"Set point"},{"key":"secondaryActual","label":"Second compartment actual","unit":"°F","required":false,"placeholder":"If applicable"},{"key":"secondarySetpoint","label":"Second set point","unit":"°F","required":false,"placeholder":"If applicable"}]', NULL, NULL, N'Add a display / temperature photo if useful', 1, 10, 1),
        (N'refrigerator', 1, N'frost_pattern', N'Evaporator frost pattern', N'Inspect the accessible evaporator pattern. Rate how evenly the active coil is frosting and look for an isolated ice ball, oil residue, or another visible leak indicator.', N'A healthy evaporator should show a consistent frost pattern across the active coil with no isolated ice ball or obvious oil / leak indicator.', N'Pattern / observation', NULL, NULL, NULL, N'Add a frost-pattern photo if useful', 1, 20, 1),
        (N'refrigerator', 1, N'condenser_temp', N'Condenser temperature & coil service', N'Measure room ambient and condenser-coil surface temperature with an infrared thermometer. Vacuum the accessible condenser coil, then rate heat rejection / coil condition after service.', N'Normal reference: condenser surface temperature is commonly about 15–30°F above room ambient. The coil should feel warm or hot, but surface temperature is typically below roughly 110–120°F. Use manufacturer guidance when available.', NULL, N'[{"key":"ambient","label":"Room ambient","unit":"°F","required":true,"placeholder":"Ambient temp"},{"key":"coilSurface","label":"Condenser coil surface","unit":"°F","required":true,"placeholder":"IR temp"}]', N'condenserTd', NULL, N'Add condenser / coil photo if useful', 1, 30, 1),
        (N'refrigerator', 1, N'components', N'Components & operating sound', N'Force accessible operating components to run as appropriate—compressor, fans, dampers and ice-making components—and listen for abnormal noise, vibration, or cycling.', NULL, N'Component test result', NULL, NULL, NULL, N'Add a component photo only if useful', 1, 40, 1),
        (N'refrigerator', 1, N'air_filter', N'Airflow & filter status', N'Confirm fans are running and airflow supports the observed frost pattern. Inspect applicable water / air filters. Replace and reset filters when Wilson Filter Service is selected or included by the plan.', N'Airflow is interpreted together with fan operation and frost pattern. If filter service is not enrolled, inspect and document the filter condition and recommend replacement when needed.', N'Airflow / filter result', NULL, NULL, NULL, N'Add a filter or airflow photo if useful', 1, 50, 1),
        (N'dishwasher', 1, N'leak', N'Seals & leak check', N'Inspect door seals, visible connections, and the base area for leakage.', NULL, N'Leak result', NULL, NULL, NULL, N'Seal / leak area if abnormal', 1, 10, 1),
        (N'dishwasher', 1, N'filter', N'Filter & sump condition', N'Inspect and clean the accessible filter/sump area.', NULL, N'Condition after cleaning', NULL, NULL, NULL, N'Filter / sump after cleaning', 1, 20, 1),
        (N'dishwasher', 1, N'codes', N'Stored codes & controls', N'Check stored faults or service indicators when available.', NULL, N'Codes / result', NULL, NULL, NULL, N'Display if a code is present', 1, 30, 1),
        (N'dishwasher', 1, N'test', N'Test cycle & operating sound', N'Run a test cycle and note fill, wash, drain, heat, and unusual sound.', NULL, N'Cycle result', NULL, NULL, NULL, N'Photo if an issue is visible', 1, 40, 1),
        (N'dishwasher', 1, N'clean', N'Maintenance clean cycle', N'Complete or initiate the approved maintenance-cleaning process.', NULL, N'Completed / product used', NULL, NULL, NULL, N'Interior after cleaning', 1, 50, 1),
        (N'cooking', 1, N'seal', N'Door seals & condition', N'Inspect oven door seals, hinges, and visible cooking surfaces.', NULL, N'Seal condition', NULL, NULL, NULL, N'Seal / cavity photo if abnormal', 1, 10, 1),
        (N'cooking', 1, N'heat', N'Burner / element / flame test', N'Verify ignition, element operation, or flame pattern as applicable.', NULL, N'Test result', NULL, NULL, NULL, N'Flame or element photo when useful', 1, 20, 1),
        (N'cooking', 1, N'accuracy', N'Temperature accuracy', N'For ovens, compare measured temperature with the set point after stabilization.', NULL, N'Actual temp / set point', NULL, NULL, N'°F', N'Temperature reading', 1, 30, 1),
        (N'cooking', 1, N'controls', N'Controls & safety operation', N'Verify controls, fans, lights, and obvious safety functions.', NULL, N'Operation result', NULL, NULL, NULL, N'Photo if an issue is present', 1, 40, 1),
        (N'icemaker', 1, N'pattern', N'Ice pattern & production', N'Inspect cube/slab/nugget formation and note abnormal pattern or production.', NULL, N'Pattern / production', NULL, NULL, NULL, N'Fresh ice pattern', 1, 10, 1),
        (N'icemaker', 1, N'bin', N'Bin condition & cleaning', N'Clean and document the bin and accessible food-contact surfaces.', NULL, N'Condition after cleaning', NULL, NULL, NULL, N'Bin after cleaning', 1, 20, 1),
        (N'icemaker', 1, N'clean_cycle', N'Cleaning / descale cycle', N'Run the manufacturer-approved cleaning or descale cycle.', NULL, N'Cycle completed / product', NULL, NULL, NULL, N'Display or interior after cycle', 1, 30, 1),
        (N'icemaker', 1, N'condenser', N'Condenser & airflow', N'Inspect and vacuum the accessible condenser; note abnormal fan/compressor sound.', NULL, N'Condition / sound', NULL, NULL, NULL, N'Condenser after vacuuming', 1, 40, 1),
        (N'icemaker', 1, N'water_drain', N'Water, drain & filter', N'Inspect water connection, drain/pump operation, and filter status.', NULL, N'Flow / drain / filter result', NULL, NULL, NULL, N'Water connection, drain, or filter', 1, 50, 1),
        (N'washer', 1, N'water', N'Hoses, fill & leak check', N'Inspect visible hoses/connections and verify normal fill with no leaks.', NULL, N'Fill / leak result', NULL, NULL, NULL, N'Connections if abnormal', 1, 10, 1),
        (N'washer', 1, N'drain', N'Drain performance', N'Verify drain/pump operation and note restriction or abnormal pump sound.', NULL, N'Drain result', NULL, NULL, NULL, N'Pump/filter area when applicable', 1, 20, 1),
        (N'washer', 1, N'mechanical', N'Wash / spin & vibration', N'Run a functional cycle and rate agitation/tumble, spin, balance, and noise.', NULL, N'Cycle / vibration result', NULL, NULL, NULL, N'Photo if movement or damage is visible', 1, 30, 1),
        (N'washer', 1, N'clean', N'Gasket, filter & cleaning condition', N'Inspect door boot/gasket, accessible filter, dispenser, and maintenance-cleaning condition.', NULL, N'Condition after service', NULL, NULL, NULL, N'Gasket/filter after cleaning', 1, 40, 1),
        (N'washer', 1, N'codes', N'Stored codes & controls', N'Check stored faults/service indicators and verify control operation.', NULL, N'Codes / result', NULL, NULL, NULL, N'Display if a code is present', 1, 50, 1),
        (N'laundry', 1, N'water_air', N'Utility / airflow performance', N'Verify normal fill/drain or exhaust airflow as applicable.', NULL, N'Result / reading', NULL, NULL, NULL, N'Connection or vent if abnormal', 1, 10, 1),
        (N'laundry', 1, N'cycle', N'Cycle operation', N'Run a functional cycle and note abnormal sound, vibration, heat, or movement.', NULL, N'Cycle result', NULL, NULL, NULL, N'Photo if issue is visible', 1, 20, 1),
        (N'laundry', 1, N'clean', N'Accessible cleaning condition', N'Inspect accessible filters, lint areas, gasket, dispenser, or service points.', NULL, N'Condition after service', NULL, NULL, NULL, N'After-cleaning photo', 1, 30, 1),
        (N'laundry', 1, N'connections', N'Connections & leak / safety check', N'Inspect visible water, vent, gas, or electrical connections.', NULL, N'Connection result', NULL, NULL, NULL, N'Connection if abnormal', 1, 40, 1),
        (N'laundry', 1, N'codes', N'Controls & stored codes', N'Verify controls and note stored faults/service indicators when available.', NULL, N'Codes / result', NULL, NULL, NULL, N'Display if a code is present', 1, 50, 1),
        (N'dryer', 1, N'airflow', N'Exhaust airflow & temperature', N'Verify exhaust airflow and record outlet temperature or observed heat performance.', NULL, N'Temp / airflow', NULL, NULL, N'°F', N'Vent connection or reading', 1, 10, 1),
        (N'dryer', 1, N'lint', N'Lint system & accessible cleaning', N'Inspect and clean the lint screen, housing, and accessible lint buildup.', NULL, N'Condition after cleaning', NULL, NULL, NULL, N'Lint area after cleaning', 1, 20, 1),
        (N'dryer', 1, N'mechanical', N'Drum, rollers & operating sound', N'Run the dryer and note abnormal drum, roller, blower, or motor sound.', NULL, N'Operating result', NULL, NULL, NULL, N'Photo if wear/damage is visible', 1, 30, 1),
        (N'dryer', 1, N'sensor', N'Cycle / moisture-sensor operation', N'Verify controls and a timed or sensor cycle as applicable.', NULL, N'Cycle result', NULL, NULL, NULL, N'Display if abnormal', 1, 40, 1),
        (N'dryer', 1, N'connection', N'Vent & utility connection', N'Inspect visible venting and gas/electrical connection condition.', NULL, N'Connection condition', NULL, NULL, NULL, N'Vent / connection if abnormal', 1, 50, 1),
        (N'ventilation', 1, N'capture', N'Blower & capture performance', N'Run each speed and verify normal airflow/capture.', NULL, N'Airflow / speed result', NULL, NULL, NULL, N'Operating hood / capture area', 1, 10, 1),
        (N'ventilation', 1, N'filters', N'Filters / baffles', N'Inspect and clean accessible filters or baffles.', NULL, N'Condition after cleaning', NULL, NULL, NULL, N'Filters after cleaning', 1, 20, 1),
        (N'ventilation', 1, N'noise', N'Blower sound & vibration', N'Listen for abnormal blower noise, vibration, or bearing sound.', NULL, N'Sound / vibration result', NULL, NULL, NULL, N'Blower area if issue visible', 1, 30, 1),
        (N'ventilation', 1, N'controls', N'Controls, lights & heat sensor', N'Verify controls, lighting, and automatic heat response when equipped.', NULL, N'Control result', NULL, NULL, NULL, N'Control panel if abnormal', 1, 40, 1),
        (N'ventilation', 1, N'grease', N'Grease / duct-entry condition', N'Inspect accessible grease accumulation and the visible duct-entry area.', NULL, N'Condition', NULL, NULL, NULL, N'Baffle / duct-entry condition', 1, 50, 1),
        (N'microwave', 1, N'door', N'Door, seal & interlock', N'Inspect the door/seal and verify interlock operation.', NULL, N'Door / interlock result', NULL, NULL, NULL, N'Door/seal if abnormal', 1, 10, 1),
        (N'microwave', 1, N'heat', N'Heating performance', N'Run a controlled heating test and record the result or temperature rise.', NULL, N'Heating result / temp rise', NULL, NULL, N'°F', N'Test reading if used', 1, 20, 1),
        (N'microwave', 1, N'air', N'Turntable, fan & airflow', N'Verify turntable/stirrer, cooling fan, and ventilation operation as applicable.', NULL, N'Operation result', NULL, NULL, NULL, N'Photo if abnormal', 1, 30, 1),
        (N'microwave', 1, N'controls', N'Controls & stored faults', N'Verify keypad/display operation and note any stored error or service indication.', NULL, N'Codes / result', NULL, NULL, NULL, N'Display if a code is present', 1, 40, 1),
        (N'microwave', 1, N'cavity', N'Interior / arcing condition', N'Inspect the cavity, waveguide cover, rack, and signs of arcing or damage.', NULL, N'Cavity condition', NULL, NULL, NULL, N'Interior if abnormal', 1, 50, 1)
    ) AS source (TemplateCode, TemplateVersion, CheckpointCode, CheckpointName, PromptText, GuidanceText, ReadingLabel, ReadingFieldsJson, DerivedReadingCode, ReadingUnit, PhotoPromptText, RatingRequired, SortOrder, IsActive)
    INNER JOIN dbo.MaintenanceProtocolTemplates t
        ON t.TemplateCode = source.TemplateCode
       AND t.TemplateVersion = source.TemplateVersion
) AS source
ON target.ProtocolTemplateId = source.ProtocolTemplateId
   AND target.CheckpointCode = source.CheckpointCode
WHEN MATCHED THEN UPDATE SET
    CheckpointName = source.CheckpointName,
    PromptText = source.PromptText,
    GuidanceText = source.GuidanceText,
    ReadingLabel = source.ReadingLabel,
    ReadingFieldsJson = source.ReadingFieldsJson,
    DerivedReadingCode = source.DerivedReadingCode,
    ReadingUnit = source.ReadingUnit,
    PhotoPromptText = source.PhotoPromptText,
    RatingRequired = source.RatingRequired,
    SortOrder = source.SortOrder,
    IsActive = source.IsActive,
    UpdatedAt = SYSUTCDATETIME()
WHEN NOT MATCHED THEN INSERT (
    ProtocolTemplateId, CheckpointCode, CheckpointName, PromptText, GuidanceText,
    ReadingLabel, ReadingFieldsJson, DerivedReadingCode, ReadingUnit,
    PhotoPromptText, RatingRequired, SortOrder, IsActive
) VALUES (
    source.ProtocolTemplateId, source.CheckpointCode, source.CheckpointName,
    source.PromptText, source.GuidanceText, source.ReadingLabel,
    source.ReadingFieldsJson, source.DerivedReadingCode, source.ReadingUnit,
    source.PhotoPromptText, source.RatingRequired, source.SortOrder, source.IsActive
);
GO

MERGE dbo.MaintenanceProtocolAssignments AS target
USING (VALUES
    (N'APPLIANCE_TYPE', N'refrigerator', N'Refrigerator', N'refrigerator', 10, 1),
    (N'APPLIANCE_TYPE', N'freezer', N'Freezer', N'refrigerator', 10, 1),
    (N'APPLIANCE_TYPE', N'wine_beverage', N'Wine / Beverage Center', N'refrigerator', 10, 1),
    (N'APPLIANCE_TYPE', N'ice_maker', N'Icemaker (IMUC)', N'icemaker', 10, 1),
    (N'APPLIANCE_TYPE', N'dishwasher', N'Dishwasher', N'dishwasher', 10, 1),
    (N'APPLIANCE_TYPE', N'range', N'Range', N'cooking', 10, 1),
    (N'APPLIANCE_TYPE', N'cooktop', N'Cooktop / Rangetop', N'cooking', 10, 1),
    (N'APPLIANCE_TYPE', N'wall_oven', N'Wall Oven', N'cooking', 10, 1),
    (N'APPLIANCE_TYPE', N'speed_oven', N'Microwave / Speed Oven', N'microwave', 10, 1),
    (N'APPLIANCE_TYPE', N'washer', N'Washer', N'washer', 10, 1),
    (N'APPLIANCE_TYPE', N'dryer', N'Dryer', N'dryer', 10, 1),
    (N'APPLIANCE_TYPE', N'hood', N'Vent Hood', N'ventilation', 10, 1),
    (N'APPLIANCE_TYPE', N'hood_insert', N'Hood Insert / Liner', N'ventilation', 10, 1),
    (N'APPLIANCE_TYPE', N'warming_drawer', N'Warming Drawer', N'cooking', 10, 1),
    (N'APPLIANCE_TYPE', N'coffee_maker', N'Built-In Coffee Maker', N'generic', 10, 1),
    (N'APPLIANCE_TYPE', N'laundry_center', N'Laundry Center / WashTower', N'laundry', 10, 1),
    (N'APPLIANCE_TYPE', N'commercial_refrigeration', N'Commercial / Specialty Refrigeration', N'refrigerator', 10, 1),
    (N'APPLIANCE_TYPE', N'outdoor', N'Outdoor Appliance', N'generic', 10, 1),
    (N'APPLIANCE_TYPE', N'other', N'Other Appliance', N'generic', 10, 1),
    (N'CUSTOMER_CATEGORY', N'refrigeration', N'Refrigeration', N'refrigerator', 20, 1),
    (N'CUSTOMER_CATEGORY', N'ice_maker', N'Icemaker', N'icemaker', 20, 1),
    (N'CUSTOMER_CATEGORY', N'cooktop', N'Cooktop / Rangetop', N'cooking', 20, 1),
    (N'CUSTOMER_CATEGORY', N'range', N'Range', N'cooking', 20, 1),
    (N'CUSTOMER_CATEGORY', N'dishwasher', N'Dishwasher', N'dishwasher', 20, 1),
    (N'CUSTOMER_CATEGORY', N'ventilation', N'Ventilation', N'ventilation', 20, 1),
    (N'CUSTOMER_CATEGORY', N'microwave', N'Microwave', N'microwave', 20, 1),
    (N'CUSTOMER_CATEGORY', N'ovens', N'Ovens', N'cooking', 20, 1),
    (N'CUSTOMER_CATEGORY', N'warming_drawer', N'Warming Drawer', N'cooking', 20, 1),
    (N'CUSTOMER_CATEGORY', N'coffee', N'Built-In Coffee', N'generic', 20, 1),
    (N'CUSTOMER_CATEGORY', N'washer', N'Washer', N'washer', 20, 1),
    (N'CUSTOMER_CATEGORY', N'dryer', N'Dryer', N'dryer', 20, 1)
) AS source (AssignmentScope, ScopeCode, ScopeLabel, TemplateCode, Precedence, IsActive)
ON target.AssignmentScope = source.AssignmentScope AND target.ScopeCode = source.ScopeCode
WHEN MATCHED THEN UPDATE SET
    ScopeLabel = source.ScopeLabel,
    TemplateCode = source.TemplateCode,
    Precedence = source.Precedence,
    IsActive = source.IsActive,
    UpdatedAt = SYSUTCDATETIME()
WHEN NOT MATCHED THEN INSERT (
    AssignmentScope, ScopeCode, ScopeLabel, TemplateCode, Precedence, IsActive
) VALUES (
    source.AssignmentScope, source.ScopeCode, source.ScopeLabel, source.TemplateCode, source.Precedence, source.IsActive
);
GO

/* -------------------------------------------------------------------------
   7.6  Lifecycle configuration (seeded from plan-config.js)
   ------------------------------------------------------------------------- */
MERGE dbo.MaintenanceLifecycleTiers AS target
USING (VALUES
    (N'luxury', N'Luxury', 15, N'Sub-Zero, Wolf, Cove, Miele, Thermador, True', 1),
    (N'premium', N'Mass premium', 10, N'Bosch, KitchenAid, Monogram, Café, Fisher & Paykel, JennAir', 1),
    (N'mass', N'Mass', 8, N'Whirlpool, Maytag, LG mainstream, GE mainstream, Samsung', 1)
) AS source (TierCode, TierLabel, DefaultExpectedYears, ExampleBrands, IsActive)
ON target.TierCode = source.TierCode
WHEN MATCHED THEN UPDATE SET
    TierLabel = source.TierLabel,
    DefaultExpectedYears = source.DefaultExpectedYears,
    ExampleBrands = source.ExampleBrands,
    IsActive = source.IsActive,
    UpdatedAt = SYSUTCDATETIME()
WHEN NOT MATCHED THEN INSERT (
    TierCode, TierLabel, DefaultExpectedYears, ExampleBrands, IsActive
) VALUES (
    source.TierCode, source.TierLabel, source.DefaultExpectedYears, source.ExampleBrands, source.IsActive
);
GO

MERGE dbo.MaintenanceBrandTiers AS target
USING (VALUES
    (N'sub-zero', N'CONTAINS', N'luxury', 10, 1),
    (N'subzero', N'CONTAINS', N'luxury', 20, 1),
    (N'wolf', N'CONTAINS', N'luxury', 30, 1),
    (N'cove', N'CONTAINS', N'luxury', 40, 1),
    (N'miele', N'CONTAINS', N'luxury', 50, 1),
    (N'thermador', N'CONTAINS', N'luxury', 60, 1),
    (N'true', N'CONTAINS', N'luxury', 70, 1),
    (N'scotsman', N'CONTAINS', N'luxury', 80, 1),
    (N'hestan', N'CONTAINS', N'luxury', 90, 1),
    (N'kalamazoo', N'CONTAINS', N'luxury', 100, 1),
    (N'bosch', N'CONTAINS', N'premium', 110, 1),
    (N'kitchenaid', N'CONTAINS', N'premium', 120, 1),
    (N'monogram', N'CONTAINS', N'premium', 130, 1),
    (N'cafe', N'CONTAINS', N'premium', 140, 1),
    (N'café', N'CONTAINS', N'premium', 150, 1),
    (N'fisher & paykel', N'CONTAINS', N'premium', 160, 1),
    (N'jennair', N'CONTAINS', N'premium', 170, 1),
    (N'jenn-air', N'CONTAINS', N'premium', 180, 1),
    (N'speed queen', N'CONTAINS', N'premium', 190, 1),
    (N'whirlpool', N'CONTAINS', N'mass', 200, 1),
    (N'maytag', N'CONTAINS', N'mass', 210, 1),
    (N'ge', N'CONTAINS', N'mass', 220, 1),
    (N'lg', N'CONTAINS', N'mass', 230, 1),
    (N'samsung', N'CONTAINS', N'mass', 240, 1),
    (N'frigidaire', N'CONTAINS', N'mass', 250, 1),
    (N'hotpoint', N'CONTAINS', N'mass', 260, 1)
) AS source (BrandMatchText, MatchType, TierCode, SortOrder, IsActive)
ON target.BrandMatchText = source.BrandMatchText
WHEN MATCHED THEN UPDATE SET
    MatchType = source.MatchType,
    TierCode = source.TierCode,
    SortOrder = source.SortOrder,
    IsActive = source.IsActive,
    UpdatedAt = SYSUTCDATETIME()
WHEN NOT MATCHED THEN INSERT (
    BrandMatchText, MatchType, TierCode, SortOrder, IsActive
) VALUES (
    source.BrandMatchText, source.MatchType, source.TierCode, source.SortOrder, source.IsActive
);
GO

MERGE dbo.MaintenanceExpectedLifeRules AS target
USING (VALUES
    (N'refrigerator', N'luxury', 20, 1),
    (N'refrigerator', N'premium', 14, 1),
    (N'refrigerator', N'mass', 10, 1),
    (N'dishwasher', N'luxury', 15, 1),
    (N'dishwasher', N'premium', 10, 1),
    (N'dishwasher', N'mass', 8, 1),
    (N'cooking', N'luxury', 20, 1),
    (N'cooking', N'premium', 15, 1),
    (N'cooking', N'mass', 12, 1),
    (N'icemaker', N'luxury', 12, 1),
    (N'icemaker', N'premium', 10, 1),
    (N'icemaker', N'mass', 8, 1),
    (N'washer', N'luxury', 15, 1),
    (N'washer', N'premium', 11, 1),
    (N'washer', N'mass', 8, 1),
    (N'dryer', N'luxury', 15, 1),
    (N'dryer', N'premium', 11, 1),
    (N'dryer', N'mass', 8, 1),
    (N'laundry', N'luxury', 15, 1),
    (N'laundry', N'premium', 11, 1),
    (N'laundry', N'mass', 8, 1),
    (N'ventilation', N'luxury', 18, 1),
    (N'ventilation', N'premium', 14, 1),
    (N'ventilation', N'mass', 10, 1),
    (N'microwave', N'luxury', 10, 1),
    (N'microwave', N'premium', 8, 1),
    (N'microwave', N'mass', 7, 1),
    (N'generic', N'luxury', 15, 1),
    (N'generic', N'premium', 10, 1),
    (N'generic', N'mass', 8, 1)
) AS source (TemplateCode, TierCode, ExpectedYears, IsActive)
ON target.TemplateCode = source.TemplateCode AND target.TierCode = source.TierCode
WHEN MATCHED THEN UPDATE SET
    ExpectedYears = source.ExpectedYears,
    IsActive = source.IsActive,
    UpdatedAt = SYSUTCDATETIME()
WHEN NOT MATCHED THEN INSERT (
    TemplateCode, TierCode, ExpectedYears, IsActive
) VALUES (
    source.TemplateCode, source.TierCode, source.ExpectedYears, source.IsActive
);
GO

MERGE dbo.MaintenanceLifecycleStages AS target
USING (VALUES
    (N'Early Life', 0.4, 10, 1),
    (N'Mid Life', 0.7, 20, 1),
    (N'Mature', 0.9, 30, 1),
    (N'Replacement Planning', 999, 40, 1)
) AS source (StageLabel, MaxAgeRatio, SortOrder, IsActive)
ON target.StageLabel = source.StageLabel
WHEN MATCHED THEN UPDATE SET
    MaxAgeRatio = source.MaxAgeRatio,
    SortOrder = source.SortOrder,
    IsActive = source.IsActive,
    UpdatedAt = SYSUTCDATETIME()
WHEN NOT MATCHED THEN INSERT (
    StageLabel, MaxAgeRatio, SortOrder, IsActive
) VALUES (
    source.StageLabel, source.MaxAgeRatio, source.SortOrder, source.IsActive
);
GO


/* -------------------------------------------------------------------------
   New operational views

   Additive only. The base script's three views are left untouched so that
   re-running sql/maintenance_schema.sql cannot revert anything defined here.
   ------------------------------------------------------------------------- */

/*
   Payment readiness. MERGE_GUIDE 7.2: an AR household is payment-ready even
   with no Stripe payment method, so readiness must never be inferred from a
   missing card.
*/
CREATE OR ALTER VIEW dbo.vw_MaintenanceHouseholdPaymentReadiness
AS
SELECT
    h.HouseholdId,
    h.HouseholdReference,
    h.DisplayName AS HouseholdName,
    h.BillingMethodCode,
    h.AccountTerms,
    h.ARStatus,
    h.ExternalARCustomerId,
    pp.PaymentProfileId,
    pp.PaymentProfileStatus,
    pp.CardBrand,
    pp.CardLast4,
    CAST(
        CASE
            WHEN h.BillingMethodCode = 'AR_ACCOUNT'
                 AND ISNULL(h.ARStatus, 'Review') = 'Active' THEN 1
            WHEN h.BillingMethodCode = 'CARD_ON_FILE'
                 AND pp.PaymentProfileId IS NOT NULL
                 AND pp.PaymentProfileStatus = 'Active' THEN 1
            ELSE 0
        END AS BIT
    ) AS PaymentReady,
    CASE
        WHEN h.BillingMethodCode = 'AR_ACCOUNT'
             AND ISNULL(h.ARStatus, 'Review') = 'Active' THEN 'AR_APPROVED'
        WHEN h.BillingMethodCode = 'AR_ACCOUNT' THEN 'ACTION_REQUIRED'
        WHEN pp.PaymentProfileId IS NULL THEN 'ACTION_REQUIRED'
        WHEN pp.PaymentProfileStatus <> 'Active' THEN 'ACTION_REQUIRED'
        ELSE 'READY_TO_CHARGE'
    END AS PaymentReadinessCode
FROM dbo.MaintenanceHouseholds h
OUTER APPLY (
    SELECT TOP (1)
        p.PaymentProfileId, p.PaymentProfileStatus, p.CardBrand, p.CardLast4
    FROM dbo.MaintenancePaymentProfiles p
    WHERE p.HouseholdId = h.HouseholdId
    ORDER BY
        CASE WHEN p.PaymentProfileStatus = 'Active' THEN 0 ELSE 1 END,
        p.PaymentProfileId DESC
) pp;
GO

/*
   Field progress per visit. Drives the Command Center's view of what the
   technician has finished and whether the report package is ready
   (MERGE_GUIDE 23).
*/
CREATE OR ALTER VIEW dbo.vw_MaintenanceFieldProgress
AS
SELECT
    v.VisitId,
    v.HouseholdId,
    h.DisplayName AS HouseholdName,
    v.DueDate,
    v.VisitStatus,
    v.AssignedTechnicianUserId,
    v.AssignedTechnicianNameSnapshot,
    v.FieldStartedAt,
    v.CompletedAt,
    COUNT(va.VisitAssetId) AS ScopedAssetCount,
    SUM(CASE WHEN fi.InspectionStatus IN ('FIELD_COMPLETE', 'REPORT_GENERATED')
             THEN 1 ELSE 0 END) AS CompletedAssetCount,
    SUM(CASE WHEN fi.InspectionStatus = 'IN_PROGRESS' THEN 1 ELSE 0 END)
        AS InProgressAssetCount,
    SUM(CASE WHEN fi.FieldInspectionId IS NULL
                   OR fi.InspectionStatus = 'NOT_STARTED'
             THEN 1 ELSE 0 END) AS NotStartedAssetCount,
    SUM(CASE WHEN fi.FollowUpRequired = 1 THEN 1 ELSE 0 END) AS FollowUpCount,
    CAST(
        CASE WHEN COUNT(va.VisitAssetId) > 0
              AND COUNT(va.VisitAssetId) = SUM(
                    CASE WHEN fi.InspectionStatus IN ('FIELD_COMPLETE', 'REPORT_GENERATED')
                         THEN 1 ELSE 0 END)
             THEN 1 ELSE 0 END AS BIT
    ) AS AllAssetsFieldComplete,
    AVG(CAST(fi.FinalHealthScore AS DECIMAL(6,2))) AS AverageHealthScore
FROM dbo.MaintenanceVisits v
INNER JOIN dbo.MaintenanceHouseholds h
    ON h.HouseholdId = v.HouseholdId
LEFT JOIN dbo.MaintenanceVisitAssets va
    ON va.VisitId = v.VisitId
LEFT JOIN dbo.MaintenanceFieldInspections fi
    ON fi.VisitId = va.VisitId
   AND fi.AssetId = va.AssetId
GROUP BY
    v.VisitId, v.HouseholdId, h.DisplayName, v.DueDate, v.VisitStatus,
    v.AssignedTechnicianUserId, v.AssignedTechnicianNameSnapshot,
    v.FieldStartedAt, v.CompletedAt;
GO

/*
   Resolved protocol per asset. The SQL counterpart of
   WILSON_PROTOCOL.resolveCheckpointSet(), including the IMUC override.
   Compare against MaintenanceAssets.CheckpointSetCode to find assets still
   carrying a stale snapshot.
*/
CREATE OR ALTER VIEW dbo.vw_MaintenanceAssetProtocol
AS
SELECT
    resolution.AssetId,
    resolution.HouseholdId,
    resolution.AssetCategory,
    resolution.AssetTypeCode,
    resolution.AssetTypeName,
    resolution.CustomerCategoryCode,
    resolution.StoredCheckpointSetCode,
    resolution.ResolvedTemplateCode,
    CAST(CASE WHEN resolution.StoredCheckpointSetCode IS NOT NULL
                   AND resolution.StoredCheckpointSetCode <> resolution.ResolvedTemplateCode
              THEN 1 ELSE 0 END AS BIT) AS StoredValueIsStale
FROM (
    /* Non-IMUC: assignment by precedence, then the stored snapshot only if it
       names a real template, then generic. The snapshot ranks BELOW config and
       above generic -- identical to step 4 of resolveCheckpointSet(). */
    SELECT
        a.AssetId,
        a.HouseholdId,
        a.AssetCategory,
        a.AssetTypeCode,
        a.AssetTypeName,
        a.CustomerCategoryCode,
        a.CheckpointSetCode AS StoredCheckpointSetCode,
        COALESCE(resolved.TemplateCode, snapshot.TemplateCode, 'generic')
            AS ResolvedTemplateCode
    FROM dbo.MaintenanceAssets a
    OUTER APPLY (
        SELECT TOP (1) pa.TemplateCode
        FROM dbo.MaintenanceProtocolAssignments pa
        WHERE pa.IsActive = 1
          AND (
                (pa.AssignmentScope = 'APPLIANCE_TYPE' AND pa.ScopeCode = a.AssetTypeCode)
             OR (pa.AssignmentScope = 'CUSTOMER_CATEGORY' AND pa.ScopeCode = a.CustomerCategoryCode)
          )
        ORDER BY pa.Precedence, pa.ProtocolAssignmentId
    ) resolved
    OUTER APPLY (
        SELECT TOP (1) t.TemplateCode
        FROM dbo.MaintenanceProtocolTemplates t
        WHERE t.TemplateCode = a.CheckpointSetCode
          AND t.IsActive = 1
        ORDER BY t.TemplateVersion DESC
    ) snapshot
    WHERE a.AssetCategory <> 'imuc'

    UNION ALL

    /* IMUC group membership always wins, before any assignment lookup. */
    SELECT
        a.AssetId,
        a.HouseholdId,
        a.AssetCategory,
        a.AssetTypeCode,
        a.AssetTypeName,
        a.CustomerCategoryCode,
        a.CheckpointSetCode AS StoredCheckpointSetCode,
        'icemaker' AS ResolvedTemplateCode
    FROM dbo.MaintenanceAssets a
    WHERE a.AssetCategory = 'imuc'
) resolution;
GO

/* -------------------------------------------------------------------------
   Schema version
   ------------------------------------------------------------------------- */
IF NOT EXISTS (
    SELECT 1 FROM dbo.MaintenanceSchemaVersions WHERE VersionNumber = '0.9'
)
BEGIN
    INSERT INTO dbo.MaintenanceSchemaVersions (VersionNumber, Notes)
    VALUES ('0.9', 'Property areas, AR billing, technician field inspection layer, report delivery tracking, technician user linkage, and versioned lifecycle/protocol configuration. Protocol seeds generated from plan-config.js v0.6.');
END;
GO
