/*
Wilson Maintenance Portal - SQL Server migration v0.9
Generated by sql/generate_migration_v09.py -- do not hand-edit.
Edit sql/_migration_v09_ddl.sql (structure) or assets/plan-config.js (seed data)
and re-run the generator.

Purpose
-------
Implements MERGE_GUIDE.md section 7: the schema additions required before the
real merge. sql/maintenance_schema.sql is at v0.3 (2026-08-21) and predates the
v0.5-v0.9 field workflow entirely -- it has no tables for technician
inspections, checkpoints, readings, photos, areas, or lifecycle/brand tier, and
its health-report tables still reflect the report builder that v0.7 retired.

Covers:
  7.1  Property areas                     MaintenanceAreas, MaintenanceAssets.AreaId
  7.2  Household billing method / AR      MaintenanceHouseholds billing columns
  7.3  Raw technician inspection data     MaintenanceFieldInspections (+Checks, +Photos)
  7.4  Report delivery tracking           MaintenanceReportDeliveries
  7.5  Technician assignment / user id    MaintenanceVisits technician columns
  7.6  Lifecycle configuration            MaintenanceLifecycleTiers, MaintenanceBrandTiers,
                                          MaintenanceExpectedLifeRules, MaintenanceLifecycleStages
  7.7  Protocol configuration             MaintenanceProtocolTemplates, MaintenanceProtocolCheckpoints,
                                          MaintenanceProtocolAssignments
  7.8  Filter service pricing (added)     MaintenanceFilterPrices, plus per-asset
                                          filter opt-in/quantity columns and the
                                          subscription filter-service amount

Status codes use the centralized vocabularies from MERGE_GUIDE section 34 and
are enforced with CHECK constraints, so a UI phrase can never be persisted as
state.

Applying this script
--------------------
Run sql/maintenance_schema.sql first. This script is strictly additive and
idempotent: every object is guarded, every column addition is guarded by
COL_LENGTH, and every seed is a MERGE. Re-running it is safe and is the
intended way to pick up protocol changes.

It deliberately does NOT redefine any existing object. sql/maintenance_schema.sql
ends with three CREATE OR ALTER VIEW statements; if this migration altered one of
them, a later re-run of the base script would silently revert it. New behaviour
is therefore delivered as new views instead.

Not covered here
----------------
- Retiring the office-built report tables (MaintenanceHealthReport* still carry
  the pre-v0.7 model). They are left intact because live prototype data may
  reference them; plan their retirement with the API contract rewrite.
- Photo binary storage. Only the storage key is modelled -- see MERGE_GUIDE
  section 20.
- HVAC field protocols. No HVAC field workflow exists yet (context section 34
  item 3), so no HVAC protocol templates are seeded.

Security
--------
No cardholder data. Technician identity is stored as the authoritative internal
user id plus a display-name snapshot for historical reporting.
*/

SET NOCOUNT ON;
SET XACT_ABORT ON;
GO

/* -------------------------------------------------------------------------
   Preflight: the base schema must already be present
   ------------------------------------------------------------------------- */
IF OBJECT_ID('dbo.MaintenanceHouseholds', 'U') IS NULL
    OR OBJECT_ID('dbo.MaintenanceAssets', 'U') IS NULL
    OR OBJECT_ID('dbo.MaintenanceVisits', 'U') IS NULL
    OR OBJECT_ID('dbo.MaintenanceHealthReports', 'U') IS NULL
BEGIN
    RAISERROR (
        'Base maintenance schema not found. Run sql/maintenance_schema.sql before this migration.',
        20, 1
    ) WITH LOG;
END;
GO

/* -------------------------------------------------------------------------
   7.1  Property areas
   ------------------------------------------------------------------------- */
IF OBJECT_ID('dbo.MaintenanceAreas', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.MaintenanceAreas (
        AreaId INT IDENTITY(1,1) NOT NULL
            CONSTRAINT PK_MaintenanceAreas PRIMARY KEY,
        HouseholdId INT NOT NULL,
        AreaName NVARCHAR(150) NOT NULL,
        AreaKind NVARCHAR(30) NULL,
        SortOrder INT NULL,
        AreaStatus NVARCHAR(30) NOT NULL
            CONSTRAINT DF_MaintenanceAreas_Status DEFAULT ('Active'),
        CreatedAt DATETIME2 NOT NULL
            CONSTRAINT DF_MaintenanceAreas_CreatedAt DEFAULT SYSUTCDATETIME(),
        UpdatedAt DATETIME2 NOT NULL
            CONSTRAINT DF_MaintenanceAreas_UpdatedAt DEFAULT SYSUTCDATETIME(),
        VersionStamp ROWVERSION,
        CONSTRAINT FK_MaintenanceAreas_Households
            FOREIGN KEY (HouseholdId) REFERENCES dbo.MaintenanceHouseholds(HouseholdId)
    );

    CREATE UNIQUE INDEX UX_MaintenanceAreas_HouseholdName
        ON dbo.MaintenanceAreas(HouseholdId, AreaName);

    CREATE INDEX IX_MaintenanceAreas_Household
        ON dbo.MaintenanceAreas(HouseholdId, AreaStatus, SortOrder);
END;
GO

/* AreaId on assets. LocationName is kept as the text snapshot the customer and
   invoice import actually entered -- see MERGE_GUIDE 7.1. */
IF COL_LENGTH('dbo.MaintenanceAssets', 'AreaId') IS NULL
    ALTER TABLE dbo.MaintenanceAssets ADD AreaId INT NULL;
GO
IF OBJECT_ID('dbo.FK_MaintenanceAssets_Areas', 'F') IS NULL
    ALTER TABLE dbo.MaintenanceAssets ADD CONSTRAINT FK_MaintenanceAssets_Areas
        FOREIGN KEY (AreaId) REFERENCES dbo.MaintenanceAreas(AreaId);
GO
IF NOT EXISTS (
    SELECT 1 FROM sys.indexes
    WHERE name = 'IX_MaintenanceAssets_Area'
      AND object_id = OBJECT_ID('dbo.MaintenanceAssets')
)
    CREATE INDEX IX_MaintenanceAssets_Area
        ON dbo.MaintenanceAssets(AreaId, SortOrder);
GO

/* -------------------------------------------------------------------------
   7.2  Household billing method / AR

   Added as columns on MaintenanceHouseholds rather than a separate 1:1 billing
   profile table (MERGE_GUIDE 7.2 permits either). Command Center payment
   readiness is a per-household question on nearly every queue query, and a 1:1
   table would add a join to all of them for four columns with no history
   requirement. MaintenancePaymentProfiles already holds the card-side rows.
   ------------------------------------------------------------------------- */
IF COL_LENGTH('dbo.MaintenanceHouseholds', 'BillingMethodCode') IS NULL
    ALTER TABLE dbo.MaintenanceHouseholds ADD BillingMethodCode NVARCHAR(30) NOT NULL
        CONSTRAINT DF_MaintenanceHouseholds_BillingMethod DEFAULT ('CARD_ON_FILE');
GO
IF COL_LENGTH('dbo.MaintenanceHouseholds', 'AccountTerms') IS NULL
    ALTER TABLE dbo.MaintenanceHouseholds ADD AccountTerms NVARCHAR(50) NULL;
GO
IF COL_LENGTH('dbo.MaintenanceHouseholds', 'ExternalARCustomerId') IS NULL
    ALTER TABLE dbo.MaintenanceHouseholds ADD ExternalARCustomerId NVARCHAR(100) NULL;
GO
IF COL_LENGTH('dbo.MaintenanceHouseholds', 'ARStatus') IS NULL
    ALTER TABLE dbo.MaintenanceHouseholds ADD ARStatus NVARCHAR(30) NULL;
GO
IF OBJECT_ID('dbo.CK_MaintenanceHouseholds_BillingMethod', 'C') IS NULL
    ALTER TABLE dbo.MaintenanceHouseholds
        ADD CONSTRAINT CK_MaintenanceHouseholds_BillingMethod
        CHECK (BillingMethodCode IN ('CARD_ON_FILE', 'AR_ACCOUNT'));
GO
IF OBJECT_ID('dbo.CK_MaintenanceHouseholds_ARStatus', 'C') IS NULL
    ALTER TABLE dbo.MaintenanceHouseholds
        ADD CONSTRAINT CK_MaintenanceHouseholds_ARStatus
        CHECK (ARStatus IS NULL OR ARStatus IN ('Active', 'Hold', 'Review'));
GO

/* -------------------------------------------------------------------------
   7.6 / 7.7  Configuration tables

   Table definitions only; seed data is generated at the end of this script.
   ------------------------------------------------------------------------- */
IF OBJECT_ID('dbo.MaintenanceLifecycleTiers', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.MaintenanceLifecycleTiers (
        LifecycleTierId INT IDENTITY(1,1) NOT NULL
            CONSTRAINT PK_MaintenanceLifecycleTiers PRIMARY KEY,
        TierCode NVARCHAR(20) NOT NULL
            CONSTRAINT UQ_MaintenanceLifecycleTiers_Code UNIQUE,
        TierLabel NVARCHAR(50) NOT NULL,
        DefaultExpectedYears DECIMAL(5,1) NULL,
        ExampleBrands NVARCHAR(500) NULL,
        IsActive BIT NOT NULL
            CONSTRAINT DF_MaintenanceLifecycleTiers_Active DEFAULT (1),
        CreatedAt DATETIME2 NOT NULL
            CONSTRAINT DF_MaintenanceLifecycleTiers_CreatedAt DEFAULT SYSUTCDATETIME(),
        UpdatedAt DATETIME2 NOT NULL
            CONSTRAINT DF_MaintenanceLifecycleTiers_UpdatedAt DEFAULT SYSUTCDATETIME()
    );
END;
GO

IF OBJECT_ID('dbo.MaintenanceBrandTiers', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.MaintenanceBrandTiers (
        BrandTierId INT IDENTITY(1,1) NOT NULL
            CONSTRAINT PK_MaintenanceBrandTiers PRIMARY KEY,
        BrandMatchText NVARCHAR(100) NOT NULL
            CONSTRAINT UQ_MaintenanceBrandTiers_Match UNIQUE,
        MatchType NVARCHAR(20) NOT NULL
            CONSTRAINT DF_MaintenanceBrandTiers_MatchType DEFAULT ('CONTAINS'),
        TierCode NVARCHAR(20) NOT NULL,
        SortOrder INT NULL,
        IsActive BIT NOT NULL
            CONSTRAINT DF_MaintenanceBrandTiers_Active DEFAULT (1),
        CreatedAt DATETIME2 NOT NULL
            CONSTRAINT DF_MaintenanceBrandTiers_CreatedAt DEFAULT SYSUTCDATETIME(),
        UpdatedAt DATETIME2 NOT NULL
            CONSTRAINT DF_MaintenanceBrandTiers_UpdatedAt DEFAULT SYSUTCDATETIME(),
        CONSTRAINT CK_MaintenanceBrandTiers_MatchType
            CHECK (MatchType IN ('EXACT', 'CONTAINS'))
    );

    CREATE INDEX IX_MaintenanceBrandTiers_Lookup
        ON dbo.MaintenanceBrandTiers(IsActive, SortOrder);
END;
GO

IF OBJECT_ID('dbo.MaintenanceProtocolTemplates', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.MaintenanceProtocolTemplates (
        ProtocolTemplateId INT IDENTITY(1,1) NOT NULL
            CONSTRAINT PK_MaintenanceProtocolTemplates PRIMARY KEY,
        TemplateCode NVARCHAR(50) NOT NULL,
        TemplateName NVARCHAR(150) NOT NULL,
        TemplateVersion INT NOT NULL
            CONSTRAINT DF_MaintenanceProtocolTemplates_Version DEFAULT (1),
        TemplateNote NVARCHAR(500) NULL,
        SourceConfigVersion NVARCHAR(50) NULL,
        IsActive BIT NOT NULL
            CONSTRAINT DF_MaintenanceProtocolTemplates_Active DEFAULT (1),
        CreatedAt DATETIME2 NOT NULL
            CONSTRAINT DF_MaintenanceProtocolTemplates_CreatedAt DEFAULT SYSUTCDATETIME(),
        UpdatedAt DATETIME2 NOT NULL
            CONSTRAINT DF_MaintenanceProtocolTemplates_UpdatedAt DEFAULT SYSUTCDATETIME(),
        CONSTRAINT UQ_MaintenanceProtocolTemplates_CodeVersion
            UNIQUE (TemplateCode, TemplateVersion)
    );
END;
GO

IF OBJECT_ID('dbo.MaintenanceProtocolCheckpoints', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.MaintenanceProtocolCheckpoints (
        ProtocolCheckpointId INT IDENTITY(1,1) NOT NULL
            CONSTRAINT PK_MaintenanceProtocolCheckpoints PRIMARY KEY,
        ProtocolTemplateId INT NOT NULL,
        CheckpointCode NVARCHAR(50) NOT NULL,
        CheckpointName NVARCHAR(300) NOT NULL,
        PromptText NVARCHAR(MAX) NULL,
        GuidanceText NVARCHAR(MAX) NULL,
        ReadingLabel NVARCHAR(150) NULL,
        ReadingFieldsJson NVARCHAR(MAX) NULL,
        DerivedReadingCode NVARCHAR(50) NULL,
        ReadingUnit NVARCHAR(30) NULL,
        PhotoPromptText NVARCHAR(300) NULL,
        RatingRequired BIT NOT NULL
            CONSTRAINT DF_MaintenanceProtocolCheckpoints_RatingRequired DEFAULT (1),
        SortOrder INT NULL,
        IsActive BIT NOT NULL
            CONSTRAINT DF_MaintenanceProtocolCheckpoints_Active DEFAULT (1),
        CreatedAt DATETIME2 NOT NULL
            CONSTRAINT DF_MaintenanceProtocolCheckpoints_CreatedAt DEFAULT SYSUTCDATETIME(),
        UpdatedAt DATETIME2 NOT NULL
            CONSTRAINT DF_MaintenanceProtocolCheckpoints_UpdatedAt DEFAULT SYSUTCDATETIME(),
        CONSTRAINT FK_MaintenanceProtocolCheckpoints_Templates
            FOREIGN KEY (ProtocolTemplateId)
            REFERENCES dbo.MaintenanceProtocolTemplates(ProtocolTemplateId),
        CONSTRAINT UQ_MaintenanceProtocolCheckpoints_Code
            UNIQUE (ProtocolTemplateId, CheckpointCode)
    );

    CREATE INDEX IX_MaintenanceProtocolCheckpoints_Template
        ON dbo.MaintenanceProtocolCheckpoints(ProtocolTemplateId, SortOrder);
END;
GO

/*
   Protocol assignment: which template applies to a given appliance.

   This is the SQL form of WILSON_PROTOCOL.resolveCheckpointSet() in
   plan-config.js. Resolution walks assignments in Precedence order and takes
   the first active match:

       Precedence 10  APPLIANCE_TYPE      matched on MaintenanceAssets.AssetTypeCode
       Precedence 20  CUSTOMER_CATEGORY   matched on MaintenanceAssets.CustomerCategoryCode

   MaintenanceAssets.CheckpointSetCode remains as the value captured at
   enrollment, but it is a snapshot, NOT the resolution input -- exactly as in
   the JS resolver. Assets created before v0.9.1 hold four known-wrong values
   (Ventilation as generic, Microwave as cooking, Washer and Dryer as laundry);
   resolving through these assignments corrects them with no data migration.
   IMUC group membership still wins over both scopes and is applied in code.
*/
IF OBJECT_ID('dbo.MaintenanceProtocolAssignments', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.MaintenanceProtocolAssignments (
        ProtocolAssignmentId INT IDENTITY(1,1) NOT NULL
            CONSTRAINT PK_MaintenanceProtocolAssignments PRIMARY KEY,
        AssignmentScope NVARCHAR(30) NOT NULL,
        ScopeCode NVARCHAR(50) NOT NULL,
        ScopeLabel NVARCHAR(150) NULL,
        TemplateCode NVARCHAR(50) NOT NULL,
        Precedence INT NOT NULL
            CONSTRAINT DF_MaintenanceProtocolAssignments_Precedence DEFAULT (20),
        IsActive BIT NOT NULL
            CONSTRAINT DF_MaintenanceProtocolAssignments_Active DEFAULT (1),
        CreatedAt DATETIME2 NOT NULL
            CONSTRAINT DF_MaintenanceProtocolAssignments_CreatedAt DEFAULT SYSUTCDATETIME(),
        UpdatedAt DATETIME2 NOT NULL
            CONSTRAINT DF_MaintenanceProtocolAssignments_UpdatedAt DEFAULT SYSUTCDATETIME(),
        CONSTRAINT UQ_MaintenanceProtocolAssignments_Scope
            UNIQUE (AssignmentScope, ScopeCode),
        CONSTRAINT CK_MaintenanceProtocolAssignments_Scope
            CHECK (AssignmentScope IN ('APPLIANCE_TYPE', 'CUSTOMER_CATEGORY'))
    );

    CREATE INDEX IX_MaintenanceProtocolAssignments_Resolve
        ON dbo.MaintenanceProtocolAssignments(IsActive, Precedence, ScopeCode);
END;
GO

IF OBJECT_ID('dbo.MaintenanceExpectedLifeRules', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.MaintenanceExpectedLifeRules (
        ExpectedLifeRuleId INT IDENTITY(1,1) NOT NULL
            CONSTRAINT PK_MaintenanceExpectedLifeRules PRIMARY KEY,
        TemplateCode NVARCHAR(50) NOT NULL,
        TierCode NVARCHAR(20) NOT NULL,
        ExpectedYears DECIMAL(5,1) NOT NULL,
        IsActive BIT NOT NULL
            CONSTRAINT DF_MaintenanceExpectedLifeRules_Active DEFAULT (1),
        CreatedAt DATETIME2 NOT NULL
            CONSTRAINT DF_MaintenanceExpectedLifeRules_CreatedAt DEFAULT SYSUTCDATETIME(),
        UpdatedAt DATETIME2 NOT NULL
            CONSTRAINT DF_MaintenanceExpectedLifeRules_UpdatedAt DEFAULT SYSUTCDATETIME(),
        CONSTRAINT UQ_MaintenanceExpectedLifeRules_Key
            UNIQUE (TemplateCode, TierCode)
    );
END;
GO

IF OBJECT_ID('dbo.MaintenanceLifecycleStages', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.MaintenanceLifecycleStages (
        LifecycleStageId INT IDENTITY(1,1) NOT NULL
            CONSTRAINT PK_MaintenanceLifecycleStages PRIMARY KEY,
        StageLabel NVARCHAR(50) NOT NULL
            CONSTRAINT UQ_MaintenanceLifecycleStages_Label UNIQUE,
        MaxAgeRatio DECIMAL(6,3) NOT NULL,
        SortOrder INT NULL,
        IsActive BIT NOT NULL
            CONSTRAINT DF_MaintenanceLifecycleStages_Active DEFAULT (1),
        CreatedAt DATETIME2 NOT NULL
            CONSTRAINT DF_MaintenanceLifecycleStages_CreatedAt DEFAULT SYSUTCDATETIME(),
        UpdatedAt DATETIME2 NOT NULL
            CONSTRAINT DF_MaintenanceLifecycleStages_UpdatedAt DEFAULT SYSUTCDATETIME()
    );
END;
GO

/* -------------------------------------------------------------------------
   7.3  Raw technician inspection data

   The field layer is the record of what the technician actually entered. It is
   append-and-correct, never overwritten by report generation: health reports
   are derived from it, so a report can be regenerated or revised without
   losing the underlying field facts (MERGE_GUIDE 7.3, 23).
   ------------------------------------------------------------------------- */
IF OBJECT_ID('dbo.MaintenanceFieldInspections', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.MaintenanceFieldInspections (
        FieldInspectionId INT IDENTITY(1,1) NOT NULL
            CONSTRAINT PK_MaintenanceFieldInspections PRIMARY KEY,
        VisitId INT NOT NULL,
        VisitAssetId INT NULL,
        HouseholdId INT NOT NULL,
        AssetId INT NOT NULL,

        /* Protocol version in force on the service date (MERGE_GUIDE 7.7). */
        ProtocolTemplateId INT NULL,
        ProtocolTemplateCodeSnapshot NVARCHAR(50) NULL,
        ProtocolTemplateVersionSnapshot INT NULL,

        /* Identity: the internal user id is authoritative, the name is a snapshot. */
        TechnicianUserId NVARCHAR(100) NULL,
        TechnicianDisplayNameSnapshot NVARCHAR(150) NULL,

        InspectionStatus NVARCHAR(40) NOT NULL
            CONSTRAINT DF_MaintenanceFieldInspections_Status DEFAULT ('NOT_STARTED'),
        StartedAt DATETIME2 NULL,
        CompletedAt DATETIME2 NULL,

        /* Lifecycle context captured in the field. */
        ApproxAgeYears DECIMAL(5,1) NULL,
        LifecycleTierCode NVARCHAR(20) NULL,
        ExpectedLifeYears DECIMAL(5,1) NULL,
        LifecycleStage NVARCHAR(50) NULL,

        /* Scoring. 75% condition / 25% lifecycle -- see reportScoring in plan-config.js. */
        ConditionScore DECIMAL(6,2) NULL,
        LifecycleScore DECIMAL(6,2) NULL,
        FinalHealthScore DECIMAL(6,2) NULL,
        GradeLabel NVARCHAR(10) NULL,

        SerialTagPhotoStorageKey NVARCHAR(500) NULL,
        TechnicianSummary NVARCHAR(MAX) NULL,
        FollowUpRequired BIT NOT NULL
            CONSTRAINT DF_MaintenanceFieldInspections_FollowUp DEFAULT (0),

        CreatedAt DATETIME2 NOT NULL
            CONSTRAINT DF_MaintenanceFieldInspections_CreatedAt DEFAULT SYSUTCDATETIME(),
        UpdatedAt DATETIME2 NOT NULL
            CONSTRAINT DF_MaintenanceFieldInspections_UpdatedAt DEFAULT SYSUTCDATETIME(),
        VersionStamp ROWVERSION,

        CONSTRAINT FK_MaintenanceFieldInspections_Visits
            FOREIGN KEY (VisitId) REFERENCES dbo.MaintenanceVisits(VisitId),
        CONSTRAINT FK_MaintenanceFieldInspections_VisitAssets
            FOREIGN KEY (VisitAssetId) REFERENCES dbo.MaintenanceVisitAssets(VisitAssetId),
        CONSTRAINT FK_MaintenanceFieldInspections_Households
            FOREIGN KEY (HouseholdId) REFERENCES dbo.MaintenanceHouseholds(HouseholdId),
        CONSTRAINT FK_MaintenanceFieldInspections_Assets
            FOREIGN KEY (AssetId) REFERENCES dbo.MaintenanceAssets(AssetId),
        CONSTRAINT FK_MaintenanceFieldInspections_Templates
            FOREIGN KEY (ProtocolTemplateId)
            REFERENCES dbo.MaintenanceProtocolTemplates(ProtocolTemplateId),

        /* MERGE_GUIDE 7.3 status vocabulary. */
        CONSTRAINT CK_MaintenanceFieldInspections_Status
            CHECK (InspectionStatus IN (
                'NOT_STARTED', 'IN_PROGRESS', 'FIELD_COMPLETE', 'REPORT_GENERATED'
            )),
        CONSTRAINT CK_MaintenanceFieldInspections_Score
            CHECK (FinalHealthScore IS NULL OR FinalHealthScore BETWEEN 0 AND 100),

        /* One live inspection per asset per visit. */
        CONSTRAINT UQ_MaintenanceFieldInspections_VisitAsset
            UNIQUE (VisitId, AssetId)
    );

    CREATE INDEX IX_MaintenanceFieldInspections_Visit
        ON dbo.MaintenanceFieldInspections(VisitId, InspectionStatus);

    CREATE INDEX IX_MaintenanceFieldInspections_Asset
        ON dbo.MaintenanceFieldInspections(AssetId, CompletedAt DESC);

    CREATE INDEX IX_MaintenanceFieldInspections_Technician
        ON dbo.MaintenanceFieldInspections(TechnicianUserId, CompletedAt DESC);
END;
GO

IF OBJECT_ID('dbo.MaintenanceFieldInspectionChecks', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.MaintenanceFieldInspectionChecks (
        FieldInspectionCheckId INT IDENTITY(1,1) NOT NULL
            CONSTRAINT PK_MaintenanceFieldInspectionChecks PRIMARY KEY,
        FieldInspectionId INT NOT NULL,
        CheckpointCode NVARCHAR(50) NOT NULL,

        /* Wording as shown to the technician on the service date. Never a live
           join to MaintenanceProtocolCheckpoints -- protocol text changes. */
        CheckpointLabelSnapshot NVARCHAR(300) NULL,

        Performed BIT NOT NULL
            CONSTRAINT DF_MaintenanceFieldInspectionChecks_Performed DEFAULT (0),
        Rating TINYINT NULL,
        StatusLabel NVARCHAR(20) NULL,
        ObservedValue NVARCHAR(150) NULL,
        ObservedUnit NVARCHAR(30) NULL,
        TargetText NVARCHAR(300) NULL,
        ReadingJson NVARCHAR(MAX) NULL,
        TechnicianNote NVARCHAR(MAX) NULL,
        PhotoCount INT NOT NULL
            CONSTRAINT DF_MaintenanceFieldInspectionChecks_PhotoCount DEFAULT (0),
        SortOrder INT NULL,
        CompletedAt DATETIME2 NULL,
        CreatedAt DATETIME2 NOT NULL
            CONSTRAINT DF_MaintenanceFieldInspectionChecks_CreatedAt DEFAULT SYSUTCDATETIME(),
        UpdatedAt DATETIME2 NOT NULL
            CONSTRAINT DF_MaintenanceFieldInspectionChecks_UpdatedAt DEFAULT SYSUTCDATETIME(),

        CONSTRAINT FK_MaintenanceFieldInspectionChecks_Inspections
            FOREIGN KEY (FieldInspectionId)
            REFERENCES dbo.MaintenanceFieldInspections(FieldInspectionId),

        /* Five tap buttons in the field tool, not a slider. */
        CONSTRAINT CK_MaintenanceFieldInspectionChecks_Rating
            CHECK (Rating IS NULL OR Rating BETWEEN 1 AND 5),
        CONSTRAINT CK_MaintenanceFieldInspectionChecks_Status
            CHECK (StatusLabel IS NULL OR StatusLabel IN ('PASS', 'MONITOR', 'ACTION')),
        CONSTRAINT UQ_MaintenanceFieldInspectionChecks_Code
            UNIQUE (FieldInspectionId, CheckpointCode)
    );

    CREATE INDEX IX_MaintenanceFieldInspectionChecks_Inspection
        ON dbo.MaintenanceFieldInspectionChecks(FieldInspectionId, SortOrder);
END;
GO

IF OBJECT_ID('dbo.MaintenanceFieldInspectionPhotos', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.MaintenanceFieldInspectionPhotos (
        FieldInspectionPhotoId INT IDENTITY(1,1) NOT NULL
            CONSTRAINT PK_MaintenanceFieldInspectionPhotos PRIMARY KEY,
        FieldInspectionId INT NOT NULL,
        FieldInspectionCheckId INT NULL,
        PhotoKind NVARCHAR(30) NOT NULL
            CONSTRAINT DF_MaintenanceFieldInspectionPhotos_Kind DEFAULT ('CHECKPOINT'),
        StorageKey NVARCHAR(500) NOT NULL,
        ContentType NVARCHAR(100) NULL,
        ByteSize BIGINT NULL,
        Caption NVARCHAR(300) NULL,
        CapturedAt DATETIME2 NULL,
        IncludeInReport BIT NOT NULL
            CONSTRAINT DF_MaintenanceFieldInspectionPhotos_Include DEFAULT (1),
        SortOrder INT NULL,
        CreatedAt DATETIME2 NOT NULL
            CONSTRAINT DF_MaintenanceFieldInspectionPhotos_CreatedAt DEFAULT SYSUTCDATETIME(),

        CONSTRAINT FK_MaintenanceFieldInspectionPhotos_Inspections
            FOREIGN KEY (FieldInspectionId)
            REFERENCES dbo.MaintenanceFieldInspections(FieldInspectionId),
        CONSTRAINT FK_MaintenanceFieldInspectionPhotos_Checks
            FOREIGN KEY (FieldInspectionCheckId)
            REFERENCES dbo.MaintenanceFieldInspectionChecks(FieldInspectionCheckId),
        CONSTRAINT CK_MaintenanceFieldInspectionPhotos_Kind
            CHECK (PhotoKind IN ('SERIAL_TAG', 'CHECKPOINT', 'BEFORE', 'AFTER', 'OTHER'))
    );

    CREATE INDEX IX_MaintenanceFieldInspectionPhotos_Inspection
        ON dbo.MaintenanceFieldInspectionPhotos(FieldInspectionId, SortOrder);
END;
GO

/* Link a generated report back to the field inspection it came from. Nullable:
   pre-v0.7 reports were built in the office and have no field inspection. */
IF COL_LENGTH('dbo.MaintenanceHealthReports', 'FieldInspectionId') IS NULL
    ALTER TABLE dbo.MaintenanceHealthReports ADD FieldInspectionId INT NULL;
GO
IF OBJECT_ID('dbo.FK_MaintenanceHealthReports_FieldInspections', 'F') IS NULL
    ALTER TABLE dbo.MaintenanceHealthReports
        ADD CONSTRAINT FK_MaintenanceHealthReports_FieldInspections
        FOREIGN KEY (FieldInspectionId)
        REFERENCES dbo.MaintenanceFieldInspections(FieldInspectionId);
GO

/* -------------------------------------------------------------------------
   7.4  Report delivery tracking

   Append-only per send attempt, so resend history survives (MERGE_GUIDE 7.4).
   ------------------------------------------------------------------------- */
IF OBJECT_ID('dbo.MaintenanceReportDeliveries', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.MaintenanceReportDeliveries (
        ReportDeliveryId INT IDENTITY(1,1) NOT NULL
            CONSTRAINT PK_MaintenanceReportDeliveries PRIMARY KEY,
        HealthReportId INT NOT NULL,
        HouseholdId INT NOT NULL,
        RecipientEmail NVARCHAR(255) NOT NULL,
        RecipientName NVARCHAR(150) NULL,
        DeliveryStatus NVARCHAR(30) NOT NULL
            CONSTRAINT DF_MaintenanceReportDeliveries_Status DEFAULT ('READY'),
        ProviderName NVARCHAR(50) NULL,
        ProviderMessageId NVARCHAR(200) NULL,
        QueuedAt DATETIME2 NULL,
        SentAt DATETIME2 NULL,
        FailedAt DATETIME2 NULL,
        FailureReason NVARCHAR(1000) NULL,
        AttemptCount INT NOT NULL
            CONSTRAINT DF_MaintenanceReportDeliveries_Attempts DEFAULT (0),
        ReportRevisionNumber INT NULL,
        CreatedByUserId NVARCHAR(100) NULL,
        CreatedAt DATETIME2 NOT NULL
            CONSTRAINT DF_MaintenanceReportDeliveries_CreatedAt DEFAULT SYSUTCDATETIME(),
        UpdatedAt DATETIME2 NOT NULL
            CONSTRAINT DF_MaintenanceReportDeliveries_UpdatedAt DEFAULT SYSUTCDATETIME(),
        VersionStamp ROWVERSION,

        CONSTRAINT FK_MaintenanceReportDeliveries_Reports
            FOREIGN KEY (HealthReportId)
            REFERENCES dbo.MaintenanceHealthReports(HealthReportId),
        CONSTRAINT FK_MaintenanceReportDeliveries_Households
            FOREIGN KEY (HouseholdId) REFERENCES dbo.MaintenanceHouseholds(HouseholdId),
        CONSTRAINT CK_MaintenanceReportDeliveries_Status
            CHECK (DeliveryStatus IN ('READY', 'QUEUED', 'SENT', 'FAILED'))
    );

    CREATE INDEX IX_MaintenanceReportDeliveries_Report
        ON dbo.MaintenanceReportDeliveries(HealthReportId, CreatedAt DESC);

    CREATE INDEX IX_MaintenanceReportDeliveries_Queue
        ON dbo.MaintenanceReportDeliveries(DeliveryStatus, QueuedAt);
END;
GO

/* -------------------------------------------------------------------------
   7.5  Technician assignment / authenticated user

   Display names are snapshots for historical reporting; the internal user id is
   the authoritative identity (MERGE_GUIDE 7.5, 12).
   ------------------------------------------------------------------------- */
IF COL_LENGTH('dbo.MaintenanceVisits', 'AssignedTechnicianUserId') IS NULL
    ALTER TABLE dbo.MaintenanceVisits ADD AssignedTechnicianUserId NVARCHAR(100) NULL;
GO
IF COL_LENGTH('dbo.MaintenanceVisits', 'AssignedTechnicianNameSnapshot') IS NULL
    ALTER TABLE dbo.MaintenanceVisits ADD AssignedTechnicianNameSnapshot NVARCHAR(150) NULL;
GO
IF COL_LENGTH('dbo.MaintenanceVisits', 'StartedByUserId') IS NULL
    ALTER TABLE dbo.MaintenanceVisits ADD StartedByUserId NVARCHAR(100) NULL;
GO
IF COL_LENGTH('dbo.MaintenanceVisits', 'CompletedByUserId') IS NULL
    ALTER TABLE dbo.MaintenanceVisits ADD CompletedByUserId NVARCHAR(100) NULL;
GO
IF COL_LENGTH('dbo.MaintenanceVisits', 'FieldStartedAt') IS NULL
    ALTER TABLE dbo.MaintenanceVisits ADD FieldStartedAt DATETIME2 NULL;
GO
IF NOT EXISTS (
    SELECT 1 FROM sys.indexes
    WHERE name = 'IX_MaintenanceVisits_Technician'
      AND object_id = OBJECT_ID('dbo.MaintenanceVisits')
)
    CREATE INDEX IX_MaintenanceVisits_Technician
        ON dbo.MaintenanceVisits(AssignedTechnicianUserId, DueDate);
GO

/* -------------------------------------------------------------------------
   7.8  Filter service pricing  (beyond MERGE_GUIDE section 7)

   Filter service is now a PRICED selection rather than a flag: choosing it on
   an individual refrigeration or icemaker asset raises the annual plan price by
   Wilson's sales price for that asset's filters. Estate Concierge includes
   filters outright, so the same selection costs nothing there.

   Water and air / food-preservation filters are separate customer choices --
   air is common on Sub-Zero and similar premium refrigeration and is never
   selected by default.

   PLACEHOLDER PRICING. The seeded unit prices mirror the $70 placeholder in
   assets/plan-config.js and are NOT approved numbers. When Wilson's filter
   sales-price list is loaded, add rows keyed by PartNumber (leaving the
   kind-level rows as the fallback) and set PriceIsPlaceholder = 0. Pricing
   should be resolved server-side from this table rather than from browser JS
   (context section 34 item 11).
   ------------------------------------------------------------------------- */
IF OBJECT_ID('dbo.MaintenanceFilterPrices', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.MaintenanceFilterPrices (
        FilterPriceId INT IDENTITY(1,1) NOT NULL
            CONSTRAINT PK_MaintenanceFilterPrices PRIMARY KEY,
        FilterKindCode NVARCHAR(20) NOT NULL,
        /* NULL PartNumber = the kind-level fallback price. */
        PartNumber NVARCHAR(100) NULL,
        FilterDescription NVARCHAR(300) NULL,
        UnitSalesPrice DECIMAL(12,2) NOT NULL,
        DefaultQuantity INT NOT NULL
            CONSTRAINT DF_MaintenanceFilterPrices_Quantity DEFAULT (1),
        PriceIsPlaceholder BIT NOT NULL
            CONSTRAINT DF_MaintenanceFilterPrices_Placeholder DEFAULT (1),
        EffectiveFrom DATE NULL,
        EffectiveTo DATE NULL,
        IsActive BIT NOT NULL
            CONSTRAINT DF_MaintenanceFilterPrices_Active DEFAULT (1),
        CreatedAt DATETIME2 NOT NULL
            CONSTRAINT DF_MaintenanceFilterPrices_CreatedAt DEFAULT SYSUTCDATETIME(),
        UpdatedAt DATETIME2 NOT NULL
            CONSTRAINT DF_MaintenanceFilterPrices_UpdatedAt DEFAULT SYSUTCDATETIME(),
        CONSTRAINT CK_MaintenanceFilterPrices_Kind
            CHECK (FilterKindCode IN ('water', 'air')),
        CONSTRAINT CK_MaintenanceFilterPrices_Price
            CHECK (UnitSalesPrice >= 0)
    );

    /* One fallback row per kind; part-number rows are added alongside. */
    CREATE UNIQUE INDEX UX_MaintenanceFilterPrices_KindFallback
        ON dbo.MaintenanceFilterPrices(FilterKindCode)
        WHERE PartNumber IS NULL;

    CREATE UNIQUE INDEX UX_MaintenanceFilterPrices_Part
        ON dbo.MaintenanceFilterPrices(FilterKindCode, PartNumber)
        WHERE PartNumber IS NOT NULL;
END;
GO

/* Per-asset filter selections. Water and air are independent opt-ins, each with
   its own quantity, so the annual price can be recomputed server-side. */
IF COL_LENGTH('dbo.MaintenanceAssets', 'WaterFilterServiceOptIn') IS NULL
    ALTER TABLE dbo.MaintenanceAssets ADD WaterFilterServiceOptIn BIT NOT NULL
        CONSTRAINT DF_MaintenanceAssets_WaterFilterOptIn DEFAULT (0);
GO
IF COL_LENGTH('dbo.MaintenanceAssets', 'AirFilterServiceOptIn') IS NULL
    ALTER TABLE dbo.MaintenanceAssets ADD AirFilterServiceOptIn BIT NOT NULL
        CONSTRAINT DF_MaintenanceAssets_AirFilterOptIn DEFAULT (0);
GO
IF COL_LENGTH('dbo.MaintenanceAssets', 'WaterFilterQuantity') IS NULL
    ALTER TABLE dbo.MaintenanceAssets ADD WaterFilterQuantity INT NULL;
GO
IF COL_LENGTH('dbo.MaintenanceAssets', 'AirFilterQuantity') IS NULL
    ALTER TABLE dbo.MaintenanceAssets ADD AirFilterQuantity INT NULL;
GO

/* Annual filter-service amount priced into the subscription, kept alongside the
   plan amount so the breakdown survives a price-list change. */
IF COL_LENGTH('dbo.MaintenanceSubscriptions', 'FilterServiceAnnualAmount') IS NULL
    ALTER TABLE dbo.MaintenanceSubscriptions ADD FilterServiceAnnualAmount DECIMAL(12,2) NOT NULL
        CONSTRAINT DF_MaintenanceSubscriptions_FilterAmount DEFAULT (0);
GO
IF COL_LENGTH('dbo.MaintenanceSubscriptions', 'FilterServiceDetailJson') IS NULL
    ALTER TABLE dbo.MaintenanceSubscriptions ADD FilterServiceDetailJson NVARCHAR(MAX) NULL;
GO

-- {{SEEDS}}
-- {{FILTER_PRICE_SEED}}

/* -------------------------------------------------------------------------
   New operational views

   Additive only. The base script's three views are left untouched so that
   re-running sql/maintenance_schema.sql cannot revert anything defined here.
   ------------------------------------------------------------------------- */

/*
   Payment readiness. MERGE_GUIDE 7.2: an AR household is payment-ready even
   with no Stripe payment method, so readiness must never be inferred from a
   missing card.
*/
CREATE OR ALTER VIEW dbo.vw_MaintenanceHouseholdPaymentReadiness
AS
SELECT
    h.HouseholdId,
    h.HouseholdReference,
    h.DisplayName AS HouseholdName,
    h.BillingMethodCode,
    h.AccountTerms,
    h.ARStatus,
    h.ExternalARCustomerId,
    pp.PaymentProfileId,
    pp.PaymentProfileStatus,
    pp.CardBrand,
    pp.CardLast4,
    CAST(
        CASE
            WHEN h.BillingMethodCode = 'AR_ACCOUNT'
                 AND ISNULL(h.ARStatus, 'Review') = 'Active' THEN 1
            WHEN h.BillingMethodCode = 'CARD_ON_FILE'
                 AND pp.PaymentProfileId IS NOT NULL
                 AND pp.PaymentProfileStatus = 'Active' THEN 1
            ELSE 0
        END AS BIT
    ) AS PaymentReady,
    CASE
        WHEN h.BillingMethodCode = 'AR_ACCOUNT'
             AND ISNULL(h.ARStatus, 'Review') = 'Active' THEN 'AR_APPROVED'
        WHEN h.BillingMethodCode = 'AR_ACCOUNT' THEN 'ACTION_REQUIRED'
        WHEN pp.PaymentProfileId IS NULL THEN 'ACTION_REQUIRED'
        WHEN pp.PaymentProfileStatus <> 'Active' THEN 'ACTION_REQUIRED'
        ELSE 'READY_TO_CHARGE'
    END AS PaymentReadinessCode
FROM dbo.MaintenanceHouseholds h
OUTER APPLY (
    SELECT TOP (1)
        p.PaymentProfileId, p.PaymentProfileStatus, p.CardBrand, p.CardLast4
    FROM dbo.MaintenancePaymentProfiles p
    WHERE p.HouseholdId = h.HouseholdId
    ORDER BY
        CASE WHEN p.PaymentProfileStatus = 'Active' THEN 0 ELSE 1 END,
        p.PaymentProfileId DESC
) pp;
GO

/*
   Field progress per visit. Drives the Command Center's view of what the
   technician has finished and whether the report package is ready
   (MERGE_GUIDE 23).
*/
CREATE OR ALTER VIEW dbo.vw_MaintenanceFieldProgress
AS
SELECT
    v.VisitId,
    v.HouseholdId,
    h.DisplayName AS HouseholdName,
    v.DueDate,
    v.VisitStatus,
    v.AssignedTechnicianUserId,
    v.AssignedTechnicianNameSnapshot,
    v.FieldStartedAt,
    v.CompletedAt,
    COUNT(va.VisitAssetId) AS ScopedAssetCount,
    SUM(CASE WHEN fi.InspectionStatus IN ('FIELD_COMPLETE', 'REPORT_GENERATED')
             THEN 1 ELSE 0 END) AS CompletedAssetCount,
    SUM(CASE WHEN fi.InspectionStatus = 'IN_PROGRESS' THEN 1 ELSE 0 END)
        AS InProgressAssetCount,
    SUM(CASE WHEN fi.FieldInspectionId IS NULL
                   OR fi.InspectionStatus = 'NOT_STARTED'
             THEN 1 ELSE 0 END) AS NotStartedAssetCount,
    SUM(CASE WHEN fi.FollowUpRequired = 1 THEN 1 ELSE 0 END) AS FollowUpCount,
    CAST(
        CASE WHEN COUNT(va.VisitAssetId) > 0
              AND COUNT(va.VisitAssetId) = SUM(
                    CASE WHEN fi.InspectionStatus IN ('FIELD_COMPLETE', 'REPORT_GENERATED')
                         THEN 1 ELSE 0 END)
             THEN 1 ELSE 0 END AS BIT
    ) AS AllAssetsFieldComplete,
    AVG(CAST(fi.FinalHealthScore AS DECIMAL(6,2))) AS AverageHealthScore
FROM dbo.MaintenanceVisits v
INNER JOIN dbo.MaintenanceHouseholds h
    ON h.HouseholdId = v.HouseholdId
LEFT JOIN dbo.MaintenanceVisitAssets va
    ON va.VisitId = v.VisitId
LEFT JOIN dbo.MaintenanceFieldInspections fi
    ON fi.VisitId = va.VisitId
   AND fi.AssetId = va.AssetId
GROUP BY
    v.VisitId, v.HouseholdId, h.DisplayName, v.DueDate, v.VisitStatus,
    v.AssignedTechnicianUserId, v.AssignedTechnicianNameSnapshot,
    v.FieldStartedAt, v.CompletedAt;
GO

/*
   Resolved protocol per asset. The SQL counterpart of
   WILSON_PROTOCOL.resolveCheckpointSet(), including the IMUC override.
   Compare against MaintenanceAssets.CheckpointSetCode to find assets still
   carrying a stale snapshot.
*/
CREATE OR ALTER VIEW dbo.vw_MaintenanceAssetProtocol
AS
SELECT
    resolution.AssetId,
    resolution.HouseholdId,
    resolution.AssetCategory,
    resolution.AssetTypeCode,
    resolution.AssetTypeName,
    resolution.CustomerCategoryCode,
    resolution.StoredCheckpointSetCode,
    resolution.ResolvedTemplateCode,
    CAST(CASE WHEN resolution.StoredCheckpointSetCode IS NOT NULL
                   AND resolution.StoredCheckpointSetCode <> resolution.ResolvedTemplateCode
              THEN 1 ELSE 0 END AS BIT) AS StoredValueIsStale
FROM (
    /* Non-IMUC: assignment by precedence, then the stored snapshot only if it
       names a real template, then generic. The snapshot ranks BELOW config and
       above generic -- identical to step 4 of resolveCheckpointSet(). */
    SELECT
        a.AssetId,
        a.HouseholdId,
        a.AssetCategory,
        a.AssetTypeCode,
        a.AssetTypeName,
        a.CustomerCategoryCode,
        a.CheckpointSetCode AS StoredCheckpointSetCode,
        COALESCE(resolved.TemplateCode, snapshot.TemplateCode, 'generic')
            AS ResolvedTemplateCode
    FROM dbo.MaintenanceAssets a
    OUTER APPLY (
        SELECT TOP (1) pa.TemplateCode
        FROM dbo.MaintenanceProtocolAssignments pa
        WHERE pa.IsActive = 1
          AND (
                (pa.AssignmentScope = 'APPLIANCE_TYPE' AND pa.ScopeCode = a.AssetTypeCode)
             OR (pa.AssignmentScope = 'CUSTOMER_CATEGORY' AND pa.ScopeCode = a.CustomerCategoryCode)
          )
        ORDER BY pa.Precedence, pa.ProtocolAssignmentId
    ) resolved
    OUTER APPLY (
        SELECT TOP (1) t.TemplateCode
        FROM dbo.MaintenanceProtocolTemplates t
        WHERE t.TemplateCode = a.CheckpointSetCode
          AND t.IsActive = 1
        ORDER BY t.TemplateVersion DESC
    ) snapshot
    WHERE a.AssetCategory <> 'imuc'

    UNION ALL

    /* IMUC group membership always wins, before any assignment lookup. */
    SELECT
        a.AssetId,
        a.HouseholdId,
        a.AssetCategory,
        a.AssetTypeCode,
        a.AssetTypeName,
        a.CustomerCategoryCode,
        a.CheckpointSetCode AS StoredCheckpointSetCode,
        'icemaker' AS ResolvedTemplateCode
    FROM dbo.MaintenanceAssets a
    WHERE a.AssetCategory = 'imuc'
) resolution;
GO

/* -------------------------------------------------------------------------
   Schema version
   ------------------------------------------------------------------------- */
IF NOT EXISTS (
    SELECT 1 FROM dbo.MaintenanceSchemaVersions WHERE VersionNumber = '0.9'
)
BEGIN
    INSERT INTO dbo.MaintenanceSchemaVersions (VersionNumber, Notes)
    VALUES ('0.9', 'Property areas, AR billing, technician field inspection layer, report delivery tracking, technician user linkage, and versioned lifecycle/protocol configuration. Protocol seeds generated from plan-config.js v{{CONFIG_VERSION}}.');
END;
GO
